/*
 * This code is for Internal Salesforce use only, and subject to change without notice.
 * Customers shouldn't reference this file in any web pages.
 */
Sfdc.ns("SfdcDevConsole.Themes");
(function(){function g(){for(var b in document.styleSheets)if(document.styleSheets.hasOwnProperty(b)){var a=document.styleSheets[b],c;try{c=a.rules||a.cssRules}catch(e){if("SecurityError"!==e.name)throw e;}if(c&&c.length)for(a=0;a<c.length;a++){var f=c[a].selectorText;f&&(".CodeMirror"===f&&c[a].style.getPropertyValue("font-size"))&&(d=c[a].style)}}}SfdcDevConsole.Themes.getThemes=function(){return"3024-day base16-light lesser-dark paraiso-dark 3024-night blackboard paraiso-light the-matrix ambiance cobalt rubyblue tomorrow-night-eighties default midnight twilight ambiance-mobile eclipse monokai vibrant-ink elegant neat solarized xq-dark base16-dark erlang-dark night xq-light".split(" ")};SfdcDevConsole.Themes.getTheme=
function(){return SfdcDevConsole.Preferences.get("cmTheme")};SfdcDevConsole.Themes.changeTheme=function(b){Sfdc.isString(b)&&Ext.getCmp("editors").items.each(function(a){a.cmEditor&&a.cmEditor.codeEditor.setOption("theme",b)})};var d=null;SfdcDevConsole.Themes.changeFontSize=function(b){d||g();d.setProperty("font-size",b+"px");d.setProperty("line-height",Math.ceil(1.3*b)+"px");Ext.getCmp("editors").items.each(function(a){a.cmEditor&&a.cmEditor.codeEditor.refresh()})};SfdcDevConsole.Events.EventDispatcher.on("preferences:changed",
function(b,a){a.cmTheme&&SfdcDevConsole.Themes.changeTheme(a.cmTheme);pref.cmFontSize&&SfdcDevConsole.Themes.changeFontSize(a.cmFontSize)})})();
(function(){function k(a,c,e){Ext.Msg.alert("Could not create "+a,"The "+a+' "'+c+'" '+e+".")}function l(a,c,e){apex.ide.IDE.startProgress(1,"Creating...","Creating new "+a.displayName,"Waiting for response from server...");var b={};a.createBody(b,c);a.createEntity(b,function(d){d.success?(a.open(Sfdc.apply({id:d.id,name:d.name||b.Name||c.name},b)),apex.test.TestResult.updateClassesAndTriggers(),apex.ide.IDE.incrementProgress("Finished!"),Sfdc.isFunction(e)&&e(d.id,c)):Ext.MessageBox.alert("New "+
a.displayName+" Error",d.errorText)})}function m(a,c,e){a.getRecords(function(b){var d,f;d=0;for(f=b.length;d<f;d++)if(b[d].Name===c&&b[d].NamespacePrefix===SfdcDevConsole.namespace){b=a.displayName;Ext.Msg.alert("Duplicate "+b+" name","The "+b+' "'+c+'" is already taken. Use a different name.');return}e()})}function g(a,c,e){var b=c.name||c.Name||"",d=Sfdc.String.escapeToHtml(b);!b||b!==Ext.String.createVarName(b)?k(a.displayName,d,"is not a legal name"):m(a,d,function(){l(a,c,e)})}Sfdc.ns("SfdcDevConsole.ExtentUI");
var h=new Ext.data.JsonStore({fields:["id","name","objectType"],autoLoad:!1});SfdcDevConsole.ExtentUI={createWithClientSideCheck:g,createEntity:function(a,c,e){a.getRecords();a.openCreateUI(function(b){g(a,b,c)},e)},triggerCreateUI:function(a,c){SfdcDevConsole.Extents.SObject.getRecords(function(a){var b=[],d,c;d=0;for(c=a.length;d<c;d++)a[d].triggerable&&b.push(a[d]);h.loadData(b,!1)});Ext.getCmp("triggerWindow")?Ext.getCmp("triggerWindow").show():Ext.create("Ext.window.Window",{title:"New Apex Trigger",
height:200,width:300,closeAction:"hide",id:"triggerWindow",items:[{name:"text",id:"triggerName",fieldLabel:"Name",xtype:"textfield",style:"margin : 5px 15px"},{id:"newTriggerEntities2",xtype:"combo",style:"margin : 0px 15px",fieldLabel:"sObject",editable:!1,queryMode:"local",displayField:"name",valueField:"triggertype",triggerAction:"all",lazyRender:!0,store:h}],buttons:[{text:"Submit",id:"triggerSubmitButton",formBind:!0,scope:this,handler:function(){var a=Ext.getCmp("triggerWindow"),b=a.items;c({triggerType:b.get(1).getRawValue(),
name:b.get(0).getValue()});a.hide()}}]}).show()},defaultCreateUI:function(a,c){Ext.Msg.prompt("New "+a.displayName,"Please enter a name for your new "+a.displayName,function(a,b){"ok"==a&&c({name:b})})}}})();
Ext.define("apex.ajax.ProgressModel",{idProperty:"sequenceNumber",extend:"Ext.data.Model",fields:[{name:"reqId"},{name:"nice"},{name:"groupId"},{name:"desc"},{name:"status"},{name:"queuedTime"},{name:"startTime"},{name:"ajaxEndTime"},{name:"endTime"},{name:"payload"},{name:"handlerError"},{name:"ajaxError"},{name:"delay"},{name:"url"},{name:"caller"}]});Ext.define("apex.ajax.ProgressStore",{extend:"Ext.data.Store",model:"apex.ajax.ProgressModel"});
Ext.define("apex.editor.ProgressPanel",{extend:"Ext.grid.GridPanel",alias:"widget.progresspanel",Status:{QUEUED:LC.getLabel("Progress","Queued"),WAITING:LC.getLabel("Progress","Waiting"),IN_PROGRESS:LC.getLabel("Progress","InProgress"),FAILED:LC.getLabel("Progress","Failed"),FINISHED:LC.getLabel("Progress","Finished"),FINISHED_HANDLER_EXCEPTION:LC.getLabel("Progress","FinishedException)"),FAILED_HANDLER_EXCEPTION:LC.getLabel("Progress","FailedException)"),GROUP_FAILED:LC.getLabel("Progress","GroupFailed"),
CONFIG_ERROR:LC.getLabel("Progress","ConfigError")},MAX_TABLE_SIZE:300,REDUCTION_SIZE:200,filterFinishedJobs:function(a){var b=this;a?b.store.filter([{filterFn:function(a){return a.get("status")!==b.Status.FINISHED}}]):b.store.clearFilter()},initComponent:function(){Ext.apply(this,{title:LC.getLabel("Progress","Progress"),xtype:"grid",forceFit:!0,plugins:Ext.create("apex.plugins.GridCellPopup"),store:Ext.create("apex.ajax.ProgressStore"),columns:[{id:"reqId",width:30,header:"ReqId",dataIndex:"reqId"},
{header:LC.getLabel("Progress","Nice"),width:30,dataIndex:"nice"},{header:LC.getLabel("Progress","Order"),width:30,dataIndex:"groupId"},{header:LC.getLabel("Progress","Description"),width:400,dataIndex:"desc"},{header:LC.getLabel("Progress","Status"),width:55,dataIndex:"status"},{header:LC.getLabel("Progress","Queued"),width:30,dataIndex:"queuedTime",hidden:!0,renderer:Ext.util.Format.dateRenderer("g:i:s")},{header:LC.getLabel("Progress","Start"),width:30,dataIndex:"startTime",renderer:Ext.util.Format.dateRenderer("g:i:s")},
{header:LC.getLabel("Progress","AjaxEnd"),width:30,dataIndex:"ajaxEndTime",hidden:!0,renderer:Ext.util.Format.dateRenderer("g:i:s")},{header:LC.getLabel("Progress","End"),width:30,dataIndex:"endTime",renderer:Ext.util.Format.dateRenderer("g:i:s")},{header:LC.getLabel("Progress","Duration"),width:30,dataIndex:"duration"},{header:LC.getLabel("Progress","HandlerError"),width:30,dataIndex:"handlerError"},{header:LC.getLabel("Progress","AjaxError"),width:25,dataIndex:"ajaxError"},{header:LC.getLabel("Progress",
"Delay"),width:30,dataIndex:"delay"},{header:LC.getLabel("Progress","URL"),width:30,dataIndex:"url",hidden:!0},{header:LC.getLabel("Progress","Caller"),width:30,dataIndex:"caller",hidden:!0}]});var a=new Ext.form.Checkbox({id:"hideFinishedCheckbox",boxLabel:LC.getLabel("Progress","HideFinishedRuns"),checked:this.filtered?!0:!1,listeners:{change:function(a,b){this.getBubbleParent().getBubbleParent().filterFinishedJobs(b)}}}),b={text:LC.getLabel("Progress","CancelAllDeployments"),id:"cancelAllDeployments",
enabled:!0,handler:function(){var a=this;a.disable();apex.ide.Container.cancelQueuedDeployments(apex.ide.IDE.containerId,function(){try{for(var b=Ext.getCmp("editors"),e=0;e<b.items.length;e++){var f=b.items.get(e);f instanceof apex.editor.CompileableSourceEditor&&f.setSaving(!1)}}finally{a.enable()}})}};this.tbar=[a,b];this.finishedBox=a;apex.editor.ProgressPanel.superclass.initComponent.apply(this,arguments)},getFirstQueued:function(a){for(var b=[],d=0;d<this.store.data.items.length;d++){var c=
a.store.data.items[d],e=c.data;(e.status===a.Status.QUEUED||e.status===a.Status.WAITING)&&b.push(c)}b.sort(function(a,b){var c=a.data,d=b.data;if(c.nice===d.nice)if(c.groupId===d.groupId){if(c.reqId===d.reqId)return 0;if(c.reqId>d.reqId)return 1;if(c.reqId<d.reqId)return-1}else{if(c.groupId>d.groupId)return 1;if(c.groupId<d.groupId)return-1}else{if(c.nice>d.nice)return 1;if(c.nice<d.nice)return-1}});return 0>=b.length?null:b[0]},getUrlInfoFromConfig:function(a){return Ext.htmlEncode(a.url+" "+(a.method?
a.method:""))},enqueue:function(a,b,d,c,e,f){var k=this.reqCounter++,g;g=b||0===b?b:this.groupCounter++;var h;h="function"!==typeof a?this.getUrlInfoFromConfig(a):LC.getLabel("Progress","TBD");this.store.insert(0,{reqId:k,groupId:g,nice:e?e:0,desc:c?c:h,status:f?f:this.Status.QUEUED,queuedTime:new Date,startTime:null,endTime:null,duration:null,payload:a,delay:d,caller:arguments.callee.caller.$name,url:h});this.isRunning||this.dequeue();return g},cleanUpStaleRows:function(){var a=this.finishedBox.checked,
b=a?this.store.snapshot:this.store;if(b.getCount()>this.MAX_TABLE_SIZE){for(var d=this.reqCounter-this.REDUCTION_SIZE,c=[],e=0;e<b.getCount();e++){var f=b.getAt(e);f.data.status===this.Status.FINISHED&&f.data.reqId<d&&c.push(f)}a?b.removeAll(c):b.remove(c)}},dequeue:function(){this.isRunning=!0;var a=this,b=this.getFirstQueued(a);if(b){var d=b.data;if(d.status==a.Status.WAITING)this.isRunning=!1;else if(0<=this.store.findBy(function(b){b=b.data;if(b.groupId==d.groupId){if(b.status==a.Status.IN_PROGRESS)throw LC.getLabel("Progress",
"ExecuteRecordSameTime",Ext.JSON.encode(b),Ext.JSON.encode(d));if(b.status!==a.Status.FINISHED&&b.status!==a.Status.QUEUED)return!0}return!1})){b.set("status",a.Status.GROUP_FAILED);var c=new Date;b.set("startTime",c);b.set("endTime",c);b.set("duration",0);b.commit();a.dequeue()}else b.set("status",a.Status.WAITING),b.commit(),a.isRunning=!1,c=function(){d.status===a.Status.WAITING&&(a.isRunning?(b.set("status",a.Status.QUEUED),b.set("delay",0),b.commit()):(a.isRunning=!0,a.processRecord(b,a,d)))},
d.delay?this._setTimeout(c,d.delay):c()}else this.cleanUpStaleRows(),this.isRunning=!1},processRecord:function(a,b,d){a.set("status",b.Status.IN_PROGRESS);a.set("startTime",new Date);a.commit();var c=null;if("function"===typeof d.payload)try{c=d.payload(),a.set("url",this.getUrlInfoFromConfig(c))}catch(e){a.set("status",b.Status.CONFIG_ERROR),a.set("handlerError",e),a.commit(),b.dequeue()}else c=d.payload;if(c){var f=c.success,k=!1,g=c.failure;!f&&c.continuation&&(f=c.continuation,k=!0);var h=function(c,
e){try{a.set("ajaxEndTime",new Date),"function"===typeof g&&g.call(this,c,e),a.set("status",b.Status.FAILED),d.ajaxError=c?Sfdc.String.escapeToHtml(c.responseText):LC.getLabel("Progress","ResponseNull")}catch(f){throw a.set("status",b.Status.FAILED_HANDLER_EXCEPTION),a.set("handlerError",f),f;}finally{a.set("endTime",new Date),a.set("duration",d.endTime-d.startTime),a.commit(),b.dequeue()}},l=function(c,e){try{a.set("ajaxEndTime",new Date),"function"===typeof f&&f.call(this,c,e),a.set("status",b.Status.FINISHED)}catch(g){throw a.set("status",
b.Status.FINISHED_HANDLER_EXCEPTION),a.set("handlerError",g),g;}finally{a.set("endTime",new Date),a.set("duration",d.endTime-d.startTime),a.commit(),b.finishedBox&&b.filterFinishedJobs(b.finishedBox.checked),b.dequeue()}};k?c.continuation=l:c.success=l;g?c.failure=h:c.additionalFailureHandler=h;SfdcDevConsole.ToolingAPI.request(c)}else b.dequeue()},_setTimeout:function(a,b){setTimeout(a,b)},getNextGroupId:function(){return this.groupCounter++},isRunning:!1,reqCounter:0,groupCounter:0});
Ext.define("apex.ide.Container",{singleton:!0,getOrCreateContainer:function(a,b){var c=apex.ide.IDE.queryUrl("SELECT Id, Name FROM MetadataContainer WHERE Name\x3d'"+a+"' ORDER BY lastModifiedDate DESC",!0),e=Ext.getCmp("progress").enqueue({url:c,continuation:function(d){if(d.done){var f,g=[],h,m=function(d){apex.ide.Container._reparentContainerMembers(a,h,d);b(d,e)};for(f=0;f<d.totalSize;f++){if(18===a.length)b(d.records[f].Id,e);else if(15===a.length){h=d.records[0].Id;var k=ApiUtils.to18CharId(a);
apex.ide.Container._createContainerReparent(k,e,m)}g.push(d.records[f].Id)}g.length?1<g.length&&apex.ide.IDE.sendGack("Returned wrong number of rows: "+g.length+" on "+c+". Workspace ID: "+a+". Container IDs: "+JSON.stringify(g)):18===a.length?apex.ide.Container.getOrCreateContainer(ApiUtils.to15CharId(a),b):apex.ide.Container._createContainer(ApiUtils.to18CharId(a),e,b)}},alertOnFailure:!0,failureMessage:"Could not fetch container for workspace \x3d "+a},null,null,"Fetching MetadataContainer for workspace "+
a)},_reparentContainerMembers:function(a,b,c){SfdcDevConsole.ToolingAPI.query("SELECT Id from MetadataContainerMember WHERE MetadataContainerId IN (SELECT Id FROM MetadataContainer WHERE Name \x3d '"+a+"')",{continuation:function(a){if(a.done){var d;for(d=0;d<a.totalSize;d++)SfdcDevConsole.ToolingAPI.request({url:"/_ui/common/apex/debug/ApexCSIAPI",data:{action:"CLEAN_WORKSPACE",entity:a.records[d].Id,newContainerID:c}});SfdcDevConsole.ToolingAPI.DELETE("MetadataContainer",b,{gackOnFailure:!0,failureMessage:"Unable to delete old container "+
b})}}})},_createContainerReparent:function(a,b,c){var e=apex.ide.IDE.sobjectUrl("MetadataContainer",!0),d={Name:a};Ext.getCmp("progress").enqueue({url:e,data:d,method:"POST",continuation:function(a){c(a.id)},alertOnFailure:!1,gackOnFailure:!0,failureMessage:"Failed to create container for workspaceId\x3d"+a},b,null,"Creating MetadataContainer for workspaceId "+a)},_createContainer:function(a,b,c){var e=apex.ide.IDE.sobjectUrl("MetadataContainer",!0),d={Name:a};Ext.getCmp("progress").enqueue({url:e,
data:d,method:"POST",continuation:function(a){c(a.id)},alertOnFailure:!0,failureMessage:"Failed to create container for workspaceId\x3d"+a},b,null,"Creating MetadataContainer for workspaceId "+a)},cancelQueuedDeployments:function(a,b){this._getAllQueuedDeployments(a,function(c){c.done&&apex.ide.Container._cancelQueuedDeploymentsHelper(a,c.records,b)},b)},_cancelQueuedDeploymentsHelper:function(a,b,c){if(0===b.length)Sfdc.isFunction(c)&&c();else{var e=b[0].Id;b=b.slice(1);apex.ide.Container._cancelDeployment(e,
function(){apex.ide.Container._cancelQueuedDeploymentsHelper(a,b,c)})}},_getAllQueuedDeployments:function(a,b,c){var e=apex.ide.IDE.queryUrl("SELECT Id, IsCheckOnly FROM ContainerAsyncRequest WHERE MetadataContainerId\x3d'"+a+"' AND State\x3d'"+apex.ide.Container.DeployStatuses.QUEUED+"' ORDER BY CreatedDate",!0);Ext.getCmp("progress").enqueue({url:e,continuation:b,failure:function(b){Sfdc.isFunction(c)&&c();SfdcDevConsole.ToolingAPI.handleFailedRequest(b,"Could not fetch queued deployments for \x3d "+
a,!0,!0)}},null,null,"Getting all queued deployments for container\x3d"+a,this._cancellationNice)},_getCreateContainerMemberConfig:function(a,b,c,e,d,f){if(void 0===a)throw"Must supply memberType";a=apex.ide.IDE.sobjectUrl(a,!0);e={MetadataContainerId:c,ContentEntityId:d,Body:e};b.metadata&&(e.Metadata=b.metadata);return{url:a,data:e,method:"POST",continuation:f,alertOnFailure:!0,failureMessage:"Failed to create createContainerMember for containerId\x3d"+c}},callbacks:{},instancesPerDeploy:{},createDeployment:function(a,
b,c,e,d,f){var g=d,h=Date.now(),m={};if(b)for(var k=0;k<b.length;k++)m[b[k].id]=b[k].instance;d=function(){var a=Date.now()-h;apex.ide.IDE.CompileDelayTime=0.8*apex.ide.IDE.CompileDelayTime+0.2*a;g&&"function"===typeof g.call&&g.apply(this,arguments)};var n=apex.ide.IDE.sobjectUrl("ContainerAsyncRequest",!0);if(null===f||void 0===f)f=Ext.getCmp("progress").getNextGroupId();var l=!e&&b&&1===b.length?b[0].containerMemberId:null;Ext.getCmp("progress").enqueue(function(){var b={MetadataContainerId:a,
MetadataContainerMemberId:l,IsRunTests:c,IsCheckOnly:e};return{url:n,data:b,method:"POST",continuation:function(a){Sfdc.log("Deployment "+a.id+" enqueued at "+new Date+" "+Ext.JSON.encode(b));apex.ide.Container.callbacks[a.id]=d;apex.ide.Container.instancesPerDeploy[a.id]=m},alertOnFailure:!0,failureMessage:"Failed to create deployment"}},f,null,"Creating deployment for containerId "+a+(l?" metadataContainerMemberId\x3d"+l:"")+" Save\x3d"+!e+" runTests\x3d"+c,this._deploymentNice)},_getPatchContainerMemberConfig:function(a,
b,c,e,d,f){a=apex.ide.IDE.sobjectUrl(a,!0,e,!0);c={Body:c};d&&(c.Metadata=d);return{url:a,data:c,method:"POST",continuation:f,alertOnFailure:!0,failureMessage:"Unable to patch container member."}},_cancelDeployment:function(a,b){var c=apex.ide.IDE.sobjectUrl("ContainerAsyncRequest",!0,a,!0),e={State:apex.ide.Container.DeployStatuses.ABORTED};Ext.getCmp("progress").enqueue({url:c,data:e,method:"POST",continuation:b,alertOnFailure:!0,failureMessage:"Unable to cancel deployment."},null,null,"Cancelling deployment"+
a,this._cancellationNice)},deleteContainerMember:function(a,b,c){var e=this._enqueueDeleteContainerMember(b.id,a,b,function(){Sfdc.isFunction(c)&&c();delete b.containerMemberId;apex.ide.Container.createDeployment(a,null,!1,!0,null,e)})},_enqueueDeleteContainerMember:function(a,b,c,e){return Ext.getCmp("progress").enqueue(function(){var b=SfdcDevConsole.Extents.getExtentFromId(a).memberType;SfdcDevConsole.Events.EventDispatcher.fire("problems:clear",[[c.Id]]);if(c.containerMemberId)return{url:apex.ide.IDE.sobjectUrl(b,
!0,c.containerMemberId),method:"DELETE",continuation:e,alertOnFailure:!0,failureMessage:"Unable to delete container member "+c.containerMemberId};Sfdc.isFunction(e)&&e()},null,null,"deleteContainerMember containerId\x3d"+b+" entityId\x3d"+a+" containerMemberId\x3d"+c.containerMemberId,this._deploymentNice)},deleteContainerMembersNoCompile:function(a,b,c){for(var e in b)b.hasOwnProperty(e)&&this._enqueueDeleteContainerMember(e,a,{containerMemberId:b[e].Id},null);Sfdc.isFunction(c)&&c()},saveContainerDeployMulti:function(a,
b,c,e,d){try{for(var f=Ext.getCmp("progress").getNextGroupId(),g=0;g<a.length;g++)this._createOrPatchContainerMember(a[g],b,e,f);this.createDeployment(b,a,e,c,d,f)}catch(h){Ext.Msg.alert(""+(c?"Compile":"Save")+" error",h),d&&d()}},_createOrPatchContainerMember:function(a,b,c,e){var d=a.getValue();if(Sfdc.isEmpty(d))throw"The editor "+a.Name+" has an empty body";var f=SfdcDevConsole.Extents.getExtentFromId(a.id).memberType;Ext.getCmp("progress").enqueue(function(){return a.containerMemberId?apex.ide.Container._getPatchContainerMemberConfig(f,
b,d,a.containerMemberId,a.metadata,null):apex.ide.Container._getCreateContainerMemberConfig(f,a,b,d,a.id,function(b){a.containerMemberId=b.id})},e,null,"Creating or Updating containerMember for containerId\x3d"+b,this._deploymentNice)},getContainerMembers:function(a,b,c,e,d,f){var g=[];if(d)SfdcDevConsole.Extents.each(function(a){void 0!==a.memberType&&a.isApiAccessible()&&g.push(a)});else{var h=Ext.getCmp("editors");d={};for(var m=0;m<h.items.length;m++){var k=h.items.get(m),n=SfdcDevConsole.Extents.getExtentFromId(k.id);
n&&k.containerMemberId&&(d[n.keyPrefix]=n)}for(var l in d)d.hasOwnProperty(l)&&(h=d[l],"object"===typeof h&&void 0!==h.memberType&&h.isApiAccessible()&&g.push(h))}g.push(c);this._processContainerQueryWork(a,b,e,g,[],f)},_processContainerQueryWork:function(a,b,c,e,d,f){var g=b?" AND Id\x3d'"+b+"'":"";if("function"===typeof e[0])e[0](d);else{var h=e[0];e=e.slice(1);var m=h.memberType,g=apex.ide.IDE.queryUrl("SELECT Id, "+(h.hasBody?"Body, ":"")+" LastSyncDate, ContentEntityId, "+(h.hasSymbols?"SymbolTable, ":
"")+"ContentEntity.Name, ContentEntity.LastModifiedDate, Metadata FROM "+m+" WHERE MetadataContainerId \x3d '"+a+"'"+g,!0),k=this;Ext.getCmp("progress").enqueue({url:g,continuation:function(g){if(g.done)d.push(g),k._processContainerQueryWork(a,b,c,e,d,f);else throw"result.done is false";},alertOnFailure:!0,failureMessage:"Could not fetch symbol tables or timestamps for "+b},c,null,"Getting members of "+m+" for containerId\x3d"+a+(b?" containerMemberId\x3d"+b:""),f?0:this._deploymentNice)}},_getDeploymentById:function(a,
b,c){var e=apex.ide.IDE.queryUrl("SELECT Id, MetadataContainerId, MetadataContainerMemberId, State, IsCheckOnly, DeployDetails, ErrorMsg FROM ContainerAsyncRequest WHERE Id\x3d'"+a+"'",!0);Ext.getCmp("progress").enqueue({url:e,continuation:b,failure:function(b){Sfdc.isFunction(c)&&c();SfdcDevConsole.ToolingAPI.handleFailedRequest(b,"Could not fetch queued deployments for \x3d "+a,!0,!0)}},null,null,"Getting deployment for id\x3d"+a,this._cancellationNice)},restoreEditors:function(a){a.IsCheckOnly||
(a.MetadataContainerMemberId?Ext.getCmp("editors").items.each(function(b){if(a.MetadataContainerMemberId==b.containerMemberId)return b.setSaving(!1),!1}):Ext.getCmp("editors").items.each(function(a){a instanceof apex.editor.CompileableSourceEditor&&a.setSaving(!1)}))},logDeploymentToServer:function(a,b){Sfdc.logServer("containerDeploy",{useragent:window.navigator.userAgent,carId:a,notified:b,sentToLog:Date.now(),timezoneOffset:(new Date).getTimezoneOffset()});var c=0;do c=Sfdc.ServerLogging.flush(),
Sfdc.isNumber(c)||(c=0);while(0<c)},finishDeploy:function(a){var b=Date.now();this._getDeploymentById(a,function(c){if(c.done){if(0===c.totalSize)throw"Unknown deploymentId "+deploymentId;var e=Ext.getCmp("progress").getNextGroupId(),d=c.records[0];if(d.State!=apex.ide.Container.DeployStatuses.QUEUED){if(d.State==apex.ide.Container.DeployStatuses.ERROR)throw apex.ide.Container.restoreEditors(d),e=d.ErrorMsg+" for deploymentId\x3d"+d.Id+"  If this persists, please contact customer support.",Ext.Msg.alert("Deployment Error",
e),e;if(!(d.State==apex.ide.Container.DeployStatuses.INVALIDATED||d.State==apex.ide.Container.DeployStatuses.ABORTED))if(d.State==apex.ide.Container.DeployStatuses.COMPLETED||apex.ide.Container.DeployStatuses.FAILED){c=!d.IsCheckOnly;var f=d.ErrorMsg?d.ErrorMsg:"",g=[];try{g=d.DeployDetails.componentFailures||[]}catch(h){f+=" (Error parsing compile errors)"}var m=d.State==apex.ide.Container.DeployStatuses.COMPLETED&&0===g.length&&0===f.length,k={results:g,errorText:f,success:m};apex.ide.Container.logDeploymentToServer(a,
b);Sfdc.log("Deployment "+a+" finished in state "+d.State+" "+Ext.JSON.encode(k));if(d.State&&apex.ide.Container.DeployStatuses.FAILED&&f){g=!0;if(0<=f.indexOf("object has been modified on server")){var n=f.match(/Could not save (\w+),/),l=n?n[1]:"",p=null;Ext.getCmp("editors").items.each(function(a){a.Name===l&&(p=a)});p&&(g=!1,Ext.MessageBox.confirm("Replace contents now?","The file "+p.Name+" has been modified and cannot be saved. Replace contents with new revision now?",function(a){"yes"==a&&
apex.ide.Container.deleteContainerMember(apex.ide.IDE.containerId,p,function(){p.clearDirty();p.fireEvent("load")})},p))}g&&Ext.MessageBox.alert("Deployment Failed",f)}apex.ide.Container.getContainerMembers(c?d.Id:d.MetadataContainerId,d.MetadataContainerMemberId,function(b){k.symbolTables={};for(var c={},e={},f=0;f<b.length;f++)for(var g=b[f],h=g.totalSize,n=0;n<h;n++){var l=g.records[n],p=l.SymbolTable;p&&(k.symbolTables[l.ContentEntityId]=p);p=l.ContentEntity.Name;c[l.ContentEntityId]={timestamp:Ext.Date.parse(l.ContentEntity.LastModifiedDate,
"c").getTime(),name:p};l.Metadata&&(e[l.ContentEntityId]=l.Metadata)}k.timestamps=c;k.metadataRecords=e;apex.editor.CompileableSourceEditor.processResults(k,!d.IsCheckOnly,!d.MetadataContainerMemberId,apex.ide.Container.instancesPerDeploy[a]);if(apex.ide.Container.callbacks[a])apex.ide.Container.callbacks[a](!m,a)},e,!1,d.IsCheckOnly)}}}"function"===typeof continuation&&continuation()})},DeployStatuses:{QUEUED:"Queued",INVALIDATED:"Invalidated",COMPLETED:"Completed",ERROR:"Error",FAILED:"Failed",
ABORTED:"Aborted"},_deployPollTimeMillis:2E3,_deployDisplaySlowSaveMsgIteration:3,_deploymentNice:-1,_cancellationNice:-2,_deployPollTimeoutMillis:18E5,_deployPollFailureTimeoutMillis:3E4});
Ext.define("apex.ide.ShortcutRegistry",{statics:{scs:[],scsNames:[],add:function(a){-1===Sfdc.Array.indexOf(apex.ide.ShortcutRegistry.scsNames,a.name)&&(this.scs.push(a),this.scsNames.push(a.name))},CTRL:"CTRL+",SHIFT:"SHIFT+",ALT:"ALT+",win:Ext.create("Ext.window.Window",{id:"ShortcutRegistry",width:650,height:500,closeAction:"hide",autoScroll:!0,items:{xtype:"panel",id:"ShortcutWindowHTML",height:900,autoEl:{tag:"div"}},generateShortcutList:function(){apex.ide.ShortcutRegistry.add({name:LC.getLabel("Shortcuts",
"VFPreview"),key:"J",ctrl:!0,alt:!1});apex.ide.ShortcutRegistry.add({name:LC.getLabel("Shortcuts","GotoDeclaration"),key:"N",ctrl:!0,alt:!0});apex.ide.ShortcutRegistry.add({name:LC.getLabel("Shortcuts","CommandLine"),key:"L",ctrl:!0,shift:!0});apex.ide.ShortcutRegistry.add({name:LC.getLabel("Shortcuts","HistoryBack"),key:",",ctrl:!0});apex.ide.ShortcutRegistry.add({name:LC.getLabel("Shortcuts","HistoryForward"),key:".",ctrl:!0});apex.ide.ShortcutRegistry.add({name:LC.getLabel("Shortcuts","NavigateLeft"),
key:"Page Up",ctrl:!0});apex.ide.ShortcutRegistry.add({name:LC.getLabel("Shortcuts","NavigateRight"),key:"Page Down",ctrl:!0});apex.ide.ShortcutRegistry.add({name:LC.getLabel("Shortcuts","Fullscreen"),key:"F11"});apex.ide.ShortcutRegistry.add({name:LC.getLabel("Shortcuts","EscapeFullscreen"),key:"Esc"})},listeners:{afterrender:function(a){this.generateShortcutList();a.setTitle(LC.getLabel("Shortcuts","title"));a='\x3ctable style\x3d"margin: 10px"\x3e';for(var d=0;d<apex.ide.ShortcutRegistry.scs.length;d++){var c=
apex.ide.ShortcutRegistry.scs[d];if(!Sfdc.isBoolean(apex.ide.IDE[c.perm])||apex.ide.IDE[c.perm]){var b="";c.ctrl&&(b+=apex.ide.ShortcutRegistry.CTRL);c.shift&&(b+=apex.ide.ShortcutRegistry.SHIFT);c.alt&&(b+=apex.ide.ShortcutRegistry.ALT);b+=c.key.toUpperCase();a+="\x3ctr\x3e\x3ctd\x3e"+c.name+'\x3c/td\x3e\x3ctd class\x3d"shortcutKey"\x3e'+b+"\x3c/td\x3e\x3c/tr\x3e"}}Ext.getCmp("ShortcutWindowHTML").getEl().setHTML(a+"\x3c/table\x3e")}}})}});
Ext.require("Ext.Panel");
Ext.define("apex.ide.IDE",{apiVersion:"v"+SfdcDevConsole.ToolingAPI.version,DEFAULT:"Default",extend:"Ext.util.Observable",singleton:!0,createCustomField:function(a,b){this.createCustomFieldWindow.show();this.createCustomFieldWindow.objectName.setValue(a);this.createCustomFieldWindow.fieldName.setValue(b)},createCustomFieldWindow:Ext.create("Ext.window.Window",{title:"Create Custom Field",id:"createCustomFieldWindow",height:200,width:400,closeAction:function(){this.hide()},listeners:{show:function(a){a.objectName.setValue("");
a.fieldName.setValue("");a.fieldLength.setValue("");a.focus()}},items:[{name:"Object Name",id:"objectName",fieldLabel:"Object Name",xtype:"textfield",style:"margin : 5px 15px",listeners:{afterrender:function(a){a.ownerCt.objectName=a}}},{name:"Field Name",id:"fieldName",fieldLabel:"Field Name",xtype:"textfield",style:"margin : 0px 15px",listeners:{afterrender:function(a){a.ownerCt.fieldName=a}}},{name:"Field Type",id:"fieldType",fieldLabel:"Field Type",xtype:"combo",queryMode:"local",displayField:"name",
valueField:"name",emptyText:"Select a type",store:Ext.create("Ext.data.Store",{fields:["name"],data:[{name:"Text"},{name:"Number"},{name:"Date"}]}),style:"margin : 5px 15px",listeners:{afterrender:function(a){a.ownerCt.fieldType=a;a.win=a.ownerCt},select:function(a,b){a.win.fieldLength.hide();a.win.fieldScale.hide();var c=b&&0<b.length&&b[0].data.name;"Text"===c?a.win.fieldLength.show():"Number"===c&&(a.win.fieldLength.show(),a.win.fieldScale.show())}}},{name:"Length",id:"fieldLength",fieldLabel:"Length",
xtype:"textfield",style:"margin : 0px 15px",hidden:!0,listeners:{afterrender:function(a){a.ownerCt.fieldLength=a}}},{name:"Decimal Place",id:"fieldPrecision",fieldLabel:"Decimal Place",xtype:"textfield",style:"margin : 5px 15px",hidden:!0,listeners:{afterrender:function(a){a.ownerCt.fieldScale=a}}}],buttons:[{text:"Create",id:"createField",formBind:!0,scope:this,handler:function(){var a=Ext.getCmp("createCustomFieldWindow"),b=a.objectName.getValue(),c=a.fieldName.getValue(),d=c,e=a.fieldType.getValue(),
f=c.indexOf("__c");0>f?c+="__c":d=c.substring(0,f);d={fullname:b+"."+c,metadata:{label:d,type:e}};"Text"===e&&(d.metadata.length=parseInt(a.fieldLength.getValue(),0));"Number"===e&&(d.metadata.precision=parseInt(a.fieldLength.getValue(),0),d.metadata.scale=parseInt(a.fieldScale.getValue(),0));var g=Ext.getCmp("apexCSIViewport");g.setLoading(!0);a.hide();SfdcDevConsole.ToolingAPI.create("CustomField",d,{continuation:function(a){g.setLoading(!1);var d=SfdcDevConsole.Core.Autocomplete.Apex.tables.getClass("",
b),f=d.symbolTable;f&&f.properties.push({name:c,scope:"GLOBAL",type:e});d.accessibleSymbols=null;console.log(a)},failure:function(a){g.setLoading(!1);SfdcDevConsole.ToolingAPI.handleFailedRequest(a,"Unable to create custom field "+c+" on "+b,!0,!0)}})}},{text:"Cancel",handler:function(){Ext.getCmp("createCustomFieldWindow").hide()}}]}),openWorkspace:function(a){a===apex.ide.IDE.workspaceId&&apex.ide.IDE.workspaceName||(apex.ide.IDE.updateWorkspaceImpl(null,!0),apex.ide.IDE.closeAll(function(){apex.ide.IDE.startProgress(1,
"Loading...","Loading workspace","Waiting for response from server...");SfdcDevConsole.ToolingAPI.query("SELECT Id, Name, Content FROM IDEWorkspace WHERE (Id\x3d'"+a+"') OR (Name\x3d'"+apex.ide.IDE.DEFAULT+"' AND userid\x3d'"+SfdcDevConsole.myUserId+"')",{continuation:function(b,c){if(b.done){var d;if(0===b.records.length)apex.ide.IDE.createWorkspace(apex.ide.IDE.DEFAULT);else{1===b.records.length?d=b.records[0]:2===b.records.length&&(d=b.records[0].Id===ApiUtils.to18CharId(a)?b.records[0]:b.records[1]);
apex.ide.IDE.workspaceId=d.Id;apex.ide.IDE.workspaceName=d.Name;d=Ext.JSON.decode(d.Content);var e=Ext.getCmp("bottomPanel");d&&d.bottomActive&&e.setActiveTab(d.bottomActive);d&&d.bottomCollapsed&&e.collapse();apex.ide.IDE.fireEvent("workspaceLoaded",d);SfdcDevConsole.ToolingAPI.save("User",{Id:SfdcDevConsole.myUserId,WorkspaceId:ApiUtils.to18CharId(apex.ide.IDE.workspaceId)},{failureMessage:"Unable to save workspace preference"});apex.ide.IDE.incrementProgress("Finished!")}}},failureMessage:"Could not open workspace",
alertOnFailure:!0})},!0))},createWorkspace:function(a,b){var c={Name:a,Content:b&&0===b.indexOf("{")?b:Ext.JSON.encode({}),UserId:SfdcDevConsole.myUserId};SfdcDevConsole.ToolingAPI.create("IDEWorkspace",c,{continuation:function(a,b){apex.ide.IDE.openWorkspace(a.id);apex.ide.IDE.workspaceWindow.hide();Ext.Msg.hide()},failureMessage:"Failed to create workspace "+escapeHTML(a),alertOnFailure:!0})},newWorkspace:function(){Ext.Msg.prompt("New Workspace","Please enter a name for your new workspace",function(a,
b){"ok"==a&&apex.ide.IDE.createWorkspace(b)})},createWorkspaceList:function(){SfdcDevConsole.ToolingAPI.query("SELECT Id, Name FROM IDEWorkspace WHERE UserId\x3d'"+SfdcDevConsole.myUserId+"'",{continuation:function(a,b){if(a.done){for(var c=[],d=0;d<a.records.length;d++)c.push({id:a.records[d].Id,name:Ext.htmlEncode(a.records[d].Name)});Ext.StoreMgr.lookup("workspaces").loadData(c);Ext.StoreMgr.lookup("workspaceList").loadData(c)}},failureMessage:"Could not list workspaces",alertOnFailure:!0})},workspaceWindow:Ext.create("Ext.window.Window",
{title:"Developer Console Workspace",id:"workspaceWindow",height:200,width:400,layout:"fit",closeAction:function(){this.hide()},bbar:[{text:"New",listeners:{afterrender:function(a,b){Ext.getCmp("workspaceWindow").newButton=a}},handler:function(){apex.ide.IDE.newWorkspace()}},{text:"Open",listeners:{afterrender:function(a,b){Ext.getCmp("workspaceWindow").openButton=a}},handler:function(){var a=Ext.getCmp("workspaces").getSelectionModel().getSelection()[0];a&&(apex.ide.IDE.openWorkspace(a.data.id),
apex.ide.IDE.workspaceWindow.hide())}},{text:"Delete",listeners:{afterrender:function(a,b){Ext.getCmp("workspaceWindow").deleteButton=a}},handler:function(){var a=Ext.getCmp("workspaces").getSelectionModel().getSelection()[0];a.data.id===apex.ide.IDE.workspaceId?Ext.MessageBox.alert("Error","Cannot delete current workspace"):Ext.Msg.confirm("Confirm Workspace Delete","Do you really want to delete workspace "+a.data.name+"?",function(b,c){"yes"==b&&apex.ide.IDE.deleteWorkspace(a)})}},{xtype:"tbfill"},
{text:"Cancel",listeners:{afterrender:function(a,b){Ext.getCmp("workspaceWindow").cancelButton=a}},handler:function(){apex.ide.IDE.workspaceWindow.hide()}}],listeners:{show:function(){apex.ide.IDE.createWorkspaceList()}},items:[{xtype:"grid",id:"workspaces",forceFit:!0,selModel:{mode:"SINGLE"},columns:[{header:"id",dataIndex:"id",hidden:!0},{header:"Name",width:100,dataIndex:"name",renderer:function(a,b,c){c.data.name===apex.ide.IDE.workspaceName&&(b.style='font-weight:bold;"');return c.data.name}}],
store:Ext.create("Ext.data.Store",{storeId:"workspaces",idField:"id",fields:[{name:"id"},{name:"name",type:"string"}],sorters:[{property:"name",direction:"ASC"}]}),listeners:{itemdblclick:function(){var a=Ext.getCmp("workspaces").getSelectionModel().getSelection()[0];apex.ide.IDE.openWorkspace(a.data.id);apex.ide.IDE.workspaceWindow.hide()}}}]}),deleteWorkspace:function(a){a&&-1!==Sfdc.Array.indexOf(Ext.getCmp("workspaces").store.data.items,a)&&SfdcDevConsole.ToolingAPI.DELETE("IDEWorkspace",a.data.id,
{success:function(b,c){Ext.StoreMgr.lookup("workspaces").remove(a)},failureMessage:"Unable to save workspace "+a.data.name})},workspace:function(){var a={panels:[]};this.fireEvent("buildingWorkspace",a);for(var b=Ext.getCmp("editors"),c="",d=0;d<b.items.length;d++)try{a.panels.push(b.items.get(d).workspace())}catch(e){c+=b.items.get(d).xtype+": "+e+";"}0<c.length&&apex.ide.IDE.sendGack("Exception asking for workspaces: "+c);c=b.getActiveTab();a.name=apex.ide.IDE.workspaceName;a.execAnonCode=apex.execanon.ExecuteAnonymous.get();
a.openLog=apex.execanon.ExecuteAnonymous.openLog;a.editorTab=b.items.indexOf(c);b=Ext.getCmp("bottomPanel");a.bottomCollapsed=!1!==b.collapsed;a.bottomActive=b.getActiveTab().id;apex.ide.IDE.console&&(a.consoleShown=!apex.ide.IDE.console.isHidden(),a.consoleConfig=apex.ide.IDE.console.getConfig());apex.csi.LogViewer.defaultPerspectiveConfig.perspectiveConfig&&(a.defaultPerspectiveConfig={},a.defaultPerspectiveConfig=apex.csi.LogViewer.defaultPerspectiveConfig);a.window=this.getBrowserWindowInfo();
return a},deleteEditor:function(){var a=Ext.getCmp("editors").getActiveTab();a&&a.DELETE()},getBrowserWindowInfo:function(){return{width:window.outerWidth||Sfdc.Window.getWindowWidth(),height:window.outerHeight||Sfdc.Window.getWindowHeight(),x:void 0!==window.screenLeft?window.screenLeft:window.screenX,y:void 0!==window.screenTop?window.screenTop:window.screenY}},maxWorkspaceLength:64E3,updateWorkspaceImpl:function(a,b){if(!apex.ide.IDE.workspaceName)return null;var c=apex.ide.IDE.workspace(),d=Sfdc.JSON.stringify(c).length;
if(d>apex.ide.IDE.maxWorkspaceLength)return Ext.Msg.alert("Workspace error","The maximum workspace size is "+apex.ide.IDE.maxWorkspaceLength+'. Your workspace "'+apex.ide.IDE.workspaceName+'" is '+d+". To reduce your workspace size, try removing some execute anonymous code or close some views."),c=Ext.getCmp("editors"),apex.ide.IDE.sendPerformanceMetrics("Hit maxmimum workspace size "+d,0,c.items.length,apex.ide.IDE.getOpenTabsInfo(),apex.execanon.ExecuteAnonymous.get().length),null;var e={Id:apex.ide.IDE.workspaceId,
Name:apex.ide.IDE.workspaceName,Content:Ext.JSON.encode(c)};SfdcDevConsole.ToolingAPI.save("IDEWorkspace",e,{async:!b,failure:function(b,c){if(Sfdc.isFunction(a)){var d="";try{d=Sfdc.JSON.parse(b.responseText)[0].message}catch(k){}a(d)}else SfdcDevConsole.ToolingAPI.handleFailedRequest(b,"Unable to save workspace "+e.Name+" response")}})},alertUser:function(a,b,c){Ext.Msg.alert(a,b,c)},hasHeapdumps:function(){return this.bytecode&&this.hasApex},saveAll:function(){if(apex.ide.IDE.authorApex||apex.ide.IDE.hasVisualforce){var a=
Ext.getCmp("editors"),b=[];for(panel=0;panel<a.items.length;panel++){var c=a.items.get(panel);c instanceof apex.editor.ApexEditor&&(!apex.ide.IDE.hasApex||!apex.ide.IDE.authorApex)||c instanceof apex.editor.VisualforceEditor&&(!apex.ide.IDE.hasVisualforce||!apex.ide.IDE.authorVisualforce)||(c instanceof apex.editor.CompileableSourceEditor&&c.dirty?(b.push(c),c.setSaving(!0)):c instanceof apex.editor.SourceFileEditor&&c.dirty&&c.save())}c=function(){for(panel=0;panel<a.items.length;panel++){var b=
a.items.get(panel);b.saving&&(b.setSaving(!1),"visualforceeditor"===b.xtype&&b.openOrRefreshWindow(!1))}};apex.editor.CompileableSourceEditor.saveContainerDeploySingleTask.cancel();0<b.length&&apex.ide.Container.saveContainerDeployMulti(b,apex.ide.IDE.containerId,!1,!1,c)}},htmlDecode:function(a){for(var b,c=/&#(\d+);/;null!==(b=c.exec(a));)a=a.replace(c,String.fromCharCode(parseInt(b[1],10)));return Ext.util.Format.htmlDecode(a)},setUpTestsConfig:function(a,b,c,d,e){return{continuation:function(a,
b){Ext.MessageBox.updateProgress(1,"Success","Run test request has been enqueued");(new Ext.util.DelayedTask(function(){Ext.MessageBox.hide()})).delay(2E3)},failure:function(f,g){if("ALREADY_IN_PROCESS"===JSON.parse(f)[0].errorCode){Ext.MessageBox.hide();var h=function(b){"yes"===b&&apex.test.TestResultBrowser.abortTestRuns(null,a,function(){apex.ide.IDE.runTests(a,c,d,e)})},k=function(f){if("yes"===f){classesToAbort=[];for(f=0;f<a.length;f++)classesToAbort.push(a.classId);apex.test.TestResultBrowser.abortTestRuns(null,
classesToAbort,function(){apex.ide.IDE.runTests(a,b,c,d,e)})}};null!==a&&"01p"==a[0].substring(0,3)&&void 0===a.testMethods?Ext.Msg.show({title:"Error",msg:"Test is already enqueued. Would you like to abort and re-run it?",buttons:Ext.Msg.YESNO,icon:Ext.Msg.ERROR,fn:h}):null!==a&&"01p"==a[0].substring(0,3)&&void 0!==a.testMethods?Ext.Msg.show({title:"Error",msg:"Test is already enqueued. Would you like to abort and re-run it?",buttons:Ext.Msg.YESNO,icon:Ext.Msg.ERROR,fn:k}):Ext.Msg.show({title:"Error",
msg:"Test is already enqueued.",buttons:Ext.Msg.OK,icon:Ext.Msg.ERROR})}else Sfdc.isFunction(c.failure)?c.failure.call(null,f):SfdcDevConsole.ToolingAPI.handleFailedRequest(f,"Failed to enqueue tests.",!0)}}},setUpSyncTestsConfig:function(a){return{success:function(b,c){var d=JSON.parse(b);Ext.getCmp("testResultTree").loaded||apex.test.TestResultBrowser.initTestBrowser();var e=Ext.getCmp("testResultTree").getRootNode(),f=[];if(!d||!d.successes&&!d.failures||0===d.successes.length&&0===d.failures.length)Ext.MessageBox.close(),
Ext.MessageBox.alert("No tests to run","Add test methods to your test class."),e.removeChild(a);else{for(var e=0<d.numFailures?Test.Constants.FAIL:Test.Constants.COMPLETED,g=null,h=null,k=0;k<d.failures.length;k++)g=d.failures[k],h=apex.ide.IDE.getFormattedDuration(g.time),f.push({name:g.methodName,status:Test.Constants.FAIL,stacktrace:g.stackTrace,duration:h,classid:g.id,error:g.message,leaf:!0});for(k=0;k<d.successes.length;k++)g=d.successes[k],h=apex.ide.IDE.getFormattedDuration(g.time),f.push({name:g.methodName,
status:Test.Constants.COMPLETED,duration:h,classid:g.id,leaf:!0});h=g=null;void 0!==d.successes[0]&&null!==d.successes[0]?(g=d.successes[0].name,h=d.successes[0].id):void 0!==d.failures[0]&&null!==d.failures[0]&&(g=d.failures[0].name,h=d.failures[0].id);f={name:g,classid:h,status:e,failures:d.numFailures,total:d.numTestsRun,children:f};a.set("status",e);a.set("failures",d.numFailures);a.set("total",d.numTestsRun);a.appendChild(f);a.commit();Ext.MessageBox.updateProgress(1,"Success");(new Ext.util.DelayedTask(function(){Ext.MessageBox.hide()})).delay(2E3);
Ext.getCmp("aggregateCoverageGrid").load()}},failure:function(a,c){JSON.parse(a);SfdcDevConsole.ToolingAPI.handleFailedRequest(a,"Failed to run tests synchronously.",!0)}}},getTime:function(a){var b=new Date,c=b.getHours(),d=b.getMinutes(),b=b.getSeconds(),e=12<=c?"pm":"am",c=(c%=12)?c:12,d=10>d?"0"+d:d;return a?c+":"+d+":"+(10>b?"0"+b:b)+" "+e:c+":"+d+" "+e},getFormattedDuration:function(a){var b=Math.floor(a/6E4);a=Math.floor(a%6E4/1E3);10>a&&(a="0"+a);return b+":"+a},runTestsSynchronously:function(a){var b=
!1;!Ext.getCmp("runTestsAsyncButton").checked&&1==a.length&&(b=!0);return b},runTests:function(a,b,c,d){Ext.MessageBox.progress("Enqueuing test run...");SfdcDevConsole.Session.initialize();b=apex.ide.IDE.setUpTestsConfig(a,null,b,c,d);SfdcDevConsole.ToolingAPI.runTests(a,b,c,d)},runSelectedTests:function(a,b,c,d,e){SfdcDevConsole.Session.initialize();var f=null;b?(Ext.MessageBox.progress("Running tests synchronously..."),c=Ext.getCmp("testResultTree").getRootNode(),f={name:"TestRun @ "+apex.ide.IDE.getTime(!0),
sync:!0,status:Test.Constants.PROCESSING,failures:null,total:null,children:null},f=c.appendChild(f),c.commit(),f=apex.ide.IDE.setUpSyncTestsConfig(f)):(Ext.MessageBox.progress("Running tests asynchronously..."),f=apex.ide.IDE.setUpTestsConfig(a,b,c,d,e));SfdcDevConsole.ToolingAPI.runSelectedTests(a,f,b,d,e)},justInCase:new Ext.util.DelayedTask(function(){Sfdc.isFunction(this.progressFinished)&&this.progressFinished();this.progressFinished=null;Ext.MessageBox.isVisible()&&(Ext.MessageBox.hide(),Ext.MessageBox.alert("Operation did not complete",
"Long running operation did not complete, continuing in background"))}),losePatience:3E4,startProgress:function(a,b,c,d,e){this.progressFinished=e;if(Ext.MessageBox.isVisible())void 0!==this.currentStep&&(this.numSteps+=a,Ext.MessageBox.updateProgress(1*this.currentStep/this.numSteps,d));else{var f=this.justInCase;f.delay(this.losePatience);this.numSteps=a;this.currentStep=0;Ext.MessageBox.progress(b,c,d);Ext.MessageBox.on("hide",function(){f.cancel();Ext.MessageBox.un("hide",arguments.callee)})}},
incrementProgress:function(a){++this.currentStep>=this.numSteps?(Ext.MessageBox.progressBar.isVisible()&&Ext.MessageBox.hide(),this.currentStep=void 0,Sfdc.isFunction(this.progressFinished)&&this.progressFinished(),this.progressFinished=null):Ext.MessageBox.updateProgress(1*this.currentStep/this.numSteps,a)},setIDECookie:function(a,b){var c=Ext.JSON.decode(Ext.util.Cookies.get("ideCookie"));null===c&&(c={});c[a]=b;Ext.util.Cookies.set("ideCookie",Ext.JSON.encode(c))},getIDECookie:function(a){var b=
Ext.JSON.decode(Ext.util.Cookies.get("ideCookie"));null===b&&(b={});return b[a]},nanoRenderer:function(a,b,c,d,e,f){b.attr='align\x3d"right"';return-1==a?"n/a":Ext.util.Format.number(a/1E6,"0,000.00")},percentRenderer:function(a,b,c,d,e,f){return 0<=a?Ext.util.Format.number(100*a,"0,000.00")+"%":"n/a"},historyMaxStackLength:25,historyBackStack:[],historyForwardStack:[],historyLock:!1,clearHistory:function(){this.historyBackStack=[];this.historyForwardStack=[]},addHistory:function(a){this.historyLock||
(this.historyBackStack.push(a),this.historyBackStack.length>this.historyMaxStackLength&&(this.historyBackStack=this.historyBackStack.splice(this.historyBackStack.length-this.historyMaxStackLength)),this.historyForwardStack=[],Ext.getCmp("backButton").setDisabled(!1),Ext.getCmp("forwardButton").setDisabled(!0))},back:function(){this.historyLock=!0;if(0<this.historyBackStack.length){var a=this.historyBackStack.pop();a.back();this.historyForwardStack.push(a)}0===this.historyBackStack.length&&Ext.getCmp("backButton").setDisabled(!0);
Ext.getCmp("forwardButton").setDisabled(!1);this.historyLock=!1},forward:function(){this.historyLock=!0;if(0<this.historyForwardStack.length){var a=this.historyForwardStack.pop();a.forward();this.historyBackStack.push(a)}0===this.historyForwardStack.length&&Ext.getCmp("forwardButton").setDisabled(!0);Ext.getCmp("backButton").setDisabled(!1);this.historyLock=!1},maxExecuteAnonymousLength:32E3,lastExecuteAnon:"",executeAnonymous:function(a,b,c,d){if(!apex.ide.IDE.authorApex)return Sfdc.isFunction(d)&&
d(LC.getLabel("ErrorMessages","noPermission")),null;if(a.length>apex.ide.IDE.maxExecuteAnonymousLength){var e="The maximum execute anonymous code length is "+apex.ide.IDE.maxExecuteAnonymousLength+". Your length is "+a.length+".";Ext.Msg.alert("Execute anonymous error",e);Sfdc.isFunction(d)&&d(e);return null}SfdcDevConsole.Session.initialize();Ext.MessageBox.progress("Executing","Sending Request","Sending...");SfdcDevConsole.ToolingAPI.executeAnonymous(a,{continuation:function(e,g){Ext.MessageBox.updateProgress(0.5,
"Unpacking results");apex.ide.IDE.lastExecuteAnon=a;if(e.success)Ext.MessageBox.updateProgress(0.75,"Processing traces"),apex.ide.IDE.fireEvent("exec",e),Ext.MessageBox.updateProgress(1,"Processed traces"),Ext.MessageBox.hide(),apex.csi.LogBrowser.selectId=e.traces,b&&(apex.csi.LogBrowser.openNext=!0),Sfdc.isFunction(c)&&c(e);else{Ext.MessageBox.updateProgress(1,"Display Error");Ext.MessageBox.hide();var h=(e.compileProblem||e.exceptionMessage)+"",h=escapeHTML(h);Sfdc.isFunction(d)?d(h,escapeHTML(e.line),
escapeHTML(e.column)):Ext.Msg.alert("Execute Anonymous Error",h)}},failure:function(a,b){Ext.MessageBox.updateProgress(1,"Execution failed");(new Ext.util.DelayedTask(function(){Ext.MessageBox.hide()})).delay(5E3);if(Sfdc.isFunction(d)){var c=Ext.JSON.decode(a,!0),c=null!==c?c[0].message:a;d("Response to EXEC was : "+c+". HTTP CODE["+b.status+"]")}}});SfdcDevConsole.Session.keepAlive()},closeAll:function(a){var b=Ext.getCmp("editors"),c=0,d={};b.items.each(function(a){a.dirty&&(c++,d[a.id]={Id:a.containerMemberId})});
var e=function(){b.items.each(function(a){a.suspendEvents(!1)});b.removeAll();SfdcDevConsole.Events.EventDispatcher.fire("problems:clear");Sfdc.isFunction(a)&&a()};0<c?Ext.Msg.confirm("Close All without saving?","There are "+c+" unsaved files. Are you sure you want to close without saving?",function(a){"yes"===a&&(e(),apex.ide.Container.deleteContainerMembersNoCompile(apex.ide.IDE.containerId,d))},this):e()},clearList:function(){apex.ide.IDE.showUpdatesFromTime=(new Date).getTime();apex.ide.IDE.fireEvent("clear")},
addNewRecordsToStore:function(a,b){if(b&&0<b.length){for(var c=!a.snapshot||0===a.snapshot.getCount(),d=0;d<b.length;d++){var e=b[d];this.haveIds.push(e.id);!c&&!a.getById(e.id)&&(a.add(e),a.sort())}c&&(a.loadData(b),a.fireEvent("load",this))}},sendGack:function(a,b){Sfdc.logServer("WINDOWERROR",Sfdc.Logging.formatError({msg:a}),b?b:Sfdc.Logging.LogLevel.INFO);if(apex.ide.IDE.isDev)throw a;Sfdc.error(a)},sendPerformanceMetrics:function(a,b,c,d,e){try{var f=SfdcDevConsole.lastAjaxRequest,g=f&&f.action.replace(/&_dc=(\d)*/,
"");Sfdc.logServer("performance",{useragent:window.navigator.userAgent,page:"DeveloperConsole",action:a,time:b,lastAjax:g,timeOfLastAjax:f&&f.time,openEntities:c,entities:d,averageSize:e?Math.round(e):0})}catch(h){}},gacksSentToServer:0,gackRelay:function(a,b,c){if(5>apex.ide.IDE.gacksSentToServer){apex.ide.IDE.gacksSentToServer++;b.browserTab=Ext.getCmp("bottomPanel").getActiveTab().title;a=Ext.getCmp("editors");if(c=a.getActiveTab())b.editorTabTitle=c.title,b.editorTabExtent=c.extent,b.rendered=
c.rendered,b.loading=c.loading,b.opened=c.opened,c instanceof apex.editor.CompileableSourceEditor&&(b.compiled=c.compiled,b.compiling=c.compiling);if(0<a.items.length){c=[];for(var d=0;d<a.items.length;d++)c[d]=a.items.items[d].name;b.editorsOnTabPanel=c.join(" | ")}b.lastAjaxAction=SfdcDevConsole.lastAjaxRequest.action;b.lastServerTrace=SfdcDevConsole.lastAjaxRequest.serverTrace;return!1}Sfdc.Logging.stopWindowErrorListener();return!0},haveIds:[],apiUrl:SfdcDevConsole.ToolingAPI.URLs.api,sobjectUrl:SfdcDevConsole.ToolingAPI.URLs.sobject,
queryUrl:SfdcDevConsole.ToolingAPI.URLs.query,CompileDelayTime:3E3,NextEarliestCompileTime:0,getOpenTabsInfo:function(){for(var a=Ext.getCmp("editors"),b="",c=0;c<a.items.length;c++){var d=a.items.get(c),b=b+(d.xtype+":"+d.size);c<a.items.length-1&&(b+=",")}return b}},function(){function a(){var a=document.createElement("div");document.body.appendChild(a);var f={width:"100%",height:"40%",marker:"devconsole$",afterInit:function(a){SfdcDevConsole.Events.EventDispatcher.fire("commandLine:init",[a])},
actions:{find:{find:function(a,b){for(var d=c.split("\n"),e=0;e<d.length;e++)0<=d[e].indexOf(b)&&a.output(d[e])},run:function(a,d){if(!b)return a.output("No log found this session, try to execute anonymous"),!0;if(c)return this.find(a,d),!0;Ext.Ajax.request({url:"/servlet/servlet.FileDownload?file\x3d"+b,headers:{Authorization:"OAuth "+Ext.util.Cookies.get("sid"),Accept:"application/json"},scope:this,success:function(b,e){c=b.responseText;this.find(a,d);a.finished()},failure:function(b,c){a.output("HTTP Error",
"Response from server was "+b.status);a.finished()}});return!1},help:"Find information in the last executed log through the command line"},exec:{execAnon:function(a,d){apex.ide.IDE.executeAnonymous(d,!1,function(d){a.output("Success!");1<=d.traces.length&&(a.output("Generated log "+d.traces[0].id+" of size "+d.traces[0].size),b=d.traces[0].id,c=null);a.finished()},function(b){a.output("Error: "+b);a.finished()})},options:{o:{description:"Open the execute anonymous window",run:function(a,b){a.output("Opening execute anonymous window");
apex.execanon.ExecuteAnonymous.open();a.hide();return!1}},r:{description:"Run the saved execute anonymous code",run:function(a,b,c){c.execAnon(a,apex.execanon.ExecuteAnonymous.get());return!1}}},run:function(a,b){if(0<b.length)return this.execAnon(a,b),!1;a.output("No script entered");return!0},help:"Execute Anonymous: Run apex as anonymous. Note that this will not override your code in the Execute Anonymous Window."},set:{help:'Set a preference for the Developer Console. Use "help set" to see a list of preferences.',
optionRan:!1,options:{f:{description:"Toggle the command line between maximized and unmaximized",run:function(a,b,c){a.getConfig().fullscreen?a.setFullScreen(!1):a.setFullScreen(!0);c.optionRan=!0}}},run:function(a,b){a.output(this.help)}}}};if(apex.ide.IDE.consoleConfig){var g=apex.ide.IDE.consoleConfig;g.fontColor&&(f.fontColor=g.fontColor);g.backgroundColor&&(f.backgroundColor=g.backgroundColor);g.fullscreen&&(f.fullscreen=g.fullscreen)}d.console=new Console(a,f);d.console.focus();SfdcDevConsole.CommandLine.instance=
d.console}SfdcDevConsole.Events.EventDispatcher.on("session:expired",function(){Ext.MessageBox.show({icon:Ext.MessageBox.WARNING,title:LC.getLabel("DeveloperConsole","ResumeTitle"),msg:LC.getLabel("DeveloperConsole","ResumeIdle")+" "+LC.getLabel("DeveloperConsole","ResumeSessionInfo"),width:400,buttons:Ext.MessageBox.OKCANCEL,buttonText:{ok:LC.getLabel("DeveloperConsole","ResumeSession")},fn:function(a,b){"ok"===a&&SfdcDevConsole.Session.initialize()}})});this.addEvents({workspaceLoaded:!0,perspectiveLoaded:!0,
exec:!0,clear:!0,buildingWorkspace:!0});Sfdc.ns("SfdcDevConsole.CommandLine");SfdcDevConsole.Events.EventDispatcher.register("commandLine:init");var b=this.console=SfdcDevConsole.CommandLine.instance=null,c=null,d=this;apex.ide.IDE.on("workspaceLoaded",function(b){b&&b.consoleConfig&&(apex.ide.IDE.consoleConfig=b.consoleConfig);b&&b.consoleShown&&a()});Ext.onReady(function(){new Ext.util.KeyMap(Ext.getBody(),[{ctrl:!0,shift:!0,alt:!1,key:"l",fn:function(){var b=SfdcDevConsole.CommandLine.instance;
b?d.console.isHidden()?(b.show(),b.focus()):b.hide():a()},defaultEventAction:"stopEvent"}])})});
Ext.onReady(function(){Ext.Ajax.defaultHeaders={Accept:"application/json"};SfdcDevConsole.Events.EventDispatcher.on("problems:selected",function(a,b){apex.ide.Viewer.open({id:ApiUtils.to18CharId(SfdcDevConsole.Extents.getTableEnumOrId(b)),Name:b.name,xtype:SfdcDevConsole.Extents[b.extent].xtype},function(a){a.coverageCycle&&a.coverageCycle.setActiveItem(a.coverageCycle.menu.items.items[0]);a=a.cmEditor;var d=b.line;a&&(a.clearHighlights(),a.highlightLine(d,"CodeMirror-line-highlight-error"),a.scrollToLine(d))})})});
Ext.define("apex.ide.Browser",{extend:"Ext.Panel"});
Ext.define("apex.ide.panelContainer",{extend:"Ext.Panel",alias:"widget.panelContainer",initComponent:function(){this.callParent();this.on("afterrender",function(a){for(var b=a.visiblePanels=0;b<a.items.length;b++)apex.csi.LogViewer.getChildPanel(a,b).hidden||a.visiblePanels++;a.isVisible()&&a.ownerCt.visiblePanels++});this.on("resize",function(a){if(apex.csi.LogViewer.findEditorPanel(a,"logviewer").isLoaded){apex.ide.ViewerPerspectiveDefinition.handlePanelResize(a);apex.ide.ViewerPerspectiveDefinition.updateContainerSizePercentage(a);
for(var b=0;b<a.items.items.length;b++){var c=apex.csi.LogViewer.getChildPanel(a,b);c&&(!c.hidden&&apex.ide.CsiPerspectiveDefinition.isBodyPanel(c))&&(a instanceof apex.ide.vboxContainer?c.setHeight(Math.round(a.getHeight()/a.visiblePanels)):c.setWidth(Math.round(a.getWidth()/a.visiblePanels)))}}})}});Ext.define("apex.ide.vboxContainer",{extend:"apex.ide.panelContainer",alias:"widget.vboxContainer",layout:{type:"vbox",align:"stretch"}});
Ext.define("apex.ide.hboxContainer",{extend:"apex.ide.panelContainer",alias:"widget.hboxContainer",layout:{type:"hbox",align:"stretch"}});
Ext.define("apex.ide.QueryGrid",{extend:"Ext.grid.Panel",alias:"widget.querygrid",statics:{describeResults:{}},openUrl:function(a,b,c){function d(){if(apex.ide.QueryGrid.describeResults[b].urls&&apex.ide.QueryGrid.describeResults[b].urls[a]){var d=apex.ide.QueryGrid.describeResults[b].urls[a];c&&(d=d.replace("{ID}",c));window.open(d)}else Ext.MessageBox.alert("Error","Entity "+b+" does not support requested operation")}void 0===apex.ide.QueryGrid.describeResults[b]?SfdcDevConsole.ToolingAPI.sobject(b,
{tooling:apex.ide.IDE.isDev&&Ext.getCmp("useToolingAPI").getValue(),describe:!0,async:!1,continuation:function(a,c){apex.ide.QueryGrid.describeResults[b]=a;d()},failureMessage:"Unable to access URL information for entity "+b}):d()},validateAction:function(a,b,c){var d=this.queryMetadata&&this.queryMetadata.idSelected||this.searchMetadata&&0<this.searchMetadata.length&&this.searchMetadata[0].Id;this.queryMetadata&&this.queryMetadata.groupBy?Ext.MessageBox.alert("Operation cannot be performed","Cannot "+
a+" on group by queries"):d?Sfdc.isFunction(b)&&b.call(c):Ext.MessageBox.alert("Operation cannot be performed","Cannot "+a+" if the ID column is not included in the target list")},initComponent:function(){var a=this.bbar&&this.bbar.items?this.bbar.items:[];a.push({xtype:"tbfill"},{xtype:"label",text:"Access in Salesforce:"},{text:"Create New",xtype:"button",handler:function(a){a.queryGrid.openUrl("uiNewRecord",a.queryGrid.entityName||a.queryGrid.queryMetadata.entityName)},listeners:{afterRender:function(a){this.queryGrid=
this.ownerCt.ownerCt;this.queryGrid.newPageButton=this}}},{text:"Open Detail Page",xtype:"button",handler:function(a){this.queryGrid.validateAction("open detail page",function(){for(var a=this.queryGrid.getSelectionModel().getSelection(),b=this.queryGrid.entityName||this.queryGrid.queryMetadata.entityName,e=0;e<a.length;e++)this.queryGrid.openUrl("uiDetailTemplate",b,a[e].data.Id)},this)},listeners:{afterRender:function(a){this.queryGrid=this.ownerCt.ownerCt;this.queryGrid.openPageButton=this}}},
{text:"Edit Page",xtype:"button",handler:function(a){this.queryGrid.validateAction("open edit page",function(){for(var a=this.ownerCt.ownerCt.getSelectionModel().getSelection(),b=this.queryGrid.entityName||this.queryGrid.queryMetadata.entityName,e=0;e<a.length;e++)this.queryGrid.openUrl("uiEditTemplate",b,a[e].data.Id)},this)},listeners:{afterRender:function(a){this.queryGrid=this.ownerCt.ownerCt;this.queryGrid.editPageButton=this}}});!this.bbar&&0<a.length&&(this.bbar={items:a});this.callParent()}});
SfdcDevConsole.Events.EventDispatcher.register("perspective:create");SfdcDevConsole.Events.EventDispatcher.register("perspective:open");SfdcDevConsole.Events.EventDispatcher.register("perspective:save");SfdcDevConsole.Events.EventDispatcher.register("perspective:deletePerspective");SfdcDevConsole.Events.EventDispatcher.register("perspective:update");SfdcDevConsole.Events.EventDispatcher.register("perspective:setDefault");
Ext.define("apex.ide.PerspectiveDefinition",{alias:"widget.perspectiveDefinition",constructor:function(a){this.initConfig(a)},logPanelWindow:Ext.create("Ext.window.Window",{title:"Select Panels",id:"logPanelWindow",closeAction:"hide",width:180,layout:{type:"vbox",pack:"start",align:"stretch"},listeners:{show:function(){for(var a=0;a<this.items.length;a++)this.items.get(a).hide(),this.items.get(a).show()}},setCheckbox:function(a,c){a.suspendEvents(!1);a.setValue(c?c.isVisible():!1);a.resumeEvents();
apex.ide.CsiPerspectiveDefinition.setLastMenuCheckItemDisabled(a.ownerCt)},items:[{boxLabel:"Stack Tree",id:"perspectivePanel0",xtype:"checkbox",listeners:{change:function(a,c,b){b=Ext.getCmp("editors").getActiveTab();apex.ide.CsiPerspectiveDefinition.handlePanelsMenuCheckItemChange(b,a.ownerCt,c,b.stacktreepanel)},afterrender:function(a){Ext.getCmp("logPanelWindow").setCheckbox(a,Ext.getCmp("editors").getActiveTab().stacktreepanel)},show:function(a){Ext.getCmp("logPanelWindow").setCheckbox(a,Ext.getCmp("editors").getActiveTab().stacktreepanel)}}},
{boxLabel:"Execution Stack",id:"perspectivePanel1",xtype:"checkbox",listeners:{change:function(a,c,b){b=Ext.getCmp("editors").getActiveTab();apex.ide.CsiPerspectiveDefinition.handlePanelsMenuCheckItemChange(b,a.ownerCt,c,b.executionStack)},afterrender:function(a){Ext.getCmp("logPanelWindow").setCheckbox(a,Ext.getCmp("editors").getActiveTab().executionStack)},show:function(a){Ext.getCmp("logPanelWindow").setCheckbox(a,Ext.getCmp("editors").getActiveTab().executionStack)}}},{boxLabel:"Execution Log",
id:"perspectivePanel2",xtype:"checkbox",listeners:{change:function(a,c,b){b=Ext.getCmp("editors").getActiveTab();apex.ide.CsiPerspectiveDefinition.handlePanelsMenuCheckItemChange(b,a.ownerCt,c,b.logPanel)},afterrender:function(a){Ext.getCmp("logPanelWindow").setCheckbox(a,Ext.getCmp("editors").getActiveTab().logPanel)},show:function(a){Ext.getCmp("logPanelWindow").setCheckbox(a,Ext.getCmp("editors").getActiveTab().logPanel)}}},{boxLabel:"Source",id:"perspectivePanel3",xtype:"checkbox",listeners:{change:function(a,
c,b){b=Ext.getCmp("editors").getActiveTab();apex.ide.CsiPerspectiveDefinition.handlePanelsMenuCheckItemChange(b,a.ownerCt,c,b.sourcePanel)},afterrender:function(a){Ext.getCmp("logPanelWindow").setCheckbox(a,Ext.getCmp("editors").getActiveTab().sourcePanel)},show:function(a){Ext.getCmp("logPanelWindow").setCheckbox(a,Ext.getCmp("editors").getActiveTab().sourcePanel)}}},{boxLabel:"Source List",id:"perspectivePanel6",xtype:"checkbox",listeners:{change:function(a,c,b){b=Ext.getCmp("editors").getActiveTab();
apex.ide.CsiPerspectiveDefinition.handlePanelsMenuCheckItemChange(b,a.ownerCt,c,b.sourceListPanel)},afterrender:function(a){Ext.getCmp("logPanelWindow").setCheckbox(a,Ext.getCmp("editors").getActiveTab().sourceListPanel)},show:function(a){Ext.getCmp("logPanelWindow").setCheckbox(a,Ext.getCmp("editors").getActiveTab().sourceListPanel)}}},{boxLabel:"Variables",id:"perspectivePanel4",xtype:"checkbox",listeners:{change:function(a,c,b){b=Ext.getCmp("editors").getActiveTab();apex.ide.CsiPerspectiveDefinition.handlePanelsMenuCheckItemChange(b,
a.ownerCt,c,b.variablePanel)},afterrender:function(a){Ext.getCmp("logPanelWindow").setCheckbox(a,Ext.getCmp("editors").getActiveTab().variablePanel)},show:function(a){Ext.getCmp("logPanelWindow").setCheckbox(a,Ext.getCmp("editors").getActiveTab().variablePanel)}}},{boxLabel:"Execution Overview",id:"perspectivePanel5",xtype:"checkbox",listeners:{change:function(a,c,b){b=Ext.getCmp("editors").getActiveTab();apex.ide.CsiPerspectiveDefinition.handlePanelsMenuCheckItemChange(b,a.ownerCt,c,b.executionOverview)},
afterrender:function(a){Ext.getCmp("logPanelWindow").setCheckbox(a,Ext.getCmp("editors").getActiveTab().executionOverview)},show:function(a){Ext.getCmp("logPanelWindow").setCheckbox(a,Ext.getCmp("editors").getActiveTab().executionOverview)}}}]})},function(){SfdcDevConsole.Events.EventDispatcher.on("perspective:open",function(a,c,b){SfdcDevConsole.ToolingAPI.query("SELECT Id, Name, Content FROM IDEPerspective WHERE Name\x3d'"+b+"'",{continuation:function(a,g){if(a.done){var f=a.records[0];try{if(!f&&
c.isPredefinedPerspective(b)){var e=c.getPredefined(b);e&&(f={Name:e.label,Content:e.perspectiveConfig})}apex.ide.IDE.fireEvent("perspectiveLoaded",f,Ext.getCmp("editors").getActiveTab())}catch(h){apex.ide.IDE.sendGack("Exception: "+h+" on perspective: "+Ext.JSON.encode(f)+" on "+this)}}},alertOnFailure:!0,failureMessage:"Could not load perspectives"})});SfdcDevConsole.Events.EventDispatcher.on("perspective:deletePerspective",function(a,c,b,d){c.isPredefinedPerspective(b.label)?Ext.MessageBox.alert("Error",
"You can't delete the default perspective."):SfdcDevConsole.ToolingAPI.DELETE("IDEPerspective",b.id,{success:function(a,b){Sfdc.isFunction(d)&&d()},failureMessage:"Unable to delete perspective "+b.id})});SfdcDevConsole.Events.EventDispatcher.on("perspective:setDefault",function(a,c,b,d){SfdcDevConsole.ToolingAPI.query("SELECT Id, Name, Content FROM IDEPerspective WHERE Name\x3d '"+d+"'",{continuation:function(a,f){if(a.done){var e=a.records[0];if(e)apex.csi.LogViewer.defaultPerspectiveConfig={id:e.Id,
label:d,perspectiveConfig:e.Content};else if(e=c.getPredefined(d))apex.csi.LogViewer.defaultPerspectiveConfig={label:e.label,perspectiveConfig:e.perspectiveConfig};b.getView().refresh()}},alertOnFailure:!0,failureMessage:"Could not set a default perspective"})});SfdcDevConsole.Events.EventDispatcher.on("perspective:create",function(a,c,b,d){a={Name:b,Content:Sfdc.JSON.stringify(d),UserId:SfdcDevConsole.myUserId};SfdcDevConsole.ToolingAPI.create("IDEPerspective",a,{success:function(a,d){var e=Ext.getCmp("editors").getActiveTab();
e&&apex.ide.ViewerPerspectiveDefinition.isValidViewer(e)&&SfdcDevConsole.Events.EventDispatcher.fire("perspective:open",[c,b])},alertOnFailure:!0,failureMessage:"Failed to create "+a.Name+" perspective: "})});SfdcDevConsole.Events.EventDispatcher.on("perspective:update",function(a,c,b,d){c.isPredefinedPerspective(b.Name)?Ext.MessageBox.alert("Error","You can't overwrite a built-in perspective. To copy your changes to a new perspective, click Save As and enter a new perspective name."):(a=Ext.JSON.encode(d),
a={Id:b.Id,Name:b.Name,Content:a},SfdcDevConsole.ToolingAPI.save("IDEPerspective",a,{success:function(a,d){var e=Ext.getCmp("editors").getActiveTab();e.isPerspectiveDirty=!1;e&&apex.ide.ViewerPerspectiveDefinition.isValidViewer(e)&&SfdcDevConsole.Events.EventDispatcher.fire("perspective:open",[c,b.Name]);b.Name===apex.csi.LogViewer.defaultPerspectiveConfig.label&&(apex.csi.LogViewer.defaultPerspectiveConfig=e.currentPerspectiveConfig)},alertOnFailure:!0,failureMessage:"Failed to update "+a.Name+" perspective: "}))});
SfdcDevConsole.Events.EventDispatcher.on("perspective:save",function(a,c,b){c.isPredefinedPerspective(b.label)?Ext.MessageBox.alert("Error","You can't overwrite a built-in perspective. To copy your changes to a new perspective, click Save As and enter a new perspective name."):SfdcDevConsole.ToolingAPI.query("SELECT Id, Name, Content FROM IDEPerspective WHERE Name\x3d '"+b.label+"'",{continuation:function(a,g){if(a.done){var f=a.records[0];f?Ext.Msg.confirm("Confirm","The perspective you are trying to save already exists, do you want to replace it?",
function(a,d){"yes"==a&&SfdcDevConsole.Events.EventDispatcher.fire("perspective:update",[c,f,b.perspectiveConfig])}):SfdcDevConsole.Events.EventDispatcher.fire("perspective:create",[c,b.label,b.perspectiveConfig])}},alertOnFailure:!0,failureMessage:"Could not save perspective"})})});
Ext.define("apex.ide.ViewerPerspectiveDefinition",{extend:"apex.ide.PerspectiveDefinition",constructor:function(a){this.callParent(arguments)},inheritableStatics:{panelContainer:["vboxContainer","hboxContainer"],isPanelContainer:function(a){return Ext.Array.contains(this.panelContainer,a.xtype)},isValidViewer:function(a){return a instanceof apex.csi.LogViewer},getPerspectiveConfigMap:function(a){var c=new Ext.util.HashMap;this.generatePerspectiveConfigMap(a.items,c);return c},generatePerspectiveConfigMap:function(a,
c){if(void 0!==a&&void 0!==a.items)for(var b=0;b<a.items.length;b++)void 0!==a.items[b].el&&this.isValidPanelOrContainer(a.items[b])&&(c.add(a.items[b].xtype,a.items[b]),void 0!==a.items[b].items&&this.generatePerspectiveConfigMap(a.items[b].items,c))},applyPerspective:function(a,c,b){if(c)for(var d,g=0;g<c.length;g++)if(d=c[g],Sfdc.isDefAndNotNull(d)&&this.isValidPanelOrContainer(d)){var f=this.perspectiveConfigMap.get(d.xtype);if(f&&this.isBodyPanel(f)){null===b.getChildByElement(f.el)&&b.add(f);
d.hidden&&f.isVisible()?a.hidePanel(f):!d.hidden&&f.isHidden()&&a.showPanel(f);var e=f.checkItem;Sfdc.isDefAndNotNull(e)&&e.checked&&(e.suspendEvents(),e.setValue(f.isVisible()),e.resumeEvents());f.widthPercentage=d.widthPercentage;f.heightPercentage=d.heightPercentage}this.applyPerspective(a,d.items,b.items.items[g])}},perspectiveConfigMap:null,generateConfig:function(a){if(void 0!==a&&void 0!==a.items)for(var c=[],b=0;b<a.items.length;b++)void 0!==a.items[b].el&&this.isValidPanelOrContainer(a.items[b])&&
(c[b]={xtype:a.items[b].xtype,hidden:a.items[b].hidden},a.items[b].hidden?(c[b].width=0,c[b].height=0):(c[b].widthPercentage=(a.items[b].width/a.items[b].ownerCt.el.getWidth()).toFixed(4),c[b].heightPercentage=(a.items[b].height/a.items[b].ownerCt.el.getHeight()).toFixed(4)),a.items[b].resizable&&(c[b].resizable=a.items[b].resizable),a.items[b].resizeHandles&&(c[b].resizeHandles=a.items[b].resizeHandles),void 0!==a.items[b].items&&(c[b].items=this.generateConfig(a.items[b].items)));return c},resizePanels:function(a){if(void 0!==
a&&void 0!==a.items)for(var c=0;c<a.items.length;c++)if(panel=a.items[c],void 0!==panel.el&&this.isValidPanelOrContainer(panel)){try{panel.suspendEvents(),void 0!==panel.widthPercentage&&panel.setWidth(Math.round(panel.ownerCt.el.getWidth()*panel.widthPercentage)),void 0!==panel.heightPercentage&&panel.setHeight(Math.round(panel.ownerCt.el.getHeight()*panel.heightPercentage))}finally{panel.resumeEvents()}void 0!==panel.items&&this.resizePanels(panel.items)}},updateContainerSizePercentage:function(a){this.isPanelContainer(a)&&
(a.heightPercentage=a.getHeight()/a.ownerCt.getHeight(),a.widthPercentage=a.getWidth()/a.ownerCt.getWidth())},handlePanelResize:function(a){a=a.ownerCt;var c=0,b=0;for(i=0;i<a.items.length;i++)if(panel=apex.csi.LogViewer.getChildPanel(a,i),panel.isVisible())if(b+=1,"vbox"===a.layout.type){if(b===a.visiblePanels){panel.suspendEvents();panel.setHeight(Math.round(a.getHeight()-c));panel.resumeEvents();break}c+=panel.getHeight()}else if("hbox"===a.layout.type){if(b===a.visiblePanels){panel.suspendEvents();
panel.setWidth(Math.round(a.getWidth()-c));panel.resumeEvents();break}c+=panel.getWidth()}},saveCurrentPerspective:function(){var a=Ext.getCmp("editors").getActiveTab(),c=this;if(a.isPerspectiveUnsaved)Ext.Msg.prompt("Save Perspective","Please enter a name for this perspective.",function(b,d){if("ok"==b){var e=c.generateConfig(a.items);SfdcDevConsole.Events.EventDispatcher.fire("perspective:save",[c,{label:d,perspectiveConfig:e}]);a.isPerspectiveUnsaved=!1}});else{var b={Id:a.currentPerspectiveConfig.id,
Name:a.currentPerspectiveConfig.label},d=this.generateConfig(a.items);SfdcDevConsole.Events.EventDispatcher.fire("perspective:update",[c,b,d])}},setLastMenuCheckItemDisabled:function(a){var c,b,d=0;a.items.each(function(a){a.checked&&(c=a,d+=1);a.isDisabled()&&(b=a)});1===d?c.setDisabled(!0):2===d&&b&&b.setDisabled(!1)},handlePanelsMenuCheckItemChange:function(a,c,b,d){this.isPredefinedPerspective(a.currentPerspectiveConfig.label)&&(a.isPerspectiveUnsaved=!0);a.isPerspectiveDirty=!0;b?a.showPanel(d):
a.hidePanel(d);apex.ide.CsiPerspectiveDefinition.setLastMenuCheckItemDisabled(c)},getPerspectiveList:function(){var a=this;SfdcDevConsole.ToolingAPI.query("SELECT Id, Name FROM IDEPerspective WHERE UserId\x3d'"+SfdcDevConsole.myUserId+"'",{continuation:function(c,b){if(c.done){for(var d=[],g=0;g<c.records.length;g++)d.push({id:c.records[g].Id,name:c.records[g].Name});for(var f in a.predefinedPerspectives)a.predefinedPerspectives.hasOwnProperty(f)&&d.push({name:a.predefinedPerspectives[f].label});
Ext.StoreMgr.lookup("perspectives").loadData(d);Ext.StoreMgr.lookup("perspectivesList").loadData(d)}},alertOnFailure:!0,failureMessage:"Could not list perspectives"})},getPredefined:function(a){for(var c in this.predefinedPerspectives)if(this.predefinedPerspectives.hasOwnProperty(c)){var b=this.predefinedPerspectives[c];if(b.label===a)return b}return null}}});
Ext.namespace("apex.plugins");apex.plugins.GridCellPopup=function(){return{init:function(b){b.on("celldblclick",function(a,b,c,d,e,f,g,h){a=a.ownerCt.getLayout().owner.columns;Ext.Msg.show({title:a[c].text,value:d.data[a[c].dataIndex],buttons:Ext.Msg.OK,minWidth:500,multiline:!0})})}}};
Ext.namespace("apex.plugins");apex.plugins.GridColumnResizer=function(g){return{init:function(a){var b=a.columns[g],h=b.dataIndex;a.on("beforerender",function(a){a.getStore().on("datachanged",function(){for(var c=b.width,e=a.getStore(),d=0;d<e.getCount();d++){var f=8*e.getAt(d).get(h).length;c<f&&(c=f)}b.setWidth(c);b.resized=!0},this)})}}};
(function(){function r(b,a){g.hide();l.setDisabled(!0);var d,m=[];d=SfdcDevConsole.Core.Search.SOSLUtil.matcher(a).match();var k;try{k=RegExp(d,"i")}catch(r){g.show();n.loadData([],!1);e.setLoading(!1);return}var s=function(b){var a=k.exec(b);return null===a?null:{pos:b.indexOf(a[0]),len:a[0].length}};if(Sfdc.isDefAndNotNull(b.searchRecords))for(d=0;d<b.searchRecords.length;d++){var c=b.searchRecords[d],f;if(null===s)f=new apex.ide.SearchInFilesResult({lineKey:c.Id+":1",id:c.Id,type:c.attributes.type,
line:1,name:c.Name,start:0,end:0,namespace:c.NamespacePrefix,snippet:""}),m.push(f);else{var p;c.Body?p=c.Body:c.Markup&&(p=c.Markup);var q=p.split("\n"),h;for(h=0;h<q.length;h++)f=s(q[h]),null!==f&&(f=new apex.ide.SearchInFilesResult({lineKey:c.Id+":"+h,id:c.Id,type:c.attributes.type,line:h+1,name:c.Name,start:f.pos,end:f.pos+f.len,namespace:c.NamespacePrefix,snippet:q[h]}),m.push(f))}}0===m.length&&g.show();n.loadData(m,!1);e.setLoading(!1)}var e,n,l,g,k;Ext.define("apex.ide.SearchInFiles",{singleton:!0,
searchInFiles:function(){e||(Ext.define("apex.ide.form.SearchField",{extend:"Ext.form.field.Trigger",alias:"widget.searchfield",triggerCls:"x-form-search-trigger",initComponent:function(){this.callParent(arguments);this.on("specialkey",function(b,a){if(a.getKey()===a.ENTER)this.onTriggerClick();a.getKey()===a.ESC&&e.hide()},this)},onTriggerClick:function(){e.setLoading(!0);g.hide();var b=this.getValue(),a="\x3ccode\x3e"+Sfdc.String.escapeToHtml(b.trim())+"\x3c/code\x3e";SfdcDevConsole.ToolingAPI.search("FIND {"+
b+"} IN ALL FIELDS RETURNING ApexClass(id, name, namespaceprefix, body), ApexTrigger(id, name, namespaceprefix, body), ApexPage(id, name, namespaceprefix, markup), ApexComponent(id, name, namespaceprefix, markup)",{continuation:function(a,e){r(a,b)},failureMessage:"Search for '"+a+"' returned error code: ",alertOnFailure:!0,gackOnFailure:!1,alertHandler:function(){this.focus()}.bind(this),additionalFailureHandler:function(){e.setLoading(!1)}})}}),Ext.define("apex.ide.SearchInFilesResult",{idProperty:"lineKey",
extend:"Ext.data.Model",fields:["lineKey","id",{name:"line",type:"int"},"type","name","namespace","snippet","pos","start","end"]}),g=Ext.create("Ext.form.Label",{xtype:"label",text:LC.getLabel("SearchInFiles","NoResult"),hidden:!0}),l=Ext.create("Ext.Button",{text:LC.getLabel("SearchInFiles","OpenButton"),disabled:!0,listeners:{click:function(b){b=Ext.getCmp("searchInFilesResultsGrid").getSelectionModel().getSelection()[0];var a=b.data.id,d=SfdcDevConsole.Extents.getExtentFromId(a);Ext.getCmp("searchInFilesWindow")._openRecord(a,
b,d)}}}),k=Ext.create("apex.ide.form.SearchField",{width:600,fieldLabel:LC.getLabel("SearchInFiles","SearchPrompt"),labelWidth:50,id:"searchFieldBar",value:""}),n=Ext.create("Ext.data.Store",{storeId:"searchInFilesGrid",type:"memory",model:"apex.ide.SearchInFilesResult"}),e=Ext.create("apex.ide.window.pinnable",{_openRecord:function(b,a,d){apex.ide.Viewer.open({id:b,Name:a.data.name,xtype:d.xtype},function(b){b.cmEditor.codeEditor.setSelection({line:a.data.line-1,ch:a.data.start},{line:a.data.line-
1,ch:a.data.end})});this._closeIfNotPinned()},title:LC.getLabel("SearchInFiles","Title"),id:"searchInFilesWindow",width:650,height:300,closeAction:"hide",layout:"fit",tbar:["-\x3e",k],items:[{xtype:"gridpanel",id:"searchInFilesResultsGrid",columns:[{header:"Namespace",dataIndex:"namespace",width:100},{header:"Name",dataIndex:"name",width:100},{header:"Type",dataIndex:"type",width:100},{header:"Line",dataIndex:"line",width:50},{header:"Text",dataIndex:"snippet",flex:1,renderer:function(b){return"\x3ccode\x3e"+
Sfdc.String.escapeToHtml(b.trim())+"\x3c/code\x3e"}}],selModel:{mode:"SINGLE"},store:n,listeners:{itemclick:function(){l.setDisabled(!1)},itemdblclick:function(b,a,d,e,g,k){b=a.data.id;d=SfdcDevConsole.Extents.getExtentFromId(b);Ext.getCmp("searchInFilesWindow")._openRecord(b,a,d)}}}],bbar:["-\x3e",g,l]}));e.show();k.focus(!0,100);Sfdc.Test&&(apex.ide.SearchInFiles.searchWindowStatusText=g)}})})();
Sfdc.ns("SfdcDevConsole.Menu");Ext.override(Ext.menu.Menu,{onMouseLeave:function(a){var b=!1;this.items.each(function(a){a.menu&&a.menu.isVisible()&&(b=!0)});b||(this.deactivateActiveItem(),this.disabled||this.fireEvent("mouseleave",this,a))}});
SfdcDevConsole.Menu={menuEntryWithShortcut:function(a,b,c,f,d,e,g){Sfdc.isObject(a)&&(b=a.ctrl,c=a.shift,f=a.alt,d=a.character,e=a.text,g=a.perm,a=a.entry);if(!e)try{e=a.substring(0,1).toUpperCase()+a.substring(1).toLowerCase()}catch(l){e=a}apex.ide.ShortcutRegistry.add({name:e,key:d,ctrl:b,alt:f,shift:c,perm:g});a='\x3cdiv class\x3d"menuEntryLeft"\x3e'.concat(a).concat('\x3c/div\x3e\x3cdiv class\x3d"menuEntryRight"\x3e');b&&(a=a.concat(apex.ide.ShortcutRegistry.CTRL));c&&(a=a.concat(apex.ide.ShortcutRegistry.SHIFT));
f&&(a=a.concat(apex.ide.ShortcutRegistry.ALT));return a.concat(d).concat("\x3c/div\x3e")},add:function(a,b,c,f){var d=SfdcDevConsole.Menu.toolbar.child('*[text\x3d"'+a+'"]'),e;if(d){if(e=d.menu,c&&c.index?e.insert(c.index,b):e.add(b),Sfdc.isFunction(f))e.on("show",f)}else c||(c={}),c.width||(c.width=200),c.items=b,Sfdc.isFunction(f)&&(c.listeners={show:f}),e=Ext.create("Ext.menu.Menu",c),d=SfdcDevConsole.Menu.toolbar.insert(SfdcDevConsole.Menu.toolbar.items.length-3,{text:a,menu:e});return d}};
SfdcDevConsole.Menu.editorMenu=Ext.create("Ext.menu.Menu",{id:"editorMenu",width:250,style:{overflow:"visible"},listeners:{show:function(a,b){SfdcDevConsole.Menu.toolbar.refresh()}},items:[{text:"New",id:"newMenuEntry",hideOnClick:!1,menu:{maxWidth:300,items:[{id:"newDataPipelineButton",text:LC.getLabel("DeveloperConsole","DataPipeline"),handler:function(){SfdcDevConsole.Extents.DataPipeline.create()}},{id:"newApexClassButton",text:LC.getLabel("DeveloperConsole","ApexClass"),handler:function(){SfdcDevConsole.Extents.ApexClass.create()}},
{text:LC.getLabel("DeveloperConsole","ApexTrigger"),id:"apexTriggerMenuEntry",handler:function(){SfdcDevConsole.Extents.ApexTrigger.create()}},{id:"newVFpageButton",text:LC.getLabel("DeveloperConsole","VisualforcePage"),handler:function(){SfdcDevConsole.Extents.ApexPage.create()}},{id:"newVFcomponentButton",text:LC.getLabel("DeveloperConsole","VisualforceComponent"),handler:function(){SfdcDevConsole.Extents.ApexComponent.create()}},{id:"newStaticResourceButton",text:LC.getLabel("DeveloperConsole",
"StaticResource"),handler:function(){SfdcDevConsole.Extents.StaticResource.create()}},{id:"newAuraAppButton",text:LC.getLabel("AuraUI","Application"),handler:function(){SfdcDevConsole.Aura.createApplication()}},{id:"newAuraCmpButton",text:LC.getLabel("AuraUI","Component"),handler:function(){SfdcDevConsole.Aura.createComponent()}},{id:"newAuraIntButton",text:LC.getLabel("AuraUI","Interface"),handler:function(){SfdcDevConsole.Aura.createInterface()}},{id:"newAuraEventButton",text:LC.getLabel("AuraUI",
"Event"),handler:function(){SfdcDevConsole.Aura.createEvent()}},{id:"newAuraTokensButton",text:LC.getLabel("AuraUI","Tokens"),handler:function(){SfdcDevConsole.Aura.createTokens()}}]}},{text:SfdcDevConsole.Menu.menuEntryWithShortcut("Open",!0,!1,!1,"O"),id:"openEntry",handler:function(){SfdcDevConsole.Repository.open()}},{id:"openAuraButton",text:SfdcDevConsole.Menu.menuEntryWithShortcut(LC.getLabel("AuraUI","OpenAuraButton"),!0,!0,!1,"A",LC.getLabel("AuraUI","OpenAuraButton"),"hasAura"),listeners:{click:function(a,
b){SfdcDevConsole.Aura.OpenWindow.show()}}},{id:"openLogButton",tooltip:LC.getLabel("Tooltips","Logs"),text:SfdcDevConsole.Menu.menuEntryWithShortcut(LC.getLabel("DevConsoleMenuItem","OpenLog"),!0,!1,!1,"G"),listeners:{afterrender:function(a){a.logBrowser=Ext.getCmp("traceGrid");a.logBrowser.openButton=a},click:function(a,b){apex.csi.LogBrowser.openLog()}}},{id:"openRawLogButton",text:SfdcDevConsole.Menu.menuEntryWithShortcut(LC.getLabel("DevConsoleMenuItem","OpenRawLog"),!0,!0,!1,"G"),tooltip:LC.getLabel("Tooltips",
"Logs"),listeners:{afterrender:function(a){a.logBrowser=Ext.getCmp("traceGrid");a.logBrowser.openRawButton=a},click:function(a,b){apex.csi.LogBrowser.openLog("rawlogviewer")}}},{id:"downloadLogButton",tooltip:LC.getLabel("Tooltips","Logs"),text:SfdcDevConsole.Menu.menuEntryWithShortcut(LC.getLabel("DevConsoleMenuItem","DownloadLog"),!0,!1,!0,"G"),listeners:{click:function(a,b){var c=Ext.getCmp("editors").getActiveTab();c instanceof apex.csi.BaseLogViewer&&c.downloadLog()}}},{text:SfdcDevConsole.Menu.menuEntryWithShortcut(LC.getLabel("DeveloperConsole",
"SaveButton"),!0,!1,!1,"S",LC.getLabel("Shortcuts","Save")),id:"newSaveButton",tooltip:LC.getLabel("Tooltips","Save"),disabled:!0,handler:function(){Ext.getCmp("editors").getActiveTab().saveEditor(Ext.getCmp("editors").getActiveTab())}},{text:SfdcDevConsole.Menu.menuEntryWithShortcut(LC.getLabel("DeveloperConsole","SaveAllButton"),!0,!0,!1,"S"),disabled:!0,tooltip:LC.getLabel("Tooltips","SaveAll"),id:"saveAllButton",handler:function(){apex.ide.IDE.saveAll()}},{text:SfdcDevConsole.Menu.menuEntryWithShortcut(LC.getLabel("DeveloperConsole",
"DeleteButton"),!0,!1,!1,"DELETE"),id:"metatypeDeleteButton",tooltip:LC.getLabel("Tooltips","Delete"),enabled:!1,handler:function(){apex.ide.IDE.deleteEditor()}},{id:"closeButton",text:SfdcDevConsole.Menu.menuEntryWithShortcut(LC.getLabel("DeveloperConsole","CloseButton"),!0,!1,!1,"/"),tooltip:LC.getLabel("Tooltips","Close"),handler:function(){Ext.getCmp("editors").getActiveTab().close()}},{text:SfdcDevConsole.Menu.menuEntryWithShortcut(LC.getLabel("DeveloperConsole","CloseAllButton"),!0,!1,!0,"/"),
id:"closeAllFilesButton",tooltip:LC.getLabel("Tooltips","CloseAll"),handler:function(){apex.ide.IDE.closeAll()}}]});
SfdcDevConsole.Menu.debugMenu=Ext.create("Ext.menu.Menu",{id:"debugMenu",width:300,style:{overflow:"visible"},refresh:function(){Ext.getCmp("switchPerspectiveMenu").disable();Ext.getCmp("viewPanelsMenu").disable();Ext.getCmp("savePerspectiveButton").disable();Ext.getCmp("saveAsPerspectiveButton").disable();Ext.getCmp("openExecuteAnonymousWindow").disable();Ext.getCmp("executeLast").disable();Ext.getCmp("resumeSessionButton").hide();var a=Ext.getCmp("editors").getActiveTab();apex.ide.IDE.hasApex&&
apex.ide.IDE.authorApex&&(Ext.getCmp("openExecuteAnonymousWindow").enable(),Ext.getCmp("executeLast").enable());a&&a instanceof apex.csi.LogViewer&&(apex.ide.CsiPerspectiveDefinition.getPerspectiveList(),Ext.getCmp("switchPerspectiveMenu").enable(),Ext.getCmp("viewPanelsMenu").enable(),Ext.getCmp("savePerspectiveButton").enable(),Ext.getCmp("saveAsPerspectiveButton").enable());SfdcDevConsole.Session.isAlive()||Ext.getCmp("resumeSessionButton").show()},listeners:{show:function(a,b){SfdcDevConsole.Menu.debugMenu.refresh()}},
items:[{id:"openExecuteAnonymousWindow",text:SfdcDevConsole.Menu.menuEntryWithShortcut(LC.getLabel("DevConsoleMenuItem","OpenExecAnon"),!0,!1,!1,"E",LC.getLabel("Shortcuts","OpenExecuteAnonymous")),handler:function(){apex.execanon.ExecuteAnonymous.open()}},{id:"executeLast",text:SfdcDevConsole.Menu.menuEntryWithShortcut(LC.getLabel("DevConsoleMenuItem","ExecuteLast"),!0,!1,!0,"E",LC.getLabel("Shortcuts","ExecuteAnonymous")),handler:function(){apex.ide.IDE.executeAnonymous(apex.ide.IDE.lastExecuteAnon,
apex.execanon.ExecuteAnonymous.openLog)}},{text:"Switch Perspective",id:"switchPerspectiveMenu",tooltip:LC.getLabel("Tooltips","SwitchPerspective"),disabled:!0,hideOnClick:!1,menu:{items:[{xtype:"grid",width:200,hideHeaders:!0,id:"perspectivesList",autoExpandColumn:"Name",forceFit:!0,selModel:{mode:"SINGLE"},columns:[{header:"id",dataIndex:"id",hidden:!0},{header:"Name",width:100,dataIndex:"name",renderer:function(a,b,c){return c.data.name===Ext.getCmp("editors").getActiveTab().currentPerspectiveConfig.label&&
(b.style='font-weight:bold;"',Ext.getCmp("editors").getActiveTab().isPerspectiveDirty)?escapeHTML(c.data.name)+"*":escapeHTML(c.data.name)}}],store:Ext.create("Ext.data.Store",{storeId:"perspectivesList",idField:"id",fields:[{name:"id"},{name:"name"}]}),listeners:{itemclick:function(a,b,c,f,d,e){Ext.getCmp("editors").getActiveTab();b&&SfdcDevConsole.Events.EventDispatcher.fire("perspective:open",[apex.ide.CsiPerspectiveDefinition,b.data.name]);Ext.getCmp("perspectiveWindow").hide();Ext.getCmp("debugMenu").hide()}}}]}},
{text:SfdcDevConsole.Menu.menuEntryWithShortcut(LC.getLabel("DevConsoleMenuItem","ViewLogPanels"),!0,!1,!1,"P"),id:"viewPanelsMenu",tooltip:LC.getLabel("Tooltips","ViewLogPanels"),disabled:!0,handler:function(){Ext.getCmp("logPanelWindow").show()}},{text:LC.getLabel("DevConsoleMenuItem","PerspectiveManager"),id:"perspectiveManagerButton",handler:function(){Ext.getCmp("perspectiveWindow").show()}},{text:LC.getLabel("DevConsoleMenuItem","SavePerspective"),id:"savePerspectiveButton",tooltip:LC.getLabel("Tooltips",
"SavePerspective"),disabled:!0,scope:this,handler:function(){apex.ide.CsiPerspectiveDefinition.saveCurrentPerspective()}},{text:LC.getLabel("DevConsoleMenuItem","SavePerspectiveAs"),id:"saveAsPerspectiveButton",tooltip:LC.getLabel("Tooltips","SavePerspectiveAs"),disabled:!0,scope:this,handler:function(){Ext.Msg.prompt(LC.getLabel("DevConsoleMenuItem","SavePerspective"),LC.getLabel("DevConsoleMenuItem","PerspectiveName"),function(a,b){if("ok"==a){var c=Ext.getCmp("editors").getActiveTab(),c=apex.ide.CsiPerspectiveDefinition.generateConfig(c.items);
SfdcDevConsole.Events.EventDispatcher.fire("perspective:save",[apex.ide.CsiPerspectiveDefinition,{label:b,perspectiveConfig:c}])}})}},{id:"hideAutomatically",text:LC.getLabel("DevConsoleMenuItem","AutoHideLogs"),checked:!1},{id:"mySessionLogsOnly",text:LC.getLabel("DevConsoleMenuItem","SessionLogsOnly"),checked:!0,handler:function(){apex.csi.LogBrowser.updateLogFilter()}},{id:"mySessionFewmetsOnly",text:LC.getLabel("DevConsoleMenuItem","SessionFewmetsOnly"),checked:!0,handler:function(){apex.fewmet.FewmetBrowser.updateFewmetFilter()}},
{text:LC.getLabel("ApexCSI","clear"),id:"clearMenuEntry",hideOnClick:!1,menu:{items:[{text:SfdcDevConsole.Menu.menuEntryWithShortcut(LC.getLabel("DevConsoleMenuItem","LogPanel"),!1,!0,!0,"G"),id:"clearButton",listeners:{click:function(a,b){apex.ide.IDE.clearList()}}},{text:LC.getLabel("DevConsoleMenuItem","CheckpointPanel"),id:"fewmetClearButton",listeners:{click:function(a,b){apex.ide.IDE.clearList()}}},{text:LC.getLabel("DevConsoleMenuItem","CheckpointLocations"),id:"clearLocationsButton",listeners:{click:function(a,
b){var c=Ext.StoreMgr.lookup("fewmetConfig"),f=[];c.each(function(a){var b=Ext.getCmp(a.data.ExecutableEntityId);b&&b.cmEditor&&b.cmEditor.setBreakpointMarker(a.data.Line,!1);f.push(a)});c.remove(f);c.sync()}}}]}},{id:"resumeSessionButton",hidden:!0,text:LC.getLabel("DeveloperConsole","ResumeSession"),listeners:{click:function(a,b){SfdcDevConsole.Session.initialize()}}},{id:"filtersButton",text:LC.getLabel("DevConsoleMenuItem","ChangeLogLevels"),handler:function(){SfdcDevConsole.TraceFlags.show()}}]});
SfdcDevConsole.Menu.testMenu=Ext.create("Ext.menu.Menu",{id:"testMenu",style:{overflow:"visible"},width:200,handler:function(a){if(0<Ext.getCmp("testResultTree").getSelectionModel().getSelection().length){for(var b=Ext.getCmp("testResultTree").getSelectionModel().getSelection()[0],b=apex.test.TestResultBrowser.getRunNode(b).childNodes,c=[],f=[],d=0,e=b.length;d<e;d++){for(var g=[],l=0,n=b[d].childNodes.length;l<n;l++){var m=b[d].childNodes[l].data;(a&&"Fail"===m.status||!a)&&g.push(m.name)}0<g.length&&
c.push({classId:b[d].data.classid,testMethods:g})}for(d=0;d<b.length;d++)(a&&0===b[d].childNodes.length&&"Failed"===b[d].data.status||!a&&0===b[d].childNodes.length)&&f.push(b[d].data.jobid);Ext.Ajax.request({url:"/_ui/common/apex/test/ApexTestQueueServlet",params:{action:"GET_MULTIPLE_TEST_RESULTS",jobid:f},success:function(b,f){var e=Util.evalAjaxServletOutput(b.responseText),k={};if(e.success){for(d=0;d<e.testResults.length;d++){var h=e.testResults[d];void 0===k[h.classid]&&"Fail"===h.outcome&&
a||!a&&void 0===k[h.classid]?k[h.classid]=[h.method]:("Fail"===h.outcome&&a||!a)&&k[h.classid].push(h.method)}for(var g in k)k.hasOwnProperty(g)&&c.push({classId:g,testMethods:k[g]});0<c.length?(e=apex.ide.IDE.runTestsSynchronously(c),apex.ide.IDE.runSelectedTests(c,e)):Ext.Msg.alert("Synchronous test run in progress","If you want to run these tests again, either cancel the in-progress test run or wait for it to finish.")}}})}else Ext.MessageBox.alert("Rerun Error","To rerun, select a test run from the Tests tab.")},
items:[{text:LC.getLabel("Test","RunAsynch"),id:"runTestsAsyncButton",checked:!1},{text:LC.getLabel("Test","NewRun"),id:"newTestRunButton",handler:function(){var a=apex.test.TestResultBrowser.getTestSelectWindow();a.selected=[];a.show()},listeners:{afterrender:function(a){a.testBrowser=Ext.getCmp("testResults");a.testBrowser.newRun=a}}},{text:LC.getLabel("Test","ReRun"),id:"reRunTestButton",handler:function(a){SfdcDevConsole.Menu.testMenu.handler(!1)},listeners:{afterrender:function(a){a.testBrowser=
Ext.getCmp("testResults");a.testBrowser.copyRun=a}}},{text:LC.getLabel("Test","ReRunFailedTests"),id:"reRunFailedTestButton",handler:function(a){SfdcDevConsole.Menu.testMenu.handler(!0)},listeners:{afterrender:function(a){a.testBrowser=Ext.getCmp("testResults");a.testBrowser.copyRun=a}}},{text:LC.getLabel("Test","RunAll"),id:"testRunAllButton",handler:function(a){apex.test.TestResult.getTestClasses(function(a){if(0===a.length)Ext.Msg.alert("Error",LC.getLabel("Test","RunTestError_NoTests"));else{for(var c=
[],f=0;f<a.length;f++)c.push(a[f].id);apex.ide.IDE.runTests(c,function(a){apex.test.TestResultBrowser.runAllJobId=a.jobid})}})},listeners:{afterrender:function(a){a.testBrowser=Ext.getCmp("testResults");a.testBrowser.runAll=a}}},{text:LC.getLabel("Test","Abort"),id:"testAbortButton",handler:function(a){a=Ext.getCmp("testResultTree").getSelectionModel().getSelection();if(0<a.length&&(a=a[0],"Completed"!==a.data.status&&"Fail"!==a.data.status))if(a.data.sync)Ext.MessageBox.alert("Error","Please wait while the test run finishes.");
else if(""!==a.data.jobid)apex.test.TestResultBrowser.abortTestRuns([a.data.jobid]);else if(!a.isLeaf()){for(var b=[],c=0;c<a.childNodes.length;c++)b.push(a.childNodes[c].data.jobid);apex.test.TestResultBrowser.abortTestRuns(b)}},listeners:{afterrender:function(a){a.testBrowser=Ext.getCmp("testResults");a.testBrowser.aboard=a}}},{xtype:"menuseparator"},{text:LC.getLabel("Test","NewSuite"),id:"newSuiteButton",handler:function(a){apex.test.TestSuite.newTestSuite()}},{text:LC.getLabel("Test","SuiteManager"),
id:"suiteManagerButton",handler:function(a){apex.test.TestSuite.TestSuiteWindow.show()}},{text:LC.getLabel("Test","NewSuiteRun"),id:"newSuiteRun",handler:function(a){apex.test.TestSuite.getRunSuitesWindow().show()}},{xtype:"menuseparator"},{text:LC.getLabel("Test","CollapseAll"),id:"testCollapseAllButton",handler:function(){var a=Ext.getCmp("testResultTree").getRootNode();apex.test.TestResultBrowser.collapseAllChildren(a)}},{text:LC.getLabel("Test","ExpandAll"),id:"testExpandAllButton",handler:function(){var a=
Ext.getCmp("testResultTree").getRootNode();apex.test.TestResultBrowser.expandAllChildren(a)}},{xtype:"menuseparator"},{text:LC.getLabel("Page_ApexTestResults","clearAction"),id:"clearTestResultsButton",tooltip:LC.getLabel("Tooltips","ClearTestResults"),handler:function(){apex.test.TestResultBrowser.clearTestResults(function(){Ext.getCmp("aggregateCoverageGrid").getStore().removeAll()})}}]});
SfdcDevConsole.Menu.wsMenu=Ext.create("Ext.menu.Menu",{id:"wsMenu",style:{overflow:"visible"},width:200,listeners:{show:function(){apex.ide.IDE.createWorkspaceList()}},items:[{text:LC.getLabel("Workspace","SwitchWorkspace"),hideOnClick:!1,menu:{items:[{xtype:"grid",hideHeaders:!0,width:200,id:"workspaceList",forceFit:!0,selModel:{mode:"SINGLE"},columns:[{header:"id",dataIndex:"id",hidden:!0},{header:"Name",width:100,dataIndex:"name",renderer:function(a,b,c){c.data.name===apex.ide.IDE.workspaceName&&
(b.style='font-weight:bold;"');return c.data.name}}],store:Ext.create("Ext.data.Store",{storeId:"workspaceList",idField:"id",fields:[{name:"id"},{name:"name",type:"string"}],sorters:[{property:"name",direction:"ASC"}]}),listeners:{itemclick:function(){var a=Ext.getCmp("workspaceList").getSelectionModel().getSelection()[0];apex.ide.IDE.openWorkspace(a.data.id);Ext.getCmp("wsMenu").hide()}}}]}},{text:LC.getLabel("Workspace","NewWorkspace"),handler:function(){apex.ide.IDE.newWorkspace()}},{text:LC.getLabel("Workspace",
"RenameCurrentWorkspace"),handler:function(){Ext.Msg.prompt(LC.getLabel("Workspace","RenameCurrentWorkspace"),LC.getLabel("Workspace","WorkspaceName"),function(a,b){if("ok"==a){var c=apex.ide.IDE.workspaceName;apex.ide.IDE.workspaceName=b;apex.ide.IDE.updateWorkspaceImpl(function(a){apex.ide.IDE.workspaceName=c;Ext.Msg.alert(LC.getLabel("Workspace","RenameError"),LC.getLabel("Workspace","WorkspaceRenameFailed")+" "+escapeHTML(c)+": "+a)});apex.ide.IDE.workspaceWindow.hide();Ext.Msg.hide()}})}},{text:LC.getLabel("Workspace",
"WorkspaceManager"),id:"workspaceManagerMenuEntry",handler:function(){apex.ide.IDE.workspaceWindow.show()}}]});
SfdcDevConsole.Menu.helpMenu=Ext.create("Ext.menu.Menu",{id:"helpMenu",width:220,style:{overflow:"visible"},items:[{text:LC.getLabel("DevConsoleMenuItem","HelpDocs"),href:"/help/doc/user_ed.jsp?loc\x3dhelp\x26target\x3dcode_system_log.htm\x26section\x3dintegrate",hrefTarget:"_blank"},{id:"shortcutHelp",text:SfdcDevConsole.Menu.menuEntryWithShortcut(LC.getLabel("Shortcuts","title"),!0,!0,!1,"?",LC.getLabel("Shortcuts","ShortcutPanel")),handler:function(){apex.ide.ShortcutRegistry.win.show()}},{text:LC.getLabel("DevConsolePrefs",
"title"),id:"openPreferencesButton",handler:function(){SfdcDevConsole.Preferences.open()}},{text:LC.getLabel("DevConsoleMenuItem","ComponentLibrary"),href:"/docs/component-library",hrefTarget:"_blank"}]});
SfdcDevConsole.Menu.fileEditMenu=Ext.create("Ext.menu.Menu",{id:"fileEditMenu",width:280,style:{overflow:"visible"},items:[{text:SfdcDevConsole.Menu.menuEntryWithShortcut(LC.getLabel("DevConsoleMenuItem","Find"),!0,!1,!1,"F"),id:"findButton",tooltip:LC.getLabel("Shortcuts","FindInText"),handler:function(){Ext.getCmp("editors").getActiveTab().find()}},{text:SfdcDevConsole.Menu.menuEntryWithShortcut(LC.getLabel("DevConsoleMenuItem","Replace"),!0,!0,!1,"F"),id:"replaceButton",tooltip:LC.getLabel("Shortcuts",
"ReplaceInText"),handler:function(){Ext.getCmp("editors").getActiveTab().replace()}},{text:SfdcDevConsole.Menu.menuEntryWithShortcut(LC.getLabel("DevConsoleMenuItem","ReplaceAll"),!0,!0,!1,"R"),id:"replaceAllButton",tooltip:LC.getLabel("Shortcuts","ReplaceAllInText"),handler:function(){Ext.getCmp("editors").getActiveTab().replaceAll()}},{xtype:"menuseparator"},{text:SfdcDevConsole.Menu.menuEntryWithShortcut(LC.getLabel("SearchInFiles","Title"),!0,!0,!1,"H",null,"restAPI"),id:"searchInFilesButton",
tooltip:LC.getLabel("Tooltips","SearchInFiles"),enabled:!1,handler:function(){apex.ide.SearchInFiles.searchInFiles()}},{xtype:"menuseparator"},{text:SfdcDevConsole.Menu.menuEntryWithShortcut(LC.getLabel("DevConsoleMenuItem","autoIndent"),!1,!0,!1,"TAB"),id:"autoIndentButton",handler:function(){Ext.getCmp("editors").getActiveTab().autoIndent()}},{text:SfdcDevConsole.Menu.menuEntryWithShortcut(LC.getLabel("DevConsoleMenuItem","Prettier"),!0,!1,!0,"F",LC.getLabel("Shortcuts","FormatCode")),id:"formatWithPrettierButton",
tooltip:LC.getLabel("Tooltips","fixCodeFormatting"),handler:function(){Ext.getCmp("editors").getActiveTab().formatWithPrettier()}}],refresh:function(){Ext.getCmp("findButton").disable();Ext.getCmp("replaceButton").disable();Ext.getCmp("replaceAllButton").disable();Ext.getCmp("autoIndentButton").disable();Ext.getCmp("formatWithPrettierButton").disable();var a=Ext.getCmp("editors").getActiveTab();a&&a instanceof apex.editor.SourceFileEditor&&(Ext.getCmp("findButton").enable(),Ext.getCmp("replaceButton").enable(),
Ext.getCmp("replaceAllButton").enable(),Ext.getCmp("autoIndentButton").enable(),window.prettier&&apex.ide.Prettier.canFormatFile(a)&&Ext.getCmp("formatWithPrettierButton").enable())},listeners:{show:function(a,b){SfdcDevConsole.Menu.fileEditMenu.refresh()}}});
SfdcDevConsole.Menu.toolbar=Ext.create("Ext.toolbar.Toolbar",{cls:"topLevelToolbar",items:[{text:LC.getLabel("DevConsoleMenuItem","File"),id:"editorMenuEntry",menu:SfdcDevConsole.Menu.editorMenu,handler:function(){}},{text:LC.getLabel("DevConsoleMenuItem","Edit"),id:"fileEditMenuEntry",menu:SfdcDevConsole.Menu.fileEditMenu,handler:function(){}},{text:LC.getLabel("DevConsoleMenuItem","Debug"),id:"debugMenuEntry",menu:SfdcDevConsole.Menu.debugMenu,handler:function(){}},{text:LC.getLabel("DevConsoleMenuItem",
"Test"),id:"testMenuEntry",menu:SfdcDevConsole.Menu.testMenu,handler:function(){}},{text:LC.getLabel("DevConsoleMenuItem","Workspace"),id:"workspaceMenuEntry",menu:SfdcDevConsole.Menu.wsMenu},{text:LC.getLabel("DevConsoleMenuItem","Help"),menu:SfdcDevConsole.Menu.helpMenu},{text:"\x3c",id:"backButton",disabled:!0,handler:function(){apex.ide.IDE.back()}},{text:"\x3e",id:"forwardButton",disabled:!0,handler:function(){apex.ide.IDE.forward()}}],refresh:function(a){Ext.getCmp("newMenuEntry").enable();
Ext.getCmp("newApexClassButton").enable();Ext.getCmp("newDataPipelineButton").enable();Ext.getCmp("apexTriggerMenuEntry").enable();Ext.getCmp("newVFpageButton").enable();Ext.getCmp("newVFcomponentButton").enable();Ext.getCmp("newSaveButton").disable();Ext.getCmp("newSaveButton").setText(SfdcDevConsole.Menu.menuEntryWithShortcut("Save",!0,!1,!1,"S",LC.getLabel("Shortcuts","Save")));Ext.getCmp("saveAllButton").enable();Ext.getCmp("saveAllButton").setText(SfdcDevConsole.Menu.menuEntryWithShortcut("Save All",
!0,!0,!1,"S"));Ext.getCmp("metatypeDeleteButton").disable();Ext.getCmp("closeButton").disable();Ext.getCmp("openLogButton").disable();Ext.getCmp("openRawLogButton").disable();Ext.getCmp("downloadLogButton").disable();apex.ide.IDE.authorVisualforce||(Ext.getCmp("newVFpageButton").disable(),Ext.getCmp("newVFcomponentButton").disable());apex.ide.IDE.authorApex||(Ext.getCmp("newApexClassButton").disable(),Ext.getCmp("apexTriggerMenuEntry").disable());!apex.ide.IDE.authorVisualforce&&!apex.ide.IDE.authorApex&&
Ext.getCmp("newMenuEntry").disable();apex.ide.IDE.hasAura||(Ext.getCmp("newAuraAppButton").hide(),Ext.getCmp("newAuraCmpButton").hide(),Ext.getCmp("newAuraIntButton").hide(),Ext.getCmp("newAuraEventButton").hide(),Ext.getCmp("openAuraButton").hide());apex.ide.IDE.restAPI||Ext.getCmp("searchInFilesButton").hide();apex.ide.IDE.dataPipelineDevConsole||Ext.getCmp("newDataPipelineButton").hide();Ext.getCmp("traceGrid").getSelectionModel().hasSelection()&&(Ext.getCmp("openLogButton").enable(),Ext.getCmp("openRawLogButton").enable());
a||(a=Ext.getCmp("editors").getActiveTab());a&&(Ext.getCmp("closeButton").enable(),a instanceof apex.csi.BaseLogViewer&&Ext.getCmp("downloadLogButton").enable(),a.canEdit&&a.canEdit()?(Ext.getCmp("newSaveButton").enable(),Ext.getCmp("metatypeDeleteButton").enable(),a.saving&&(Ext.getCmp("saveAllButton").disable(),Ext.getCmp("saveAllButton").setText(LC.getLabel("DeveloperConsole","Saving")),Ext.getCmp("newSaveButton").disable(),Ext.getCmp("newSaveButton").setText(LC.getLabel("DeveloperConsole","Saving")))):
(Ext.getCmp("metatypeDeleteButton").disable(),Ext.getCmp("newSaveButton").disable()))},listeners:{show:function(a,b){SfdcDevConsole.Menu.toolbar.refresh()}}});

//# sourceMappingURL=/javascript/1568710058000/sfdc/source/ApexIDEBase_Ext4.js.map
