/*
 * This code is for Internal Salesforce use only, and subject to change without notice.
 * Customers shouldn't reference this file in any web pages.
 */
var Console=function(c,e){function l(a,h){if("string"!==typeof a)throw"Action name must be of type string";if(!h||"function"!==typeof h.run)throw"Action '"+a+"' has no run method";if(g[a])throw"Action '"+a+"' already exist";if(null===h.options||"object"!==typeof h.options)h.options=[];h.forEachOption=function(a){if("function"===typeof a){var b=0,c;for(c in h.options)if(h.options.hasOwnProperty(c)&&(b++,!a(c,h.options[c])))break;return b}throw"The callback must be a function";};g[a]=h}function s(a,
h){var b=document.createElement("div");b.setAttribute("class","outputline");h?(b.textContent=a,b.innerText=a):b.innerHTML=a;t.appendChild(b)}function r(a){return a.replace(/^\s+/,"").replace(/\s+$/,"")}function y(a){var b={rawInput:a,options:[]};a=r(a);if(0===a.length)throw"No command to parse";var c=a.indexOf(" ");if(0<=c){b.command=a.substring(0,c);var d=g[b.command];if(!d)throw b.command+": command not found";a=r(a).substring(c+1,a.length);if(d.forEachOption(function(){return!1})){d=d.options;
a=a.split(/\s+/);for(var e=[],c=0;c<a.length;c++)if(0===a[c].indexOf("-")){var f=a[c].substring(1);if(d[f])e.push(f);else throw f+": option not found";}else break;b.options=e;for(d="";c<a.length;c++)d+=a[c]+" ";b.input=r(d)}else b.input=a}else if(b.command=a,!g[b.command])throw b.command+": command not found";return b}if(!(this instanceof arguments.callee))throw"Constructor called as a function";try{if(!(c instanceof HTMLElement))throw"The container must be a valid HTML element";}catch(z){if(null===
c||"object"!==typeof c||1!==c.nodeType||"object"!==typeof c.style||"object"!==typeof c.ownerDocument)throw"The container must be a valid HTML element";}e||(e={});var k=e.width||500,x=e.height||300,d=e.marker||"console$",g=[];if(e.actions&&"object"===typeof e.actions)for(var u in e.actions)e.actions.hasOwnProperty(u)&&l(u,e.actions[u]);else if(e.actions)throw"Actions must be an object containing actions";var n=e.history||[""],q=n.length-1,d=d+" ",v=k+("string"===typeof k?"":"px"),w=x+("string"===typeof x?
"":"px");c.setAttribute("class","Console");c.setAttribute("style","height:"+w+";width:"+v);var t=document.createElement("div");t.setAttribute("class","Console-output");var b=document.createElement("textarea"),k=document.createElement("div");k.setAttribute("class","Console-input");b.setAttribute("class","Console-inputField, noscroll");b.setAttribute("style","width: 100%");b.spellcheck=!1;b.value=d;var f={element:c,isHidden:function(){return"none"===c.style.display},show:function(){c.style.display=
"";this.finished()},hide:function(){c.style.display="none"},focus:function(){b.focus()},finished:function(){b.disable=!1;b.value=d;c.scrollTop=c.scrollHeight;this.focus()},setBackgroundColor:function(a){c.style.backgroundColor=a},setFontColor:function(a){c.style.color=a;b.style.color=a},setFullScreen:function(a){a?(c.style.height="100%",c.style.width="100%"):(c.style.height=w,c.style.width=v)},getConfig:function(){return{height:w,width:v,fullscreen:"100%"===c.style.height&&"100%"===c.style.width,
backgroundColor:c.style.backgroundColor,fontColor:c.style.color?c.style.color:"black"}}};e.backgroundColor&&f.setBackgroundColor(e.backgroundColor);e.fontColor&&f.setFontColor(e.fontColor);e.fullscreen&&f.setFullScreen(!0);f.output=s;f.addAction=l;var m={printAction:function(a,b){var c="\x3cb\x3e"+a+": \x3c/b\x3e";b.help?(f.output(c),f.output(b.help),b.forEachOption(function(a,b){f.output("- "+a+": "+b.description);return!0})):f.output(c+LC.getLabel("CommandLine","Help_NoHelpError",a))},options:{a:{description:LC.getLabel("CommandLine",
"Help_Option_a_Desc"),run:function(a,b,c){for(var d in g)g.hasOwnProperty(d)&&c.printAction(d,g[d]);return!1}}},run:function(a,b){var c=g[b];if(b&&""!==b){if(!c)return a.output(LC.getLabel("CommandLine","CommandNotFound",b)),!0;this.printAction(b,c);return!0}}};l("help",{printAction:m.printAction,options:m.options,run:function(a,b){m.run(a,b)||(a.output(LC.getLabel("DeveloperConsole","Title")+" "+LC.getLabel("CommandLine","Title")+":"),a.output(LC.getLabel("CommandLine","Help_Info1"),!0),a.output(LC.getLabel("CommandLine",
"Help_Info2","help"),!0))},help:LC.getLabel("CommandLine","Help_Help")});l("man",{printAction:m.printAction,options:m.options,run:function(a,b){m.run(a,b)||a.output(LC.getLabel("CommandLine","Help_Info2","man"),!0)},help:LC.getLabel("CommandLine","Man_Help")});l("commands",{options:{f:{description:LC.getLabel("CommandLine","Commands_Option_f_Desc"),run:function(a,b,c){c.printCommands(a,b);return!1}}},run:function(a,b){this.printCommands(a)},printCommands:function(a,b){a.output(LC.getLabel("CommandLine",
"Commands_Title"));for(var c in g)if(g.hasOwnProperty(c)&&(!b||0<=c.indexOf(b)))a.output("\x26nbsp;\x26nbsp;\x26nbsp;\x26nbsp;\x26nbsp;\x3cb\x3e"+c+"\x3c/b\x3e"+(g[c].help?" : "+g[c].help:""))},help:LC.getLabel("CommandLine","Commands_Help")});b.onclick=function(){b.selectionStart<d.length&&(b.selectionStart=d.length);b.selectionEnd<d.length&&(b.selectionEnd=d.length)};b.onselect=function(){b.selectionStart<d.length&&(b.selectionStart=d.length);b.selectionEnd<d.length&&(b.selectionEnd=d.length);return!0};
b.onfocus=function(){b.selectionStart=b.value.length};c.appendChild(t);k.appendChild(b);c.appendChild(k);c.onclick=function(){b.focus()};var p={ENTER:{shouldHandle:function(a){return 13===a.keyCode},handle:function(){try{s(b.value);var a=y(b.value.substring(d.length));q=n.length;n.push(a.rawInput);b.value="";a:{if(null===a||"object"!==typeof a||"string"!==typeof a.command||void 0===g[a.command])throw LC.getLabel("CommandLine","CommandNotFound",a.command);for(var e=g[a.command],k=a.input,m=0;m<a.options.length;m++){var l=
e.options[a.options[m]].run(f,k,e);if("string"===typeof l)k=l;else if("boolean"===typeof l&&!l)break a}e.run(f,"string"===typeof k?r(k):"")}}catch(p){s(p)}b.value=d;c.scrollTop=c.scrollHeight;return!1}},UP_ARROW:{shouldHandle:function(a){return 38===a.keyCode},handle:function(){0<q&&(b.value=d+n[q--],b.selectionStart=b.value.length,b.selectionEnd=b.value.length);return!1}},DOWN_ARROW:{shouldHandle:function(a){return 40===a.keyCode},handle:function(){q+1<n.length-1&&(b.value=d+n[++q+1],b.selectionStart=
b.value.length,b.selectionEnd=b.value.length);return!1}},HIGHLIGHT:{shouldHandle:function(a){return 8===a.keyCode&&b.selectionStart<=d.length&&b.selectionEnd<=d.length||37===a.keyCode&&b.selectionStart<=d.length||37===a.keyCode&&a.ctrlKey||37===a.keyCode&&a.metaKey},handle:function(a){b.selectionStart!==d.length&&(b.selectionStart=d.length,a.shiftKey||(b.selectionEnd=d.length));return!1}}};b.onkeydown=function(a){void 0===a&&(a=window.event);for(var c in p)if(p.hasOwnProperty(c)&&p[c].shouldHandle(a))return p[c].handle(a);
b.selectionStart<=d.length&&(b.selectionStart=d.length)};e.afterInit&&e.afterInit.call&&e.afterInit(f);return f};
Sfdc.ns("SfdcDevConsole.Events");
SfdcDevConsole.Events={PREFIX:"SfdcDevConsoleEvent:",EventDescription:new Sfdc.Class({name:null,object:null,handlers:null,$constructor:function(c,b){if(!Sfdc.isString(c))throw"Event name must be a string";this.name=SfdcDevConsole.Events.PREFIX+c;this.object=b?b:"undefined"!==typeof window?window:null;this.handlers=[]},fire:function(c,b){Sfdc.Event.fireEvent(this.object,this.name,{context:b?b:this.object,data:c})},on:function(c,b){b?Sfdc.Event.add(this.object,this.name,c,b):Sfdc.Event.add(this.object,
this.name,c);this.handlers.push(c)},un:function(c){Sfdc.Event.remove(this.object,this.name,c);for(var b=0;b<this.handlers.length;b++)if(this.handlers[b].toString()===c.toString()){this.handlers.splice(b,1);break}},removeAll:function(){for(var c=0;c<this.handlers.length;c++)Sfdc.Event.remove(this.object,this.name,this.handlers[c]);this.handlers=[]}}),EventDispatcher:function(){function c(a){if(!Sfdc.isString(a))throw"Event must be a string";if(!b[SfdcDevConsole.Events.PREFIX+a])throw"Event "+a+" is not registered.";
return SfdcDevConsole.Events.PREFIX+a}var b={};return{register:function(a){if(Sfdc.isString(a))a=new SfdcDevConsole.Events.EventDescription(a),b[a.name]=a;else if(Sfdc.inherits(SfdcDevConsole.Events.EventDescription,a))b[a.name]=a;else throw"Event desctiption must be of type String or SfdcDevConsole.Events.EventDescription";},fire:function(a,e,d){a=c(a);b[a].fire(e,d)},on:function(a,e,d){a=c(a);b[a].on(e,d)},once:function(a,e,d){var f=c(a);b[f].on(function(){e.apply(d,arguments);b[f].un(arguments.callee,
d)},d)},get:function(a){a=c(a);return b[a]}}}()};
Sfdc.ns("SfdcDevConsole.Core.Search.SOSLUtil");
(function(){var g=/[-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g;SfdcDevConsole.Core.Search.getWildcardFilterFunction=function(d){var c=null,b=!1;d=Sfdc.String.trim(d);0===d.indexOf("re:")&&(b=!0,d=d.substring(3));try{var a=null;if(b)a=RegExp(d,"i");else var e=d.replace(g,"\\$\x26"),e=e.replace(/\\\*/g,".*"),a=RegExp("^"+e,"i");c=function(b){return!!b.match(a)}}catch(f){c=function(a){return 0<=a.toLowerCase().indexOf(d.toLowerCase())}}return c};SfdcDevConsole.Core.Search.SOSLUtil={SOSL_SC:"\x26!{}~:\"'-".split(""),
REGEX_SC:["$","."],sanitizeSpecialCharacters:function(d){for(var c="",b=0,a,e,f;b<d.length;){e=d[b];if("\\"===e){if(f=d[b+1],-1!==SfdcDevConsole.Core.Search.SOSLUtil.SOSL_SC.indexOf(f)){c+=f;b+=2;continue}}else-1!==SfdcDevConsole.Core.Search.SOSLUtil.REGEX_SC.indexOf(e)?c+="\\":"*"===e&&null!==a&&"\\"!==a&&(c+=".");a=e;c+=e;b++}return c},matcher:function(d){var c=this.sanitizeSpecialCharacters;return{ws:/^\s+/,qt:/^"(?:\\.|[^"])+"/,ex:/^(AND|OR|NOT)/i,wd:/^\S+/,so:/^(?:\\\)|[^\)])+/,probe:d,match:function(b){b=
b||[];for(var a;0<this.probe.length;)if(a=this.ws.exec(this.probe),null!==a)this.probe=this.probe.slice(a[0].length);else if(a=this.ex.exec(this.probe),null!==a)this.probe=this.probe.slice(a[0].length);else if(a=this.qt.exec(this.probe),null!==a)this.probe=this.probe.slice(a[0].length),a=a[0].slice(1,a[0].length-1),b.push(c(a));else{"("===this.probe[0]&&(this.probe=this.probe.slice(1),this.match(b));if(")"===this.probe[0]){this.probe=this.probe.slice(1);return}a=this.wd.exec(this.probe);null!==a&&
(a=a[0],a=this.so.exec(a),this.probe=this.probe.slice(a[0].length),b.push(c(a[0])))}if(0<this.probe.length)return Sfdc.log("Unparseable SOSL expr in "+d+" at "+this.probe),null;a=b[0];for(var e=1;e<b.length;e++)a=a+"|"+b[e];return a}}}}})();
Sfdc.ns("SfdcDevConsole");SfdcDevConsole.hasNamespace=function(g){var e=SfdcDevConsole.namespace,f=Sfdc.isString(e)&&0<e.length;return null===g?!f:Sfdc.isString(g)?0===g.length?!f:f&&e.toLowerCase()===g.toLowerCase():f};
SfdcDevConsole.ToolingAPI=function(){function g(a){if(Sfdc.isDefAndNotNull(a)&&(void 0===a.method||"GET"===a.method)&&!0!==a.cache)a.data=a.data||{},a.data._=(new Date).getTime()}var e={base:"undefined"!==typeof window?window.location.protocol+"//"+window.location.host:"",api:function(a){return e.base+"/services/data/v46.0"+(a?"/tooling":"")},sobject:function(a,b,c,d,k){return e.api(b)+"/sobjects/"+a+((c?"/"+ApiUtils.to18CharId(c):"")+(k?"/"+k:"")+(d?"?_HttpMethod\x3dPATCH":""))},query:function(a,
b,c,d){b=e.api(b)+"/query/";var k={};d?k.explain=a:k.q=a;return b+Sfdc.Url.generateQueryString("",Sfdc.apply(k,c))},search:function(a,b){return e.api(!1)+"/search/"+Sfdc.Url.generateQueryString("",Sfdc.apply({q:a},b))},executeAnonymous:function(){return e.api(!0)+"/executeAnonymous/"},runTests:function(){return e.api(!0)+"/runTestsAsynchronous/"},runTestsSync:function(){return e.api(!0)+"/runTestsSynchronous/"},completions:function(a){return e.api(!0)+"/completions?type\x3d"+a}},f={version:"46.0",
availableVersions:5,getMilliSecondsFromAPIDate:function(a){var b=(new Date(a)).getTime();if(!b||isNaN(b))try{var c=a.replace("T"," "),d=a.indexOf(".");0<=d&&(c=c.substring(0,d));c=c.replace(/-/g,"/");b=Date.parse(c)}catch(e){}return b},URLs:e,request:function(a){!Sfdc.isFunction(a.success)&&Sfdc.isFunction(a.continuation)&&(a.success=function(b,d,e){d=b;try{b&&0<b.length&&(d=Sfdc.JSON.parse(b))}finally{a.continuation(d)}});Sfdc.isFunction(a.failure)||(a.failure=function(b){var d=a.failureMessage||
"",e=a.alertOnFailure||!1,g=Sfdc.isBoolean(a.gackOnFailure)?a.gackOnFailure:!0;if(Sfdc.isFunction(a.additionalFailureHandler))try{a.additionalFailureHandler(b)}catch(h){}f.handleFailedRequest(b,d,e,!g,a.alertHandler)});a.headers||(a.headers={});g(a);var b=a.sid||SfdcDevConsole.SID;b&&(a.headers.Authorization="OAuth "+b);a.headers.Accept||(a.headers.Accept="application/json");a.contentType||(a.contentType="application/json");"application/json"===a.contentType&&(Sfdc.isObject(a.data)&&"POST"===a.method)&&
(a.data=Sfdc.JSON.stringify(a.data));a.headers["Sforce-Call-Options"]||(a.headers["Sforce-Call-Options"]="client\x3ddevconsole");return Sfdc.Ajax.request(a.url,a)},completions:function(a,b){b.url=e.completions(a);f.request(b)},query:function(a,b){var c=Sfdc.isBoolean(b.tooling)?b.tooling:!0;b.url=e.query(a,c,b.params,b.explain);f.request(b)},search:function(a,b){var c=Sfdc.isBoolean(b.tooling)?b.tooling:!0;b.url=e.search(a,c,b.params);b.escape=encodeURIComponent;f.request(b)},sobject:function(a,b){var c=
Sfdc.isBoolean(b.tooling)?b.tooling:!0;b.url=e.sobject(a,c);b.describe?b.url+="/describe":b.id&&(b.url+="/"+b.id,b.body&&(b.url+="/Body",b.continuation&&(b.success=b.continuation,delete b.continuation)));f.request(b)},executeAnonymous:function(a,b){b.url=e.executeAnonymous();b.data={anonymousBody:a};b.escape=encodeURIComponent;f.request(b)},runTests:function(a,b,c,d){b.url=e.runTests();b.method="POST";0<a.length&&"01p"==a[0].substring(0,3)?b.data=0<=c?Sfdc.JSON.stringify({classids:a.join(","),maxFailedTests:c,
skipCodeCoverage:d}):Sfdc.JSON.stringify({classids:a.join(","),skipCodeCoverage:d}):b.data=0<=c?Sfdc.JSON.stringify({suiteids:a.join(","),maxFailedTests:c,skipCodeCoverage:d}):Sfdc.JSON.stringify({suiteids:a.join(","),skipCodeCoverage:d});f.request(b)},runSelectedTests:function(a,b,c,d,k){b.url=c?e.runTestsSync():e.runTests();b.method="POST";b.data=0<=d?Sfdc.JSON.stringify({tests:a,maxFailedTests:d,skipCodeCoverage:k}):Sfdc.JSON.stringify({tests:a,skipCodeCoverage:k});f.request(b)},create:function(a,
b,c){var d=Sfdc.isBoolean(c.tooling)?c.tooling:!0;c.url=e.sobject(a,d);c.method="POST";c.data=Sfdc.JSON.stringify(b);f.request(c)},DELETE:function(a,b,c){var d=Sfdc.isBoolean(c.tooling)?c.tooling:!0;c.url=e.sobject(a,d,b);c.method="DELETE";f.request(c)},save:function(a,b,c){if(!b.id&&!b.Id)throw"Missing field: ID";c||(c={});var d=Sfdc.isBoolean(c.tooling)?c.tooling:!0;c.url=e.sobject(a,d,b.id||b.Id,!0);c.method="POST";a={};Sfdc.apply(a,b);delete a.id;delete a.Id;c.data=Sfdc.JSON.stringify(a);f.request(c)},
getSymbolTable:function(a,b,c){var d=c.continuation;if(!Sfdc.isFunction(d))throw"The continuation must be a function";if(!Sfdc.isString(b)||0>=b.length)throw"The name must be a non-empty string";c.continuation=function(a){var b=null,c=null;try{b=(c=a&&a.records?a.records[0]:null)?c.SymbolTable:null}finally{d(c,b)}};a="SELECT NamespacePrefix, Name, SymbolTable FROM ApexClass WHERE NamespacePrefix \x3d '"+(Sfdc.isString(a)?a:"")+"'    AND Name \x3d '"+b+"' LIMIT 1";f.query(a,c)},handleFailedRequest:function(a,
b,c,d,e){var f="Unknown Error",h="Unknown Error Message: Check for javascript errors.",g=a&&a.responseText||Sfdc.isString(a)&&a;if(g)try{var l=Ext.JSON.decode(g);Sfdc.isArray(l)&&0<l.length&&(l=l[0]);l.errorCode&&(f=l.errorCode);h=l.message?l.message:g}catch(m){h=g}h=escapeHTML(h);if(a&&401===a.status)return apex.ide.IDE.alertUser(a.statusText,h,function(){window.close()}),h;if(a&&403===a.status)return apex.ide.IDE.alertUser("Forbidden: "+f,(b?b+": ":"")+h),h;if(a&&0===a.status)return h="No response from the server",
apex.ide.IDE.alertUser(a.statusText,h),h;c&&apex.ide.IDE.alertUser(f,(b?b+": ":"")+h,e);if(b&&!d)throw b+=": ",b=a?b+(a.status+" - "+a.statusText+" - "+a.responseText):b+"Undefined response",escapeHTML(b);return h}};return f}();
SfdcDevConsole.FixedSizeList=function(g,e,f){var a=[],b={},c={FULL_LIST_EXCEPTION:"Trying to add an element to a full list",add:function(d){var g=f?d.toLowerCase():d;if(c.isFull())throw c.FULL_LIST_EXCEPTION;if(!e||!b[g])a.push(d),e&&(b[g]=!0)},getList:function(){return a},getMaxSize:function(){return g},getSize:function(){return a.length},isFull:function(){return a.length>=g}};return c};
Sfdc.ns("SfdcDevConsole.Extents");
(function(){SfdcDevConsole.Events.EventDispatcher.register("extent:deleted");SfdcDevConsole.Events.EventDispatcher.register("extent:created");String.prototype.endsWith||(String.prototype.endsWith=function(a,b){var c=this.toString();if("number"!==typeof b||!isFinite(b)||Math.floor(b)!==b||b>c.length)b=c.length;b-=a.length;c=c.lastIndexOf(a,b);return-1!==c&&c===b});var e={each:function(a){for(var b in e)if(e.hasOwnProperty(b)){var c=e[b];"object"===typeof c&&a(c)}},getExtentFromId:function(a){if(!a||
!Sfdc.isString(a))throw"Invalid ID: "+a;var b=null;e.each(function(c){c.isId(a)&&(b=c)});return b},getExtentFromType:function(a){if(!a||!Sfdc.isString(a))throw"Invalid type: "+a;var b=null;e.each(function(c){c.entityType===a&&(b=c)});return b},getTableEnumOrId:function(a){var b;if(!a)return null;b=a.id||a.Id;b||(b=a.name||a.Name,(a=a.NamespacePrefix||a.namespacePrefix)&&(b=a+"__"+b));return b},hasNamespace:function(a,b){return!a&&!b||!(!a||!(b&&a.toLowerCase()===b.toLowerCase()))}},f=new Sfdc.Class({$constructor:function(a){Sfdc.apply(this,
a,!0)},getExtension:function(a){return null},beforeOpen:function(a,b){},open:function(a,b){var c;c=this.xtype;var d=a.data||a,h=e.getTableEnumOrId(d);c=Sfdc.apply({id:h,Name:escapeHTML(d.name||d.Name),xtype:c},d);if(d=this.getExtension(a))c.title=c.Name+"."+d;(d=this.beforeOpen(c))?Ext.Msg.alert("Open Error",d):apex.ide.Viewer.open(c,b)},create:function(a){SfdcDevConsole.ExtentUI.createEntity(this,a)},openCreateUI:function(a){SfdcDevConsole.ExtentUI.defaultCreateUI(this,a)},useToolingApiOnCreate:!0,
createEntity:function(a,b){var c=this;SfdcDevConsole.ToolingAPI.create(this.entityType,a,{continuation:function(d){d=Sfdc.apply(d,a);!d.NamespacePrefix&&SfdcDevConsole.namespace&&(d.NamespacePrefix=SfdcDevConsole.namespace);d.Id||(d.Id=d.id);c.cache&&c.cache.push(d);Sfdc.isFunction(c.afterCreate)&&c.afterCreate(d);SfdcDevConsole.Events.EventDispatcher.fire("extent:created",[c,d]);Sfdc.isFunction(b)&&b(d)},tooling:this.useToolingApiOnCreate,alertOnFailure:!0,gackOnFailure:!1})},findId:function(a,b,
c){this.getRecords(function(d){a:{for(var h=0;h<d.length;h++){var m=e.hasNamespace(d[h].NamespacePrefix,a),f=d[h].Name.toLowerCase()===b.toLowerCase();if(m&&f){d=d[h].Id;break a}}d=null}c(d)})},isId:function(a){return a.substring(0,3)===this.keyPrefix?!0:!1},clearItemFromCache:function(a){if(self.cache)for(var b=self.cache,c=0;c<b.length;c++)if(b[c].Id===a){self.cache=b.slice(0,c).concat(b.slice(c+1,b.length));break}},DELETE:function(a,b){var c=this;SfdcDevConsole.ToolingAPI.DELETE(this.entityType,
a,{success:function(d,h){c.clearItemFromCache(a);SfdcDevConsole.Events.EventDispatcher.fire("extent:deleted",[a]);Sfdc.isFunction(b)&&b()},alertOnFailure:!0,gackOnFailure:!1})},fields:null,cached:!1,loading:!1,continuations:[],_massageRows:function(a,b){b(a)},_loadData:function(a){function b(d,e){d.nextRecordsUrl?SfdcDevConsole.ToolingAPI.request({url:d.nextRecordsUrl,continuation:function(a){b(a,e.concat(a.records))}}):c._massageRows(e,a)}var c=this,d="SELECT Id, ",d=c.fields?d+c.fields.join(", "):
d+"Name, NamespacePrefix",d=d+(" FROM "+c.entityType);SfdcDevConsole.ToolingAPI.query(d,{continuation:function(a){b(a,a.records)},failure:function(b,d){SfdcDevConsole.ToolingAPI.handleFailedRequest(b,"Could not load "+c.displayName+" from Salesforce",!0);Sfdc.isFunction(a)&&a()}})},getRecords:function(a,b){function c(b){d.cache=b;d.cached=!0;d.loading=!1;for(var c=d.continuations.length;c--;)try{d.continuations[c](b)}catch(e){Sfdc.error(e)}d.continuations=[];Sfdc.isFunction(a)&&a(b)}var d=this;d.loading?
Sfdc.isFunction(a)&&d.continuations.push(a):d.cached&&!b?Sfdc.isFunction(a)&&a(d.cache):(d.loading=!0,delete d.cache,d.cached=!1,this._loadData(c))},isApiAccessible:function(){return!0},createBody:function(a,b,c){throw'Function "createBody" not implemented for type '+this.displayName;},has:function(a,b,c){return null!==this.get(a,b,function(a){Sfdc.isFunction(c)&&c(null!==a)})},get:function(a,b,c){var d=function(d){for(var e=0;e<d.length;e++)if(d[e][a]===b)return Sfdc.isFunction(c)&&c(d[e]),d[e];
return null};if(c&&!this.cache)this.getRecords(function(a){d(a)});else{if(this.cached)return d(this.cache);throw"No data cached from salesforce";}},load:function(a){SfdcDevConsole.ToolingAPI.sobject(this.entityType,a)},sourceField:"Body"});e.isExtent=function(a){return a instanceof f};e.ApexClass=new f({xtype:"apexeditor",keyPrefix:"01p",displayName:"Apex class",entityType:"ApexClass",memberType:"ApexClassMember",hasBody:!0,hasSymbols:!0,versionable:!0,contentField:"Body",useToolingApiOnCreate:!1,
getExtension:function(a){return"apxc"},isApiAccessible:function(){return apex.ide.IDE.authorApex},createBody:function(a,b){hierarchy=(a.Name=b.name)&&b.name.toLowerCase().endsWith("exception")?" extends Exception":"";a.Body="public class "+b.name+hierarchy+" {\n\n}\n"}});e.ApexTrigger=new f({xtype:"apexeditor",keyPrefix:"01q",displayName:"Trigger",entityType:"ApexTrigger",memberType:"ApexTriggerMember",hasBody:!0,hasSymbols:!0,versionable:!0,contentField:"Body",useToolingApiOnCreate:!1,getExtension:function(a){return"apxt"},
openCreateUI:function(a){SfdcDevConsole.ExtentUI.triggerCreateUI(this,a)},isApiAccessible:function(){return apex.ide.IDE.authorApex},createBody:function(a,b){a.Name=b.name;b.triggerType.endsWith("__e")||b.triggerType.endsWith("ChangeEvent")||"AssetTokenEvent"===b.triggerType||"MyS1BrokerNotification"===b.triggerType||"LogoutEventStream"===b.triggerType||"RevokeDevice"===b.triggerType||"RemoteKeyCalloutEvent"===b.triggerType||"BatchApexErrorEvent"===b.triggerType||"PlatformStatusAlertEvent"===b.triggerType?
a.Body="trigger "+b.name+" on "+b.triggerType+" (after insert) {\n\n}\n":a.Body="trigger "+b.name+" on "+b.triggerType+" (before insert) {\n\n}\n";a.TableEnumOrId=b.triggerType}});e.ApexPage=new f({xtype:"visualforceeditor",keyPrefix:"066",displayName:"Apex Page",entityType:"ApexPage",sourceField:"Markup",hasBody:!0,memberType:"ApexPageMember",versionable:!0,contentField:"Markup",getExtension:function(a){return"vfp"},isApiAccessible:function(){return apex.ide.IDE.hasVisualforce&&apex.ide.IDE.authorVisualforce},
createBody:function(a,b){a.Markup="\x3capex:page\x3e\n\x3c/apex:page\x3e";a.Name=b.name.replace(" ","_");a.MasterLabel=b.name}});e.ApexComponent=new f({xtype:"visualforceeditor",keyPrefix:"099",displayName:"Apex Page Component",sourceField:"Markup",entityType:"ApexComponent",hasBody:!0,memberType:"ApexComponentMember",versionable:!0,contentField:"Markup",getExtension:function(a){return"vfc"},isApiAccessible:function(){return apex.ide.IDE.hasVisualforce&&apex.ide.IDE.authorVisualforce},createBody:function(a,
b){a.Markup="\x3capex:component\x3e\n\x3c/apex:component\x3e";a.Name=b.name.replace(" ","_");a.MasterLabel=b.name}});var g=function(a,b){this.mode=a;this.extension=b},k=new g("javascript","js"),l=new g("xml","xml"),n=new g("text","txt"),p=new g("css","css"),g=new g("text/x-pig","pig");e.DataPipeline=new f({xtype:"datapipelineeditor",keyPrefix:"0NO",entityType:"DataPipeline",displayName:LC.getLabel("DataPipelineUI","DataPipelines"),fields:["MasterLabel","DeveloperName","ScriptContent","ScriptType"],
TEMPLATE_TYPES:{Sample:"-- Sample script for a data pipeline\nA \x3d load 'force://chatter/REPLACE_ME_CHATTER_ID' using gridforce.hadoop.pig.loadstore.func.ForceStorage();\nStore A  into 'force://chatter/REPLACE_ME_TOO' using gridforce.hadoop.pig.loadstore.func.ForceStorage();",ETL:"-- Template script for an ETL data pipeline\n-- load a File(Extract)\nmyJson \x3d load 'force://chatter/REPLACE_ME_CHATTER_ID' using gridforce.hadoop.pig.loadstore.func.ForceStorage() as (name,street,city,zip);\n-- Transform\ndata \x3d FILTER myJson by Zip \x3d\x3d '00000';\n --Store\nSTORE data INTO 'force://entity/Contact/fields/Name, MailingStreet, MailingPostalCode, MailingCity' USING gridforce.hadoop.pig.loadstore.func.ForceStorage();",
"Data Denorm":"-- Template script for data denorm data pipeline\n-- load sObjects\nACCOUNT \x3d LOAD 'force://soql/SELECT Id, Name,Description,ShippingCountry FROM Account' using gridforce.hadoop.pig.loadstore.func.ForceStorage() as (Id,Name,Description,ShippingCountry);\nOPPORTUNITY \x3d LOAD 'force://soql/SELECT AccountId, Name FROM Opportunity' using gridforce.hadoop.pig.loadstore.func.ForceStorage() as (AccountId,Name);\n-- join sObjects\naccntOpp \x3d JOIN ACCOUNT by Id FULL, OPPORTUNITY by AccountId;\n--Store denorm dataset into customObj\nSTORE accntOpp INTO 'force://chatter/denorm' USING gridforce.hadoop.pig.loadstore.func.ForceStorage();",
Metrics:"-- Template script for generating metrics/data crunching data pipeline\nmy_data \x3d LOAD 'force://soql/SELECT Id, Name,LeadSource,ReportsToId FROM Contact' using gridforce.hadoop.pig.loadstore.func.ForceStorage() as (Id,Name,LeadSource,ReportsToId);\nby_reportsTo_and_LeadSource \x3d GROUP my_data BY (ReportsToId, LeadSource);\nby_reportsTo_and_LeadSource_c \x3d FOREACH by_reportsTo_and_LeadSource GENERATE group.ReportsToId, group.LeadSource,COUNT(A);\nSTORE by_reportsTo_and_LeadSource_c INTO 'force://chatter/Age_And_Color' USING gridforce.hadoop.pig.loadstore.func.ForceStorage();"},
SCRIPT_TYPES:{pig:g},getExtension:function(a){return(a=this.SCRIPT_TYPES[(a.ScriptType||a.data.ScriptType).toLowerCase()])?a.extension:""},beforeOpen:function(a){var b=a.ScriptType.toLowerCase();if(!this.SCRIPT_TYPES[b]){var c=LC.getLabel("DataPipelineUI","BadScriptType1")+Object.keys(this.SCRIPT_TYPES).join(", ")+LC.getLabel("DataPipelineUI","BadScriptType2");return c+=LC.getLabel("DataPipelineUI","BadScriptType3")+a.Name+LC.getLabel("DataPipelineUI","BadScriptType4")+b}a.mode=this.SCRIPT_TYPES[b].mode},
createBody:function(a,b){var c=b.name.replace(" ","_");a.MasterLabel=c;a.DeveloperName=c;a.ScriptContent=this.TEMPLATE_TYPES[b.templateType];a.ScriptType=b.scriptType.toUpperCase();a.ApiVersion=SfdcDevConsole.ToolingAPI.version},openCreateUI:function(a){SfdcDevConsole.DataPipeline.openCreateUI(a)},isApiAccessible:function(){return apex.ide.IDE.dataPipelineDevConsole},_massageRows:function(a,b){for(var c=0;c<a.length;c++){var d=a[c];d.Name=d.DeveloperName}b(a)}});e.StaticResource=new f({xtype:"staticresourceeditor",
keyPrefix:"081",entityType:"StaticResource",displayName:"Static Resource",fields:["Name","NamespacePrefix","ContentType"],CONTENT_TYPES:{"application/javascript":k,"text/javascript":k,"application/xml":l,"text/xml":l,"text/css":p,"text/plain":n},getExtension:function(a){return(a=this.CONTENT_TYPES[(a.ContentType||a.data.ContentType).toLowerCase()])?a.extension:""},beforeOpen:function(a){var b=a.ContentType.toLowerCase();if(!this.CONTENT_TYPES[b]){var c="Only resources with a MIME Type of "+Object.keys(this.CONTENT_TYPES).join(", ")+
" can be opened. ";return c+="The resource "+a.Name+" has a MIME type of "+escapeHTML(b)+"."}a.mode=this.CONTENT_TYPES[b].mode},openCreateUI:function(a){SfdcDevConsole.StaticResource.openCreateUI(a)},createBody:function(a,b){Sfdc.apply(a,b);0<=b.ContentType.indexOf("javascript")?a.Body=btoa("function helloWorld() {\n\n}"):0<=b.ContentType.indexOf("css")?a.Body=btoa("h1 {\n    color : red;\n}\n\n#myClass {\n    color : blue;\n}"):a.Body=btoa("")},isApiAccessible:function(){return apex.ide.IDE.authorVisualforce},
load:function(a){a.body=!0;SfdcDevConsole.ToolingAPI.sobject(this.entityType,a)}});e.AuraDefinitionBundle=new f({xtype:"aurabundleeditor",keyPrefix:"0Ab",entityType:"AuraDefinitionBundle",displayName:"Lightning Bundle",fields:["DeveloperName","NamespacePrefix","ApiVersion","Description"],bundleMap:{},clearItemFromCache:function(a){var b=null;if(this.cache)for(var b=this.cache,c=0;c<b.length;c++)if(b[c].Id===a){this.cache=b.slice(0,c).concat(b.slice(c+1,b.length));break}this.bundleMap[a]&&delete this.bundleMap[a];
if(e.AuraDefinition.cache){for(var b=e.AuraDefinition.cache,d=[],c=0;c<b.length;c++)b[c].AuraDefinitionBundleId!==a&&d.push(b[c]);e.AuraDefinition.cache=d}},getDefinitions:function(a,b){if(Sfdc.isFunction(b)){var c=this;if(c.bundleMap[a])b(c.bundleMap[a]);else{var d="SELECT Id, "+e.AuraDefinition.fields.join(",")+" FROM "+e.AuraDefinition.entityType+" WHERE AuraDefinitionBundleiD \x3d '"+a+"'";SfdcDevConsole.ToolingAPI.query(d,{continuation:function(d){c.bundleMap[a]=d.records;b(c.bundleMap[a])}})}}},
create:function(a,b){SfdcDevConsole.ExtentUI.createEntity(this,a,b)},openCreateUI:function(a,b){SfdcDevConsole.Aura.openCreateUI(a,b)},createBody:function(a,b){a.MasterLabel=b.Name;a.DeveloperName=b.Name;a.ApiVersion=SfdcDevConsole.ToolingAPI.version;a.Description=b.Description||"A Lightning Component Bundle"},isApiAccessible:function(){return apex.ide.IDE.hasAura}});e.AuraDefinition=new f({xtype:"auraeditor",keyPrefix:"0Ad",entityType:"AuraDefinition",displayName:"Lightning",fields:["AuraDefinitionBundleId",
"AuraDefinitionBundle.DeveloperName","DefType","Format"],getExtension:function(a){return null},create:function(){throw"AuraDefinition can not be called from the UI. Call createEntitiy directly unless the UI is modified";},afterCreate:function(a){var b=e.AuraDefinitionBundle.bundleMap[a.AuraDefinitionBundleId];b&&b.push(a)},createBody:function(a,b){Sfdc.apply(a,{AuraDefinitionBundleId:b,DefType:"APPLICATION",Format:"XML",Source:"\x3caura:application\x3e\n\n\x3c/aura:application\x3e"})},isApiAccessible:function(){return apex.ide.IDE.hasAura},
_massageRows:function(a,b){for(var c=0;c<a.length;c++){var d=a[c];d.Name=SfdcDevConsole.Aura.getFileName(d)}b(a)},getDefinition:function(a,b,c){e.AuraDefinitionBundle.getDefinitions(a,function(a){for(var e=0;e<a.length;e++)if(a[e]&&a[e].DefType===b){c(a[e]);return}c(null)})}});e.SObject=new f({xtype:"entityinfoviewer",entityType:"SObject",displayName:"Object",getExtension:function(a){return"obj"},_loadData:function(a){SfdcDevConsole.ToolingAPI.sobject("",{tooling:!1,continuation:function(b){for(var c=
b.sobjects.length,d=0;d<c;d++){var e=b.sobjects[d],f=e.name,g=f.indexOf("__"),k=f.lastIndexOf("__");g!=k?(e.NamespacePrefix=f.substring(0,g),e.Name=f.substring(g+2)):(e.NamespacePrefix=null,e.Name=f)}a(b.sobjects)},failure:function(b,c){SfdcDevConsole.ToolingAPI.handleFailedRequest(b,"Could not load Objects from Salesforce",!0);Sfdc.isFunction(a)&&a()}})}});e.Package=new f({entityType:"Package",getExtension:function(a){return"pkg"},_loadData:function(a){Ext.Ajax.request({url:"/_ui/common/apex/debug/ApexCSIAPI",
params:{action:"EXTENT",extent:"PACKAGES"},success:function(b,c){var d=[];try{d=Util.evalAjaxServletOutput(b.responseText).PACKAGES.packages}finally{Sfdc.isFunction(a)&&a(d)}},failure:function(b,c){SfdcDevConsole.ToolingAPI.handleFailedRequest(b,"Could not load Packages from Salesforce",!0);Sfdc.isFunction(a)&&a()}})}});e.Workflow=new f({xtype:"xmleditor",keyPrefix:"01Q",displayName:"Workflow Rule",entityType:"WorkflowRule",memberType:"WorkflowRuleMember",useToolingApiOnCreate:!0,sourceField:"Metadata",
isApiAccessible:function(){return!0},open:null});SfdcDevConsole.Extents=e})();
SfdcDevConsole.Events.EventDispatcher.register("session:initialized");SfdcDevConsole.Events.EventDispatcher.register("session:refreshed");SfdcDevConsole.Events.EventDispatcher.register("session:expired");Sfdc.ns("SfdcDevConsole.Session");
(function(){function m(){SfdcDevConsole.ToolingAPI.request({url:"/_ui/common/apex/debug/ApexCSIAPI",data:{action:"KEEPALIVE"},alertOnFailure:!0,gackOnFailure:!1,success:function(c,d){var a=Util.evalAjaxServletOutput(c);a.success||(b&&(clearInterval(b),b=null),Ext.Msg.alert(LC.getLabel("DeveloperConsole","LoggingDisabledTitle"),LC.getLabel("DeveloperConsole","LoggingDisabledMsg")+" "+a.errorText))}})}function n(){Sfdc.cometd.getStatus&&"disconnected"!==Sfdc.cometd.getStatus()||(Sfdc.log("Streaming API initializing..."),
Sfdc.cometd.init({url:SfdcDevConsole.ToolingAPI.URLs.base+"/cometd/36.0",requestHeaders:{Authorization:"OAuth "+SfdcDevConsole.SID},appendMessageTypeToURL:!1}),p||(Sfdc.cometd.addListener("/meta/connect",function(c){if(!cometd.isDisconnected()){var b=f;f=message.successful;b||f||apex.ide.IDE.sendGack("Error connecting Streaming API "+JSON.stringify(c),Sfdc.Logging.LogLevel.GACK)}}),Sfdc.cometd.addListener("/meta/disconnect",SfdcDevConsole.Session,function(){f=!1;Sfdc.log("Streaming API disconnected");
g.isAlive()&&n()}),Sfdc.cometd.addListener("/meta/handshake",function(c){if(c.successful)Sfdc.cometd.subscribe("/systemTopic/Logging",function(a){apex.csi.LogBrowser.selectId=a&&a.data&&a.data.sobject&&a.data.sobject.Id;Ext.getCmp("traceGrid").getStore().load()}),Sfdc.cometd.subscribe("/systemTopic/ApexExecutionOverlayResult",function(a){Ext.getCmp("fewmetList").getStore().load()}),Sfdc.cometd.subscribe("/systemTopic/TestResult",function(a){apex.test.TestResultBrowser.loadTestResults();(a=Ext.getCmp("editors").getActiveTab())&&
("testresult"===a.xtype&&!a.loaded)&&a.refresh()}),apex.ide.IDE.dataPipelineDevConsole&&Sfdc.cometd.subscribe("/systemTopic/DataPipelineJob",function(a){a=a.data.sobject;Ext.getCmp("dataPipelineJobProgressPanel").loadJobProgress(a)}),Sfdc.cometd.subscribe("/systemTopic/ContainerDeployStateChange",function(a){apex.ide.Container.finishDeploy(a.data.sobject.Id)}),Sfdc.log("Streaming API connected");else{var b=c.advice&&"none"!==c.advice.reconnect;if(c.error||!b)Sfdc.log("Failed handshake with Streaming API"),
apex.ide.IDE.sendGack("Error establishing handshake with Streaming API "+JSON.stringify(c),Sfdc.Logging.LogLevel.GACK)}}),p=!0))}function q(){n();SfdcDevConsole.ToolingAPI.request({url:"/_ui/common/apex/debug/ApexCSIAPI",data:{action:"KEEPALIVE"},alertOnFailure:!0,gackOnFailure:!1,success:function(c,d){var a=Util.evalAjaxServletOutput(c);a.success?b||(b=setInterval(m,0.25*l)):Ext.Msg.alert(LC.getLabel("DeveloperConsole","LoggingDisabledTitle"),LC.getLabel("DeveloperConsole","LoggingDisabledMsg")+
" "+a.errorText)}});h=null;k=(new Date).getTime();d=!0;e=setTimeout(s,t*l)}function r(){d&&(k=null,d=!1,Sfdc.cometd.disconnect(),clearInterval(b),b=null,apex.ide.IDE.updateWorkspaceImpl())}function s(){var b=h&&k&&h>=k;e=null;b?(q(),Sfdc.log("Session refreshed"),SfdcDevConsole.Events.EventDispatcher.fire("session:refreshed")):(r(),Sfdc.log("Session expired"),SfdcDevConsole.Events.EventDispatcher.fire("session:expired"))}var t=20,l=6E4,d=!1,p=!1,k=null,h=null,e=null,g=null,f=!1,b=null,g={initialize:function(){d?
g.keepAlive():(q(),Sfdc.log("Session initialized"),SfdcDevConsole.Events.EventDispatcher.fire("session:initialized"))},expire:function(){Sfdc.isDefAndNotNull(e)&&(clearTimeout(e),e=null);r();SfdcDevConsole.Events.EventDispatcher.fire("session:expired")},keepAlive:function(){h=(new Date).getTime()},isAlive:function(){return d},changeLoggingStatus:function(c){!0===c?b||(b=setInterval(m,0.25*l)):b&&(clearInterval(b),b=null)}};SfdcDevConsole.Session=g})();
Sfdc.ns("SfdcDevConsole.Preferences");SfdcDevConsole.Events.EventDispatcher.register("preferences:save");SfdcDevConsole.Events.EventDispatcher.register("preferences:changed");
(function(){function m(a,b){for(var d in a)a.hasOwnProperty(d)&&!Sfdc.isFunction(a[d])&&b(d,a[d])}var l={},c={noLogsOnLoad:{label:LC.getLabel("DevConsolePrefs","noLogLoadTitle"),description:LC.getLabel("DevConsolePrefs","noLogLoadDesc"),defaultValue:!1,apiName:"PreventLogsonLoad",apiNumber:91},autocompleteApexAfterKeyPress:{label:LC.getLabel("DevConsolePrefs","autocompleteApexAfterKeyPressTitle"),description:LC.getLabel("DevConsolePrefs","autocompleteApexAfterKeyPressDesc"),defaultValue:!0,apiName:"AutocompleteApexAfterKeyPress",
apiNumber:92},visualforceViewstateInspector:{label:LC.getLabel("DevConsolePrefs","visualforceViewstateInspectorTitle"),description:LC.getLabel("DevConsolePrefs","visualforceViewstateInspectorDesc"),defaultValue:!0,apiName:"VisualforceViewstateInspector",apiNumber:93},cmTheme:{label:LC.getLabel("DevConsolePrefs","cmThemeTitle"),description:LC.getLabel("DevConsolePrefs","cmThemeDesc"),defaultValue:"default",apiName:"EditorTheme",apiNumber:96,values:function(){return SfdcDevConsole.Themes.getThemes()},
change:function(a,b){SfdcDevConsole.Themes.changeTheme(b)}},cmFontSize:{label:LC.getLabel("DevConsolePrefs","cmFontSizeTitle"),description:LC.getLabel("DevConsolePrefs","cmFontSizeDesc"),defaultValue:18,apiName:"EditorFontSize",apiNumber:97,change:function(a,b){SfdcDevConsole.Themes.changeFontSize(b)}},enableQueryPlan:{label:LC.getLabel("DevConsolePrefs","enableQueryPlanTitle"),description:LC.getLabel("DevConsolePrefs","enableQueryPlanDesc"),defaultValue:!1,apiName:"EnableQueryPlan",apiNumber:99},
pttrFormatWithTabs:{label:LC.getLabel("DevConsolePrefs","pttrFormatWithTabsTitle"),description:LC.getLabel("DevConsolePrefs","pttrFormatWithTabsDesc"),defaultValue:!1,apiName:"FormatWithTabs",apiNumber:111},pttrFormatTabWidth:{label:LC.getLabel("DevConsolePrefs","pttrFormatTabWidthTitle"),description:LC.getLabel("DevConsolePrefs","pttrFormatTabWidthDesc"),defaultValue:2,apiName:"FormatTabWidth",apiNumber:112},pttrFormatPrintWidth:{label:LC.getLabel("DevConsolePrefs","pttrFormatPrintWidthTitle"),description:LC.getLabel("DevConsolePrefs",
"pttrFormatPrintWidthDesc"),defaultValue:80,apiName:"FormatPrintWidth",apiNumber:113},each:function(a){m(c,a)},get:function(a){return Sfdc.isNumber(a)?c[l[a]]:c[a]},has:function(a){return Sfdc.isNumber(a)?!!l[a]:c.hasOwnProperty(a)&&!Sfdc.isFunction(c[a])}};c.each(function(a,b){if(!b.apiName||!b.apiNumber)throw"All preferences must have the preference api name and number";l[b.apiNumber]=a});var p=!1,f={},r=function(a){var b={};c.each(function(d,c){b[d]=a[d]||c.defaultValue});p=!0;SfdcDevConsole.Events.EventDispatcher.fire("preferences:changed",
[b])};SfdcDevConsole.Events.EventDispatcher.on("preferences:save",function(a,b){var d={url:SfdcDevConsole.ToolingAPI.URLs.sobject("User",!1,SfdcDevConsole.myUserId),method:"PUT"},h=null;m(b,function(a,b){var e=!f[a]&&c.get(a).defaultValue!==b||Sfdc.isDefAndNotNull(f[a])&&f[a]!==b;c.has(a)&&e&&(h||(h={}),f[a]=b,h[a]=b,e=Sfdc.apply({data:b+""},d),e.url+="/"+c.get(a).apiName,SfdcDevConsole.ToolingAPI.request(e))});h&&SfdcDevConsole.Events.EventDispatcher.fire("preferences:changed",[h])});var q={get:function(a){if(!p)throw"The preferences are not loaded!";
return Sfdc.isDefAndNotNull(f[a])?f[a]:c[a]&&c[a].defaultValue},load:function(a){var b={};c.each(function(a,c){b[a]=c.defaultValue});SfdcDevConsole.ToolingAPI.query("SELECT Preference, Value FROM UserPreference WHERE UserID \x3d '"+SfdcDevConsole.myUserId+"'",{continuation:function(a){for(var h={},n=0;n<a.records.length;n++)try{var k=a.records[n],e=k.Preference,g=k.Value;if(isNaN(parseInt(e,0)))throw"Preference field is not a number: found Preference "+e+" with Value "+g;e=parseInt(e,0);c.has(e)&&
("true"===g?g=!0:"false"===g?g=!1:isNaN(g-0)||(g-=0),c.get(e),f[l[e]]=g)}catch(m){h=b}r(h)},failure:function(a){SfdcDevConsole.Events.EventDispatcher.fire("preferences:update",[b]);SfdcDevConsole.ToolingAPI.handleFailedRequest(a,"Unable to create preferences")}})},getPreferenceInfo:function(a){var b=Sfdc.isString(a),d=b?null:[];c.each(function(c,f){var k=Sfdc.apply({name:c,value:q.get(c)},f);b?a===c&&(d=k):d.push(k)});return d}};SfdcDevConsole.Preferences=q})();
Sfdc.ns("SfdcDevConsole");SfdcDevConsole.Events.EventDispatcher.register("devconsole:loaded");
(function(){var g=!1,e=!1,h=0,l=0,k={},f=new Sfdc.Class({$constructor:function(a,c){h++;if(Sfdc.isFunction(a))this.startFn=a;else throw"StartupTask must have a start function";Sfdc.apply(this,c,!0)},start:function(){try{this.loading=!0;var a=this;this.timeoutId=setTimeout(function(){a.loading&&a.finish()},1E4);this.startFn()}catch(c){Sfdc.error("Failed during a startup task "+c),this.finish()}},finish:function(a,c){this.loading&&(this.loading=!1,clearTimeout(this.timeoutId),a&&(k[a]=c),++l===h&&(g=
!0,e=!1,SfdcDevConsole.Events.EventDispatcher.fire("devconsole:loaded",[k])))}}),d=[];d.push(new f(function(){Sfdc.log("Loading config...");var a=this;SfdcDevConsole.ToolingAPI.request({url:"/_ui/common/apex/debug/ApexCSIAPI",data:{action:"CONFIG"},success:function(c,d){var b={};try{Sfdc.log("Loaded config..."),b=Util.evalAjaxServletOutput(c),SfdcDevConsole.namespace=b.namespace,Sfdc.apply(apex.ide.IDE,b),Sfdc.apply(apex.ide.IDE,{showUpdatesFromTime:b.startTime,category:b.categoryMap})}finally{a.finish("config",
b)}},failure:function(c){a.finish();SfdcDevConsole.ToolingAPI.handleFailedRequest(c,"Error loading the Developer Console configuration",!0)}})}));d.push(new f(function(){function a(b){SfdcDevConsole.ToolingAPI.query("SELECT Id FROM IDEWorkspace WHERE UserId \x3d '"+Sfdc.UserContext.userId+"' AND Name \x3d 'Default'",{continuation:function(a){a&&a.records&&0<a.records.length?b(a.records[0].Id):b(null)},failure:function(){b(null)}})}function c(a){apex.ide.IDE.workspaceId=a;d.finish("workspaceId",a)}
Sfdc.log("Loading workspace...");var d=this;SfdcDevConsole.ToolingAPI.sobject("User",{id:Sfdc.UserContext.userId,continuation:function(b){b&&b.WorkspaceId&&0<b.WorkspaceId.length?c(b.WorkspaceId):a(c)},failure:function(a){d.finish()}})}));d.push(new f(function(){var a=this;SfdcDevConsole.Events.EventDispatcher.once("preferences:changed",function(c){a.finish("preferences",c)});SfdcDevConsole.Preferences.load()}));SfdcDevConsole.load=function(){if(g)throw"The Developer Console has already loaded";e||
(e=!0,Sfdc.Array.forEach(d,function(a){a.start()}))}})();

//# sourceMappingURL=/javascript/1568710058000/sfdc/source/ApexIDECore.js.map
