/*
 * This code is for Internal Salesforce use only, and subject to change without notice.
 * Customers shouldn't reference this file in any web pages.
 */
Sfdc.ns("SfdcDevConsole.Aura");
(function(){function h(a){return a.reduce(function(a,c){for(var d in c)if(c.hasOwnProperty(d))switch(d){case "access":case "extends":a[d]=c[d];break;case "implements":a[d]=(a[d]?a[d]+",":"")+c[d]}return a},{})}function k(a,b){var c=h(b),d="",e;for(e in c)c.hasOwnProperty(e)&&(d+=e+'\x3d"'+c[e]+'" ');return a.replace("##ATTRIBUTES##",d)}function e(a){g.create(function(b,c){g.getRecords(function(){SfdcDevConsole.Aura.createAndOpenDefinition(b,{DefType:SfdcDevConsole.Aura.DefTypes.getTypeName(a),Source:k(a.template,
c.Attributes||[])})})},a)}var g=SfdcDevConsole.Extents.AuraDefinitionBundle,f=SfdcDevConsole.Extents.AuraDefinition;SfdcDevConsole.Aura.createAndOpenDefinition=function(a,b){f.createBody(b,a);f.createEntity(b,function(a){SfdcDevConsole.ToolingAPI.sobject(f.entityType,{id:a.id,continuation:function(a){f.open(a)}})})};SfdcDevConsole.Aura.createApplication=function(){e(SfdcDevConsole.Aura.DefTypes.APPLICATION)};SfdcDevConsole.Aura.createComponent=function(){e(SfdcDevConsole.Aura.DefTypes.COMPONENT)};
SfdcDevConsole.Aura.createInterface=function(){e(SfdcDevConsole.Aura.DefTypes.INTERFACE)};SfdcDevConsole.Aura.createEvent=function(){e(SfdcDevConsole.Aura.DefTypes.EVENT)};SfdcDevConsole.Aura.createTokens=function(){e(SfdcDevConsole.Aura.DefTypes.TOKENS)};SfdcDevConsole.Aura.getFileName=function(a){var b=a.DeveloperName||a.AuraDefinitionBundle&&a.AuraDefinitionBundle.DeveloperName||"",c=SfdcDevConsole.Aura.DefTypes[a.DefType].extension,d=a.Format.toLowerCase();return b=c?b+("."+c):"STYLE"===a.DefType?
b+("."+d):b+(Sfdc.String.capitalize(a.DefType.toLowerCase())+"."+d)};SfdcDevConsole.Aura.getAuraComponents=function(a){Sfdc.isFunction(a)&&g.getRecords(function(b){f.getRecords(function(c){a(b,c)})})};SfdcDevConsole.Aura.DefTypes={APPLICATION:{format:"XML",template:"\x3caura:application ##ATTRIBUTES##\x3e\n\t\n\x3c/aura:application\x3e",extension:"app",locationsTitle:LC.getLabel("AuraUI","AttrUIApplicationTitle"),locationsInfoLabel:LC.getLabel("AuraUI","AttrUIApplicationInfo"),locations:[{label:LC.getLabel("AuraUI",
"AttrUIOutApp"),attributes:{"extends":"ltng:outApp"}}]},COMPONENT:{format:"XML",template:"\x3caura:component ##ATTRIBUTES##\x3e\n\t\n\x3c/aura:component\x3e",extension:"cmp",locationsTitle:LC.getLabel("AuraUI","AttrUIComponentTitle"),locationsInfoLabel:LC.getLabel("AuraUI","AttrUIComponentInfo"),locations:[{label:LC.getLabel("AuraUI","AttrUIAppHostable"),attributes:{"implements":"force:appHostable"}},{label:LC.getLabel("AuraUI","AttrUIAvailableForAllPageTypes"),attributes:{"implements":"flexipage:availableForAllPageTypes",
access:"global"}},{label:LC.getLabel("AuraUI","AttrUIAvailableForRecordHome"),attributes:{"implements":"flexipage:availableForRecordHome,force:hasRecordId",access:"global"}},{label:LC.getLabel("AuraUI","AttrUICommunityAvailableForAllPageTypes"),attributes:{"implements":"forceCommunity:availableForAllPageTypes",access:"global"}},{label:LC.getLabel("AuraUI","AttrUILightningQuickAction"),attributes:{"implements":"force:lightningQuickAction"}}]},CONTROLLER:{format:"JS",template:"({\n\tmyAction : function(component, event, helper) {\n\t\t\n\t}\n})"},
EVENT:{format:"XML",template:'\x3caura:event type\x3d"APPLICATION" description\x3d"Event template" /\x3e',extension:"evt"},TOKENS:{format:"XML",template:"\x3caura:tokens\x3e\n\t\n\x3c/aura:tokens\x3e",extension:"tokens"},HELPER:{format:"JS",template:"({\n\thelperMethod : function() {\n\t\t\n\t}\n})"},INTERFACE:{format:"XML",template:'\x3caura:interface description\x3d"Interface template"\x3e\n\t\x3caura:attribute name\x3d"example" type\x3d"String" default\x3d"" description\x3d"An example attribute."/\x3e\n\x3c/aura:interface\x3e',
extension:"intf"},STYLE:{format:"CSS",template:".THIS {\n}"},DOCUMENTATION:{format:"XML",template:'\x3caura:documentation\x3e\n\t\x3caura:description\x3eDocumentation\x3c/aura:description\x3e\n\t\x3caura:example name\x3d"ExampleName" ref\x3d"exampleComponentName" label\x3d"Label"\x3e\n\t\tExample Description\n\t\x3c/aura:example\x3e\n\x3c/aura:documentation\x3e',extension:"auradoc"},RENDERER:{format:"JS",template:"({\n\t// Your renderer method overrides go here\n})"},DESIGN:{format:"XML",template:"\x3cdesign:component\x3e\n\t\n\x3c/design:component\x3e",
extension:"design"},SVG:{format:"SVG",template:'\x3c?xml version\x3d"1.0" encoding\x3d"UTF-8" standalone\x3d"no"?\x3e\n\x3csvg width\x3d"120px" height\x3d"120px" viewBox\x3d"0 0 120 120" version\x3d"1.1" xmlns\x3d"http://www.w3.org/2000/svg" xmlns:xlink\x3d"http://www.w3.org/1999/xlink"\x3e\n\t\x3cg stroke\x3d"none" stroke-width\x3d"1" fill\x3d"none" fill-rule\x3d"evenodd"\x3e\n\t\t\x3cpath d\x3d"M120,108 C120,114.6 114.6,120 108,120 L12,120 C5.4,120 0,114.6 0,108 L0,12 C0,5.4 5.4,0 12,0 L108,0 C114.6,0 120,5.4 120,12 L120,108 L120,108 Z" id\x3d"Shape" fill\x3d"#2A739E"/\x3e\n\t\t\x3cpath d\x3d"M77.7383308,20 L61.1640113,20 L44.7300055,63.2000173 L56.0543288,63.2000173 L40,99.623291 L72.7458388,54.5871812 L60.907727,54.5871812 L77.7383308,20 Z" id\x3d"Path-1" fill\x3d"#FFFFFF"/\x3e\n\t\x3c/g\x3e\n\x3c/svg\x3e',
extension:"svg"},each:function(a){for(var b in this)this.hasOwnProperty(b)&&!Sfdc.isFunction(this[b])&&a(b,this[b])},isApp:function(a){return this[a]===this.APPLICATION},isCmp:function(a){return this[a]===this.COMPONENT},isInterface:function(a){return this[a]===this.INTERFACE},isEvent:function(a){return this[a]===this.EVENT},isTokens:function(a){return this[a]===this.TOKENS},getTypeName:function(a){var b=null;this.each(function(c,d){d===a&&(b=c)});return b}}})();
Sfdc.ns("SfdcDevConsole.Aura");
(function(){function k(a){null===c&&(d=Ext.create("Ext.Button",{text:"Submit",cls:"selTest-submitButton"}),e=Ext.create("Ext.form.field.Text",{name:"text",fieldLabel:"Name",labelWidth:100,margin:"5px 15px;",width:460}),g=Ext.create("Ext.form.field.TextArea",{name:"text",height:100,labelWidth:100,fieldLabel:"Description",margin:"5px 15px",width:460}),b=Ext.create("Ext.form.FieldSet",{title:"",width:460,margin:"0 0 0 15",defaultType:"checkbox",items:[],hidden:!0}),c=Ext.create("Ext.window.Window",{title:LC.getLabel("AuraUI",
"CreateUITitle"),height:200,width:500,closeAction:"hide",items:[e,g,b],buttons:[d]}));b.removeAll();f=[];a&&a.locations&&a.locations.length?(b.setTitle(a.locationsTitle),b.add(Ext.create("Ext.form.Label",{text:a.locationsInfoLabel})),Sfdc.each(a.locations,function(a){f.push(Ext.create("Ext.form.field.Checkbox",{boxLabel:a.label,inputValue:a.attributes,autoDestroy:!0}))}),b.add(f),b.hidden=!1,c.setHeight(400)):(b.hidden=!0,c.setHeight(200));return c}var c=null,d=null,e=null,g=null,b=null,f=null;SfdcDevConsole.Aura.openCreateUI=
function(a,b){var c=k(b);c.show();d.setHandler(function(){var d=e.getValue();if(b!=SfdcDevConsole.Aura.DefTypes.TOKENS&&"defaulttokens"==d.toLowerCase())Ext.Msg.alert("Error","Only Lightning Tokens can be named 'defaultTokens'.");else{var h=[];Sfdc.each(f,function(a){a.getSubmitValue()&&h.push(a.getSubmitValue())});a({Name:e.getValue(),Description:g.getValue(),Attributes:h})}c.hide()})}})();
Sfdc.ns("SfdcDevConsole.Aura");Ext.define("Aura.Open.Model",{extend:"Ext.data.Model",fields:[{name:"Id",type:"string"},{name:"NamespacePrefix",type:"string"},{name:"DeveloperName",type:"string"},{name:"Name",type:"string"},{name:"DefType",type:"string"},{name:"Format",type:"string"}]});Ext.define("Aura.Open.Store",{extend:"Ext.data.TreeStore",model:"Aura.Open.Model",proxy:{type:"memory"}});
Ext.define("Aura.Open.Tree",{alias:"widget.auraopentree",extend:"Ext.tree.Panel",region:"center",useArrows:!0,rootVisible:!1,multiSelect:!0,columns:[{xtype:"treecolumn",header:"Name",flex:2,sortable:!0,dataIndex:"Name"},{header:"Format",flex:1,dataIndex:"Format",sortable:!1}]});
(function(){function e(a,b){if(a.isId(b)){var f=a.get("Id",b);if(f)return a.open(f),!0}return!1}function m(a){var b=[];Sfdc.Array.forEach(a,function(a){var d=a.data.Id;!e(SfdcDevConsole.Extents.AuraDefinitionBundle,d)&&!e(SfdcDevConsole.Extents.AuraDefinition,d)&&b.push(a.data)});return b}function n(a){var b={text:".",expand:!0,children:[]},f={};SfdcDevConsole.Aura.getAuraComponents(function(d,c){Sfdc.Array.forEach(d,function(a){var k=Sfdc.apply({Name:(a.NamespacePrefix||"c")+":"+a.DeveloperName,
children:[]},a);f[a.Id]=k.children;b.children.push(k)});Sfdc.Array.forEach(c,function(a){var b=Sfdc.apply({leaf:!0,Name:a.DefType},a);f[a.AuraDefinitionBundleId].push(b)});Sfdc.isFunction(a)&&a(b)})}var l=Ext.create("Aura.Open.Store",{root:{text:".",expand:!0,children:[]}}),g=Ext.create("Aura.Open.Store"),p={text:LC.getLabel("DeveloperConsole","OpenSelectedButton"),listeners:{click:function(a){var b=c.openTree.getSelectionModel().getSelection();a=LC.getLabel("DeveloperConsole","OpenErrorTitle");b&&
0<b.length?(b=m(b),c.close(),0<b.length&&Ext.Msg.alert(a,"Failed to open "+b.length+" Aura items")):Ext.Msg.alert(a,LC.getLabel("DeveloperConsole","OpenErrorNothingSelected"))}}},q={xtype:"textfield",id:"filterTextField",width:200,enableKeyEvents:!0,emptyText:LC.getLabel("DeveloperConsole","Filter"),listeners:{keyup:function(a){Ext.suspendLayouts();try{var b=a.getValue(),c=g.getRootNode(),d=l.getRootNode(),e=[],h=[];d.eachChild(function(a){0<=a.data.DeveloperName.indexOf(b)&&e.push(a)});c.eachChild(function(a){0>
a.data.DeveloperName.indexOf(b)&&h.push(a)});Sfdc.Array.forEach(e,function(a){c.appendChild(a)});Sfdc.Array.forEach(h,function(a){d.appendChild(a)});g.sort()}finally{Ext.resumeLayouts(!0)}}}},c=Ext.create("Ext.window.Window",{title:LC.getLabel("AuraUI","OpenAuraTitle"),layout:"border",width:400,height:500,bbar:[p,q],listeners:{afterrender:function(a){a.openTree=a.items.get(0)},show:function(a){a.setLoading(!0);n(function(b){g.setRootNode(b);l.setRootNode({text:".",expand:!0,children:[]});Ext.getCmp("filterTextField").setValue("");
a.setLoading(!1)})}},items:[{xtype:"auraopentree",store:g}],closeAction:"hide"});Sfdc.onload(function(){new Ext.util.KeyMap(Ext.getBody(),[{ctrl:!0,shift:!0,key:"A",fn:function(){c.isHidden()?c.show():c.hide()},defaultEventAction:"stopEvent"}])});SfdcDevConsole.Aura.OpenWindow=c})();
Ext.define("aura.editor.AuraActionModel",{extend:"Ext.data.Model",fields:"key type name action extension format template".split(" "),idProperty:"type"});Ext.define("aura.editor.AuraActionStore",{extend:"Ext.data.Store",model:"aura.editor.AuraActionModel"});
(function(){function k(a){var b=a&&(a.AuraDefinitionBundleId||a.id);if(!b)throw"Invalid bundle id "+b;var c=l[b];c||(c=Ext.create("aura.editor.AuraSidebar",{region:"east",title:a.DeveloperName?a.DeveloperName:"Lightning Components",width:a.actionWidth||250,animCollapse:!1,collapseMode:"mini",collapsed:a.actionCollapsed,bundleId:b,editor:a}),l[b]=c);return c}function n(a,b){var c=b.data.type;SfdcDevConsole.Extents.AuraDefinition.getDefinition(a,c,function(d){d?SfdcDevConsole.Extents.AuraDefinition.open(Sfdc.apply(d,
{xtype:"auraeditor"})):SfdcDevConsole.Aura.createAndOpenDefinition(a,{DefType:c.toUpperCase(),Source:b.data.template,Format:b.data.format})})}function p(a,b){SfdcDevConsole.Events.EventDispatcher.fire("problems:clear");for(var c=JSON.parse(a),d=[],e=0;e<c.length;e++){var f=c[e].message;if(f&&f.startsWith("ESLINT_ERROR:")){var g=f.split("--\x3e",2);if(g&&1<g.length){f={};if(b)f.fullName=b;else{var h=g[0].match(/\{(.*?)\}/);h&&1<h.length&&(f.fullName=h[1])}if((h=g[0].match(/\[(\d+?):(\d+?)\]/))&&1<
h.length)f.lineNumber=h[1];g=g[1];g=g.replace(/:[^:]+$/,"");f.problem=g;d[e]=f}}}0<d.length&&SfdcDevConsole.Events.EventDispatcher.fire("problems:new",[d])}function q(a){for(var b=+SfdcDevConsole.ToolingAPI.version,c=b-5,d=[];b>=c;b--)d.push(b.toFixed(1));-1==d.indexOf(a.toFixed(1))&&d.unshift(a.toFixed(1));return d}function r(a,b){var c=Ext.getCmp("editors").getActiveTab();if(c&&c instanceof apex.editor.AuraEditor){var c=k(c),d=c.actions.store.getAt(a-s);d&&n(c.bundleId,d)}}var l={};Ext.define("aura.sidebar.PreviewButton",
{extend:"Ext.panel.Panel",cls:"viewButton",height:35,initComponent:function(){this.refresh();this.callParent();Ext.EventManager.onWindowUnload(this.closePreview,this)},refresh:function(){var a=LC.getLabel("AuraUI","Preview");this.updatedOn&&(a=LC.getLabel("AuraUI","UpdatePreview"),this.updatedOn.toLocaleString&&(a+="\x3cbr /\x3e\x3csmall\x3e"+LC.getLabel("AuraUI","PreviewUpdatedOn",this.updatedOn.toLocaleString())+"\x3c/small\x3e"));this.update(a)},isOpen:function(){return!(!this.previewWindow||this.previewWindow.closed)},
updateIfOpen:function(){this.isOpen()&&this.preview()},preview:function(a){var b=SfdcDevConsole.ToolingAPI.URLs.base,b=b+("/"+(this.getNamespace()||Aotp.MY_NS)),b=b+("/"+this.getName()+this.getExtension());this.isOpen()?this.previewWindow.location=b:this.previewWindow=window.open(b);this.updatedOn=new Date;this.refresh();a&&this.previewWindow.focus()},closePreview:function(){this.isOpen()&&this.previewWindow.close()},listeners:{afterrender:function(a){a.el.on("click",function(){this.preview(!0)},
a);a.el.on("mouseover",function(){a.el.dom.style.background="#cfe5ed"});a.el.on("mouseout",function(){a.el.dom.style.background="#b6d1da"})},destroy:function(a){Ext.EventManager.removeUnloadListener(a.closePreview,a);a.closePreview()}}});Ext.define("aura.sidebar.VersionSettingsButton",{extend:"Ext.panel.Panel",cls:"viewButton",height:25,initComponent:function(){var a=LC.getLabel("AuraUI","VersionSettings");this.update(a);this.callParent();Ext.EventManager.onWindowUnload(this.closeVersionSettings,
this)},isOpen:function(){return!(!this.versionSettingsWindow||!this.versionSettingsWindow.isVisible())},openVersionSettings:function(a){if(!this.isOpen()){editor=this.ownerCt.ownerCt;metadata=editor.metadata;var b="aurabundleeditor"===editor.xtype?editor.getId():editor.AuraDefinitionBundleId,c=!1,d=!1,e=[],f=[],g=[],h=this,k=function(){h.versionSettingsWindow=h.getVersionSettingsWindow();h.versionSettingsWindow.editor=editor;if(g.length>=e.length)for(var b=0;b<g.length;b++)0>f.indexOf(g[b].name)&&
e.push(g[b]);h.versionSettingsWindow.loadData(e);h.versionSettingsWindow.show();a&&h.versionSettingsWindow.focus()};SfdcDevConsole.ToolingAPI.query("SELECT ApiVersion,Metadata FROM AuraDefinitionBundle WHERE id \x3d'"+b+"'",{continuation:function(a){var b=a.records[0].ApiVersion;e.push({name:"API Version",type:"number",value:b,versions:q(b)});a=a.records[0].Metadata.packageVersions;for(b=0;b<a.length;b++)f.push(a[b].namespace),e.push({id:a[b].namespace,name:a[b].namespace,type:"number",value:a[b].majorNumber+
"."+a[b].minorNumber});d=!0;c&&k()}});SfdcDevConsole.ToolingAPI.query("SELECT NamespacePrefix,MajorVersion,MinorVersion FROM Publisher WHERE IsSalesforce\x3dfalse",{continuation:function(a){for(var b=0;b<a.records.length;b++)packageVersion=a.records[b],"\x3clocal\x3e"!=packageVersion.NamespacePrefix&&g.push({id:packageVersion.NamespacePrefix,name:packageVersion.NamespacePrefix,type:"number",value:packageVersion.MajorVersion+"."+packageVersion.MinorVersion+" ("+LC.getLabel("AuraUI","NotYetDefined")+
")"});c=!0;d&&k()}})}},closeVersionSettings:function(){this.isOpen()&&this.versionSettingsWindow.close()},listeners:{afterrender:function(a){a.el.on("click",function(){this.openVersionSettings(!0)},a);a.el.on("mouseover",function(){a.el.dom.style.background="#cfe5ed"});a.el.on("mouseout",function(){a.el.dom.style.background="#b6d1da"})},destroy:function(a){Ext.EventManager.removeUnloadListener(a.closeVersionSettings,a);a.closeVersionSettings()}},getVersionSettingsWindow:function(){return Ext.create("Ext.window.Window",
{xtype:window,title:LC.getLabel("AuraUI","VersionSettings"),height:200,width:400,layout:"fit",bbar:[{xtype:"tbfill"},{text:LC.getLabel("DeveloperConsole","SaveButton"),handler:function(){function a(a,b){SfdcDevConsole.ToolingAPI.save("AuraDefinitionBundle",a,{success:function(){SfdcDevConsole.Events.EventDispatcher.fire("problems:clear");b.ownerCt.ownerCt.close()},failure:function(a){p(a);SfdcDevConsole.ToolingAPI.handleFailedRequest(a,"Failed to save "+c.clsName,!0,!0)}})}var b=this.ownerCt.ownerCt.items.get(0).store.data;
if(b.items){var c=this,d={};d.id=void 0===editor.AuraDefinitionBundleId?editor.id:editor.AuraDefinitionBundleId;var e={};e.apiVersion=b.items[0].data.value;e.packageVersions=this.ownerCt.ownerCt.createPackageVersions(b);d.Metadata=e;a(d,this)}}},{text:LC.getLabel("DeveloperConsole","CancelButton"),handler:function(){this.ownerCt.ownerCt.close()}}],closeAction:"close",loadData:function(a){this.items.get(0).store.loadData(a)},createPackageVersions:function(a){for(var b=[],c=1;c<a.items.length;c++){var d=
a.items[c].data.value;if(d){var e=d.toString(),f=e.indexOf("."),d=0<f?e.substring(0,f):e,g=e.indexOf("("),e=0<f?0<g?e.substring(f+1,g):e.substring(f+1):"0",f=a.items[c].data.name;0>g&&b.push({majorNumber:d,minorNumber:e,namespace:f})}}return b},items:{xtype:"versionsettings"}})}});Ext.define("aura.editor.AuraSidebar",{extend:"Ext.panel.Panel",title:"",forceFit:!0,collapsible:!0,split:!0,cls:"AuraSideBar",initComponent:function(){var a=Ext.create("aura.sidebar.PreviewButton",{getNamespace:this.getNamespace.bind(this),
getName:this.getName.bind(this),getExtension:this.getExtension.bind(this),hidden:!0}),b=Ext.create("aura.sidebar.VersionSettingsButton"),c=Ext.create("aura.sidebar.AuraActions",{bundleId:this.bundleId});Ext.apply(this,{items:[a,c,b]});this.actions=c;this.preview=a;this.versionSettings=b;this.callParent()},refreshView:function(a){this.actions.refreshView(a,function(){this.actions.isApp&&this.preview.show();this.versionSettings.show()}.bind(this))},getNamespace:function(){var a=this.NamespacePrefix||
this.editor.NamespacePrefix;if(!a&&SfdcDevConsole.Extents.AuraDefinitionBundle.cachedData){var b=SfdcDevConsole.Extents.AuraDefinitionBundle.get("Id",this.bundleId);b&&(a=b.NamespacePrefix)}a||(a=SfdcDevConsole.namespace);return a},getName:function(){return this.editor.DeveloperName},isApp:function(){return this.actions.isApp},isCmp:function(){return this.actions.isCmp},getExtension:function(){var a;a=this.isApp()?".app":null;return a=this.isCmp()?".cmp":a},listeners:{beforedestroy:function(a){delete l[a.bundleId];
return!0},resize:function(a){a.doLayout()}}});Ext.define("aura.sidebar.AuraActions",{extend:"Ext.grid.Panel",forceFit:!0,cls:"AuraActionSideBar",columns:[{name:"Key",dataIndex:"key",width:70},{name:"Name",dataIndex:"name"},{name:"Action",dataIndex:"action",width:50}],initComponent:function(){Ext.apply(this,{store:Ext.create("aura.editor.AuraActionStore",{bundleId:this.bundleId})});this.callParent()},ignoreDefinitionType:function(a){var b=SfdcDevConsole.Aura.DefTypes;return this.isInterface&&a!==b.INTERFACE||
this.isEvent&&a!==b.EVENT||this.isTokens&&a!==b.TOKENS||a===b.APPLICATION&&!this.isApp||a===b.COMPONENT&&!this.isCmp||a===b.INTERFACE&&!this.isInterface||a===b.EVENT&&!this.isEvent||a===b.TOKENS&&!this.isTokens||a===b.DESIGN&&!this.isCmp},initializeStore:function(a){var b=this.getStore();if(!(0===a.length||b.initialized)){var c=0;a=function(a,e){if(!this.ignoreDefinitionType(e)){var f=Sfdc.apply({},e);f.key="Ctrl + Shift + "+ ++c;f.name=a;f.type=a;b.add(f)}}.bind(this);SfdcDevConsole.Aura.DefTypes.each(a);
b.initialized=!0}},setActiveDefinitionType:function(a,b){this.getView().getRowClass=function(c,d,e,f){c=c.data.type.toUpperCase();return a===c?"auraCmpActive":b[c]?"auraCmpExist":""}},refreshDefinitionActions:function(a){SfdcDevConsole.Aura.DefTypes.each(function(b,c){var d=this.getStore().getById(b);d&&(a[b]?d.set("action",""):d.set("action","Create"))}.bind(this))},refreshView:function(a,b){SfdcDevConsole.Extents.AuraDefinitionBundle.getDefinitions(this.bundleId,function(c){var d={};Sfdc.Array.forEach(c,
function(a){d[a.DefType]=!0});this.isApp=!!d.APPLICATION;this.isCmp=!!d.COMPONENT;this.isInterface=!!d.INTERFACE;this.isEvent=!!d.EVENT;this.isTokens=!!d.TOKENS;this.initializeStore(c);this.setActiveDefinitionType(a,d);this.refreshDefinitionActions(d);this.getView().refresh();Sfdc.isFunction(b)&&b(c)}.bind(this))},listeners:{itemclick:function(a,b,c,d,e){n(a.ownerCt.bundleId,b)}}});var m=function(a){var b=k(a);if(!a.items.contains(b)){a.add(b);if(b.splitter)b.splitter.on("afterrender",function(){b.splitter.el.selectable();
b.splitter.un(arguments.callee)});b.refreshView(a.DefType);setTimeout(function(){a.doLayout();a.cmEditor&&a.cmEditor.codeEditor.refresh()},20)}},s=49;Ext.onReady(function(){var a=new Ext.util.KeyMap(Ext.getBody(),[{key:"0123456789",ctrl:!0,shift:!0,fn:r,defaultEventAction:"stopEvent"}]);Sfdc.Test&&(SfdcDevConsole.Aura.keymap=a)});Ext.define("apex.editor.AuraBundleEditor",{alias:"widget.aurabundleeditor",extend:"apex.ide.Editor",layout:"border",loaded:!1,workspace:function(){var a=k(this);return Ext.apply(this.callParent(),
{DeveloperName:this.DeveloperName,Description:this.Description,actionWidth:a.width,actionCollapsed:a.collapsed})},canEdit:function(){return!0},initComponent:function(){this.Name=this.DeveloperName;this.callParent()},listeners:{show:m,afterrender:m},performSave:function(a,b){},getItems:function(){var a=this.callParent(),b="";this.Description&&(b=document.createElement("div"),b.textContent=this.Description,b.innerText=this.Description,b=b.innerHTML);b="\x3cb\x3eDescription\x3c/b\x3e"+("\x3cp\x3e"+b+
"\x3c/p\x3e")+"\x3chr\x3e";b+="\x3ci\x3eNavigate to the bundle's definitions in the action bar to the right.\x3ci\x3e";a.push({xtype:"panel",region:"center",cls:"AuraBundleBody",html:b});return a},loadContent:function(){this.fireEvent("afterLoad",null)}});Ext.define("apex.editor.AuraEditor",{alias:"widget.auraeditor",extend:"apex.editor.SourceFileEditor",layout:"border",loaded:!1,canEdit:function(){return apex.ide.IDE.hasAura},removeEditor:function(a,b,c){for(var d=c.items.items.length,e=0,f=0;f<
d;f++)if((b=c.items.items[e])&&b.DeveloperName&&a==b.DeveloperName)try{c.remove(b)}catch(g){Ext.Msg.alert("Error",g.message)}else e++},deleteBundleMapItem:function(){var a=this.AuraDefinitionBundleId,b=SfdcDevConsole.Extents.getExtentFromId(a),c=b.bundleMap[a],d=c.length;for(i=0;i<d;i++)if(c[i]&&this.DefType===c[i].DefType){delete b.bundleMap[a][i];break}},checkEssentialElement:function(){return"COMPONENT"==this.DefType||"APPLICATION"==this.DefType||"INTERFACE"==this.DefType||"EVENT"==this.DefType||
"TOKENS"==this.DefType},DELETE:function(){var a=Ext.getCmp("editors"),b=a.getActiveTab();if(this.canDelete()){var c=this.id,d=this,e=this.AuraDefinitionBundleId,f=SfdcDevConsole.Extents.getExtentFromId(e),g=LC.getLabel("DeveloperConsole","DeletionMsgEssentialType",this.DefType.toLowerCase());d.checkEssentialElement()?Ext.Msg.confirm("Confirm",g,function(c){"yes"===c&&(d.removeEditor(d.DeveloperName,b,a),f.DELETE(e,function(){apex.test.TestResult.updateClassesAndTriggers()}))}):Ext.Msg.confirm("Confirm",
LC.getLabel("DeveloperConsole","DeletionMsgNonEssentialType",this.Name),function(b,e){"yes"===b&&(a.remove(d),SfdcDevConsole.Extents.getExtentFromId(c).DELETE(c,function(){apex.test.TestResult.updateClassesAndTriggers();d.deleteBundleMapItem();var b=a.getActiveTab();k(b).refreshView(b.DefType)}))})}},initBody:function(a){this.setValue(a.Source||"");this.clearHistory()},workspace:function(){var a=k(this);return Ext.apply(this.callParent(),{name:this.name,AuraDefinitionBundleId:this.AuraDefinitionBundleId,
DefType:this.DefType,Format:this.Format,NamespacePrefix:this.NamespacePrefix,DeveloperName:this.DeveloperName,actionWidth:a.width,actionCollapsed:a.collapsed})},getFileName:function(){return SfdcDevConsole.Aura.getFileName(this)},initComponent:function(){if(!this.DeveloperName){var a=this,b=SfdcDevConsole.Extents.AuraDefinitionBundle.get("Id",this.AuraDefinitionBundleId,function(c){if(!b){a.DeveloperName=c.DeveloperName;var d=a.getFileName();a.Name=d;a.setTitle(d);a.NamespacePrefix=c.NamespacePrefix}});
this.DeveloperName=b&&b.DeveloperName||"";this.NamespacePrefix=b&&b.NamespacePrefix||""}this.Name=this.getFileName();this.mode=this.Format.toLowerCase();"js"===this.mode&&(this.mode="javascript");this.callParent()},listeners:{show:m,afterrender:m},performSave:function(a,b){var c=this;SfdcDevConsole.ToolingAPI.save("AuraDefinition",{id:this.id,Source:a},{success:function(){k(c).preview.updateIfOpen();SfdcDevConsole.Events.EventDispatcher.fire("problems:clear");b()},failure:function(a){p(a,c.Name);
SfdcDevConsole.ToolingAPI.handleFailedRequest(a,"Failed to save "+c.Name,!0,!0);b(!0)}})}});Sfdc.Test&&(SfdcDevConsole.Aura.sidebars=l)})();

//# sourceMappingURL=/javascript/1568710058000/sfdc/source/ApexIDEAura.js.map
