/*
 * This code is for Internal Salesforce use only, and subject to change without notice.
 * Customers shouldn't reference this file in any web pages.
 */
this.org=this.org||{};org.cometd={};org.cometd.JSON={};org.cometd.JSON.toJSON=org.cometd.JSON.fromJSON=function(b){throw"Abstract";};org.cometd.Utils={};org.cometd.Utils.isString=function(b){return void 0===b||null===b?!1:"string"===typeof b||b instanceof String};org.cometd.Utils.isArray=function(b){return void 0===b||null===b?!1:b instanceof Array};org.cometd.Utils.inArray=function(b,a){for(var c=0;c<a.length;++c)if(b===a[c])return c;return-1};
org.cometd.Utils.setTimeout=function(b,a,c){return window.setTimeout(function(){try{a()}catch(c){b._debug("Exception invoking timed function",a,c)}},c)};org.cometd.Utils.clearTimeout=function(b){window.clearTimeout(b)};
org.cometd.TransportRegistry=function(){var b=[],a={};this.getTransportTypes=function(){return b.slice(0)};this.findTransportTypes=function(c,g,l){for(var e=[],f=0;f<b.length;++f){var k=b[f];!0===a[k].accept(c,g,l)&&e.push(k)}return e};this.negotiateTransport=function(c,g,l,e){for(var f=0;f<b.length;++f)for(var k=b[f],p=0;p<c.length;++p)if(k===c[p]){var m=a[k];if(!0===m.accept(g,l,e))return m}return null};this.add=function(c,g,l){for(var e=!1,f=0;f<b.length;++f)if(b[f]===c){e=!0;break}e||("number"!==
typeof l?b.push(c):b.splice(l,0,c),a[c]=g);return!e};this.find=function(c){for(var g=0;g<b.length;++g)if(b[g]===c)return a[c];return null};this.remove=function(c){for(var g=0;g<b.length;++g)if(b[g]===c)return b.splice(g,1),g=a[c],delete a[c],g;return null};this.clear=function(){b=[];a={}};this.reset=function(){for(var c=0;c<b.length;++c)a[b[c]].reset()}};
org.cometd.Transport=function(){var b,a;this.registered=function(c,g){b=c;a=g};this.unregistered=function(){a=b=null};this._debug=function(){a._debug.apply(a,arguments)};this._mixin=function(){return a._mixin.apply(a,arguments)};this.getConfiguration=function(){return a.getConfiguration()};this.getAdvice=function(){return a.getAdvice()};this.setTimeout=function(c,g){return org.cometd.Utils.setTimeout(a,c,g)};this.clearTimeout=function(c){org.cometd.Utils.clearTimeout(c)};this.convertToMessages=function(c){if(org.cometd.Utils.isString(c))try{return org.cometd.JSON.fromJSON(c)}catch(a){throw this._debug("Could not convert to JSON the following string",
'"'+c+'"'),a;}if(org.cometd.Utils.isArray(c))return c;if(void 0===c||null===c)return[];if(c instanceof Object)return[c];throw"Conversion Error "+c+", typeof "+typeof c;};this.accept=function(c,a,b){throw"Abstract";};this.getType=function(){return b};this.send=function(c,a){throw"Abstract";};this.reset=function(){this._debug("Transport",b,"reset")};this.abort=function(){this._debug("Transport",b,"aborted")};this.toString=function(){return this.getType()}};
org.cometd.Transport.derive=function(b){function a(){}a.prototype=b;return new a};
org.cometd.RequestTransport=function(){function b(h){for(;0<m.length;){var c=m[0],a=c[0],c=c[1];if(a.url===h.url&&a.sync===h.sync)m.shift(),h.messages=h.messages.concat(a.messages),this._debug("Coalesced",a.messages.length,"messages from request",c.id);else break}}function a(c,a){this.transportSend(c,a);a.expired=!1;if(!c.sync){var b=this.getConfiguration().maxNetworkDelay,e=b;!0===a.metaConnect&&(e+=this.getAdvice().timeout);this._debug("Transport",this.getType(),"waiting at most",e,"ms for the response, maxNetworkDelay",
b);var g=this;a.timeout=this.setTimeout(function(){a.expired=!0;a.xhr&&a.xhr.abort();var b="Request "+a.id+" of transport "+g.getType()+" exceeded "+e+" ms max network delay";g._debug(b);g.complete(a,!1,a.metaConnect);c.onFailure(a.xhr,c.messages,"timeout",b)},e)}}function c(c){var b=++f,e={id:b,metaConnect:!1};p.length<this.getConfiguration().maxConnections-1?(p.push(e),a.call(this,c,e)):(this._debug("Transport",this.getType(),"queueing request",b,"envelope",c),m.push([c,e]))}function g(a,e){var g=
org.cometd.Utils.inArray(a,p);0<=g&&p.splice(g,1);if(0<m.length){var g=m.shift(),l=g[0],y=g[1];this._debug("Transport dequeued request",y.id);if(e)this.getConfiguration().autoBatch&&b.call(this,l),c.call(this,l),this._debug("Transport completed request",a.id,l);else{var I=this;this.setTimeout(function(){I.complete(y,!1,y.metaConnect);l.onFailure(y.xhr,l.messages,"error","Previous request failed")},0)}}}var l=new org.cometd.Transport,e=org.cometd.Transport.derive(l),f=0,k=null,p=[],m=[];e.complete=
function(c,a,e){if(e){c=c.id;this._debug("Transport",this.getType(),"metaConnect complete, request",c);if(null!==k&&k.id!==c)throw"Longpoll request mismatch, completing request "+c;k=null}else g.call(this,c,a)};e.transportSend=function(c,a){throw"Abstract";};e.transportSuccess=function(c,a,e){if(!a.expired)if(this.clearTimeout(a.timeout),this.complete(a,!0,a.metaConnect),e&&0<e.length)c.onSuccess(e);else c.onFailure(a.xhr,c.messages,"Empty HTTP response")};e.transportFailure=function(c,a,e,b){a.expired||
(this.clearTimeout(a.timeout),this.complete(a,!1,a.metaConnect),c.onFailure(a.xhr,c.messages,e,b))};e.send=function(e,b){if(b){if(null!==k)throw"Concurrent metaConnect requests not allowed, request id\x3d"+k.id+" not yet completed";var g=++f;this._debug("Transport",this.getType(),"metaConnect send, request",g,"envelope",e);g={id:g,metaConnect:!0};a.call(this,e,g);k=g}else c.call(this,e)};e.abort=function(){l.abort();for(var c=0;c<p.length;++c){var a=p[c];this._debug("Aborting request",a);a.xhr&&a.xhr.abort()}k&&
(this._debug("Aborting metaConnect request",k),k.xhr&&k.xhr.abort());this.reset()};e.reset=function(){l.reset();k=null;p=[];m=[]};return e};
org.cometd.LongPollingTransport=function(){var b=new org.cometd.RequestTransport,a=org.cometd.Transport.derive(b),c=!0;a.accept=function(a,b,e){return c||!b};a.xhrSend=function(c){throw"Abstract";};a.transportSend=function(a,b){this._debug("Transport",this.getType(),"sending request",b.id,"envelope",a);var e=this;try{var f=!0;b.xhr=this.xhrSend({transport:this,url:a.url,sync:a.sync,headers:this.getConfiguration().requestHeaders,body:org.cometd.JSON.toJSON(a.messages),onSuccess:function(f){e._debug("Transport",
e.getType(),"received response",f);var m=!1;try{var h=e.convertToMessages(f);0===h.length?(c=!1,e.transportFailure(a,b,"no response",null)):(m=!0,e.transportSuccess(a,b,h))}catch(k){e._debug(k),m||(c=!1,e.transportFailure(a,b,"bad response",k))}},onError:function(k,m){c=!1;f?e.setTimeout(function(){e.transportFailure(a,b,k,m)},0):e.transportFailure(a,b,k,m)}});f=!1}catch(k){c=!1,this.setTimeout(function(){e.transportFailure(a,b,"error",k)},0)}};a.reset=function(){b.reset();c=!0};return a};
org.cometd.CallbackPollingTransport=function(){var b=new org.cometd.RequestTransport,b=org.cometd.Transport.derive(b);b.accept=function(a,c,b){return!0};b.jsonpSend=function(a){throw"Abstract";};b.transportSend=function(a,c){for(var b=this,l=0,e=a.messages.length,f=[];0<e;){var k=org.cometd.JSON.toJSON(a.messages.slice(l,l+e)),k=a.url.length+encodeURI(k).length;if(2E3<k){if(1===e){var p="Bayeux message too big ("+k+" bytes, max is 2000) for transport "+this.getType();this.setTimeout(function(){b.transportFailure(a,
c,"error",p)},0);return}--e}else f.push(e),l+=e,e=a.messages.length-l}var m=a;if(1<f.length){l=0;e=f[0];this._debug("Transport",this.getType(),"split",a.messages.length,"messages into",f.join(" + "));m=this._mixin(!1,{},a);m.messages=a.messages.slice(l,e);m.onSuccess=a.onSuccess;m.onFailure=a.onFailure;for(k=1;k<f.length;++k){var h=this._mixin(!1,{},a),l=e,e=e+f[k];h.messages=a.messages.slice(l,e);h.onSuccess=a.onSuccess;h.onFailure=a.onFailure;this.send(h,c.metaConnect)}}this._debug("Transport",
this.getType(),"sending request",c.id,"envelope",m);try{var r=!0;this.jsonpSend({transport:this,url:m.url,sync:m.sync,headers:this.getConfiguration().requestHeaders,body:org.cometd.JSON.toJSON(m.messages),onSuccess:function(a){var e=!1;try{var h=b.convertToMessages(a);0===h.length?b.transportFailure(m,c,"no response"):(e=!0,b.transportSuccess(m,c,h))}catch(f){b._debug(f),e||b.transportFailure(m,c,"bad response",f)}},onError:function(a,e){r?b.setTimeout(function(){b.transportFailure(m,c,a,e)},0):b.transportFailure(m,
c,a,e)}});r=!1}catch(w){this.setTimeout(function(){b.transportFailure(m,c,"error",w)},0)}};return b};
org.cometd.WebSocketTransport=function(){function b(){var a=e.getURL().replace(/^http/,"ws");this._debug("Transport",this.getType(),"connecting to URL",a);var c=this,b=null,g=e.getConfiguration().connectTimeout;0<g&&(b=this.setTimeout(function(){b=null;r||(c._debug("Transport",c.getType(),"timed out while connecting to URL",a,":",g,"ms"),c.onClose(1002,"Connect Timeout"))},g));var f=new org.cometd.WebSocket(a);f.onopen=function(){c._debug("WebSocket opened",f);b&&(c.clearTimeout(b),b=null);if(f!==
h)c._debug("Ignoring open event, WebSocket",h);else c.onOpen()};f.onclose=function(a){var e=a?a.code:1E3;a=a?a.reason:void 0;c._debug("WebSocket closed",e,"/",a,f);b&&(c.clearTimeout(b),b=null);if(f!==h)c._debug("Ignoring close event, WebSocket",h);else c.onClose(e,a)};f.onerror=function(){f.onclose({code:1002})};f.onmessage=function(a){c._debug("WebSocket message",a,f);if(f!==h)c._debug("Ignoring message event, WebSocket",h);else c.onMessage(a)};h=f;this._debug("Transport",this.getType(),"configured callbacks on",
f)}function a(a,c){var b=org.cometd.JSON.toJSON(a.messages);h.send(b);this._debug("Transport",this.getType(),"sent",a,"metaConnect \x3d",c);var e=b=this.getConfiguration().maxNetworkDelay;c&&(e+=this.getAdvice().timeout,w=!0);for(var f=[],g=0;g<a.messages.length;++g){var k=a.messages[g];k.id&&(f.push(k.id),m[k.id]=this.setTimeout(function(){h&&h.close(1E3,"Timeout")},e))}this._debug("Transport",this.getType(),"waiting at most",e,"ms for messages",f,"maxNetworkDelay",b,", timeouts:",m)}function c(c,
e){try{null===h?b.call(this):r&&a.call(this,c,e)}catch(f){this.setTimeout(function(){c.onFailure(h,c.messages,"error",f)},0)}}var g=new org.cometd.Transport,l=org.cometd.Transport.derive(g),e,f=!0,k=!1,p={},m={},h=null,r=!1,w=!1,x;l.onOpen=function(){this._debug("Transport",this.getType(),"opened",h);k=r=!0;this._debug("Sending pending messages",p);for(var c in p){var b=p[c],e=b[0],b=b[1];x=e.onSuccess;a.call(this,e,b)}};l.onMessage=function(c){this._debug("Transport",this.getType(),"received websocket message",
c,h);var a=!1;c=this.convertToMessages(c.data);for(var b=[],e=0;e<c.length;++e){var f=c[e];if((/^\/meta\//.test(f.channel)||void 0===f.data)&&f.id){b.push(f.id);var g=m[f.id];g&&(this.clearTimeout(g),delete m[f.id],this._debug("Transport",this.getType(),"removed timeout for message",f.id,", timeouts",m))}"/meta/connect"===f.channel&&(w=!1);"/meta/disconnect"===f.channel&&!w&&(a=!0)}e=!1;for(f=0;f<b.length;++f){var k=b[f],l;for(l in p){var g=l.split(","),r=org.cometd.Utils.inArray(k,g);if(0<=r){e=
!0;g.splice(r,1);k=p[l][0];r=p[l][1];delete p[l];0<g.length&&(p[g.join(",")]=[k,r]);break}}}e&&this._debug("Transport",this.getType(),"removed envelope, envelopes",p);x.call(this,c);a&&h.close(1E3,"Disconnect")};l.onClose=function(c,a){this._debug("Transport",this.getType(),"closed",c,a,h);f=k;for(var b in m)this.clearTimeout(m[b]);m={};for(var e in p)b=p[e][0],p[e][1]&&(w=!1),b.onFailure(h,b.messages,"closed "+c+"/"+a);p={};null!==h&&r&&h.close(1E3,"Close");r=!1;h=null};l.registered=function(c,a){g.registered(c,
a);e=a};l.accept=function(c,a,b){return f&&!!org.cometd.WebSocket&&!1!==e.websocketEnabled};l.send=function(a,b){this._debug("Transport",this.getType(),"sending",a,"metaConnect \x3d",b);for(var e=[],f=0;f<a.messages.length;++f){var g=a.messages[f];g.id&&e.push(g.id)}p[e.join(",")]=[a,b];this._debug("Transport",this.getType(),"stored envelope, envelopes",p);c.call(this,a,b)};l.abort=function(){g.abort();if(null!==h)try{h.close(1001)}catch(a){this._debug(a)}this.reset()};l.reset=function(){g.reset();
null!==h&&r&&h.close(1E3,"Reset");f=!0;k=!1;m={};p={};h=null;r=!1;x=null};return l};
org.cometd.Cometd=function(b){function a(d){return org.cometd.Utils.isString(d)}function c(d){return void 0===d||null===d?!1:"function"===typeof d}function g(d,a){if(window.console){var b=window.console[d];c(b)&&b.apply(window.console,a)}}function l(){for(var d in A)for(var a=A[d],c=0;c<a.length;++c){var b=a[c];b&&!b.listener&&(delete a[c],n._debug("Removed subscription",b,"for channel",d))}}function e(d){D!==d&&(n._debug("Status",D,"-\x3e",d),D=d)}function f(){return"disconnecting"===D||"disconnected"===
D}function k(d,a,b,e,f){try{return a.call(d,e)}catch(g){n._debug("Exception during execution of extension",b,g);d=n.onExtensionException;if(c(d)){n._debug("Invoking extension exception callback",b,g);try{d.call(n,g,b,f,e)}catch(h){n._info("Exception during execution of exception callback in extension",b,h)}}return e}}function p(d){for(var a=0;a<t.length&&!(void 0===d||null===d);++a){var b=t[a],e=b.extension.outgoing;c(e)&&(b=k(b.extension,e,b.name,d,!0),d=void 0===b?d:b)}return d}function m(d,a){var b=
A[d];if(b&&0<b.length)for(var e=0;e<b.length;++e){var f=b[e];if(f)try{f.callback.call(f.scope,a)}catch(g){n._debug("Exception during notification",f,a,g);var h=n.onListenerException;if(c(h)){n._debug("Invoking listener exception callback",f,g);try{h.call(n,g,f.handle,f.listener,a)}catch(k){n._info("Exception during execution of listener callback",f,k)}}}}}function h(d,a){m(d,a);for(var c=d.split("/"),b=c.length-1,e=b;0<e;--e){var f=c.slice(0,e).join("/")+"/*";e===b&&m(f,a);f+="*";m(f,a)}}function r(){null!==
J&&org.cometd.Utils.clearTimeout(J);J=null}function w(d){r();var a=u.interval+s;n._debug("Function scheduled in",a,"ms, interval \x3d",u.interval,"backoff \x3d",s,d);J=org.cometd.Utils.setTimeout(n,d,a)}function x(d,a,b,e){for(var f=0;f<a.length;++f){var g=a[f];g.id=""+ ++ea;E&&(g.clientId=E);var h=void 0;c(g._callback)&&(h=g._callback,delete g._callback);g=p(g);void 0!==g&&null!==g?(a[f]=g,h&&(M[g.id]=h)):a.splice(f--,1)}0!==a.length&&(f=q.url,q.appendMessageTypeToURL&&(f.match(/\/$/)||(f+="/"),
e&&(f+=e)),d={url:f,sync:d,messages:a,onSuccess:function(d){try{V.call(n,d)}catch(a){n._debug("Exception during handling of messages",a)}},onFailure:function(d,a,c,b){try{N.call(n,d,a,c,b)}catch(e){n._debug("Exception during handling of failure",e)}}},n._debug("Send",d),z.send(d,b))}function y(d){0<B||!0===G?F.push(d):x(!1,[d],!1)}function I(){var d=F;F=[];0<d.length&&x(!1,d,!1)}function K(){e("connecting");w(function(){if(!f()){var d={channel:"/meta/connect",connectionType:z.getType()};O||(d.advice=
{timeout:0});e("connecting");n._debug("Connect sent",d);x(!1,[d],!0,"connect");e("connected")}})}function L(d){d&&(u=n._mixin(!1,{},q.advice,d),n._debug("New advice",u))}function C(d){r();d&&z.abort();E=null;e("disconnected");s=B=0;0<F.length&&(N.call(n,void 0,F,"error","Disconnected"),F=[])}function R(d){E=null;l();f()?(v.reset(),L(q.advice)):L(n._mixin(!1,u,{reconnect:"retry"}));B=0;G=!0;P=d;d=v.findTransportTypes("1.0",H,q.url);var a=n._mixin(!1,{},P,{version:"1.0",minimumVersion:"0.9",channel:"/meta/handshake",
supportedConnectionTypes:d,advice:{timeout:u.timeout,interval:u.interval}});z=v.negotiateTransport(d,"1.0",H,q.url);n._debug("Initial transport is",z.getType());e("handshaking");n._debug("Handshake sent",a);x(!1,[a],!1,"handshake")}function S(){e("handshaking");G=!0;w(function(){R(P)})}function T(d){h("/meta/handshake",d);h("/meta/unsuccessful",d);!f()&&"none"!==u.reconnect?(s<q.maxBackoff&&(s+=q.backoffIncrement),S()):C(!1)}function U(d){h("/meta/connect",d);h("/meta/unsuccessful",d);d=f()?"none":
u.reconnect;switch(d){case "retry":K();s<q.maxBackoff&&(s+=q.backoffIncrement);break;case "handshake":v.reset();s=0;S();break;case "none":C(!1);break;default:throw"Unrecognized advice action"+d;}}function W(d){C(!0);h("/meta/disconnect",d);h("/meta/unsuccessful",d)}function X(d){h("/meta/subscribe",d);h("/meta/unsuccessful",d)}function Y(d){h("/meta/unsubscribe",d);h("/meta/unsuccessful",d)}function Z(d){var a=M[d.id];c(a)&&(delete M[d.id],a.call(n,d))}function $(d){Z(d);h("/meta/publish",d);h("/meta/unsuccessful",
d)}function aa(d){for(var a=0;a<t.length&&!(void 0===d||null===d);++a){var b=t[q.reverseIncomingExtensions?t.length-1-a:a],e=b.extension.incoming;c(e)&&(b=k(b.extension,e,b.name,d,!1),d=void 0===b?d:b)}if(!(void 0===d||null===d))switch(L(d.advice),d.channel){case "/meta/handshake":if(d.successful){E=d.clientId;a=v.negotiateTransport(d.supportedConnectionTypes,d.version,H,q.url);if(null===a)throw"Could not negotiate transport with server; client "+v.findTransportTypes(d.version,H,q.url)+", server "+
d.supportedConnectionTypes;z!==a&&(n._debug("Transport",z,"-\x3e",a),z=a);G=!1;I();d.reestablish=Q;Q=!0;h("/meta/handshake",d);d=f()?"none":u.reconnect;switch(d){case "retry":s=0;K();break;case "none":C(!1);break;default:throw"Unrecognized advice action "+d;}}else T(d);break;case "/meta/connect":if(O=d.successful)switch(h("/meta/connect",d),d=f()?"none":u.reconnect,d){case "retry":s=0;K();break;case "none":C(!1);break;default:throw"Unrecognized advice action "+d;}else U(d);break;case "/meta/disconnect":d.successful?
(C(!1),h("/meta/disconnect",d)):W(d);break;case "/meta/subscribe":d.successful?h("/meta/subscribe",d):X(d);break;case "/meta/unsubscribe":d.successful?h("/meta/unsubscribe",d):Y(d);break;default:void 0===d.successful?d.data?h(d.channel,d):n._debug("Unknown message",d):d.successful?(Z(d),h("/meta/publish",d)):$(d)}}function ba(d){if(d=A[d])for(var a=0;a<d.length;++a)if(d[a])return!0;return!1}function ca(d,b){var e={scope:d,method:b};if(c(d))e.scope=void 0,e.method=d;else if(a(b)){if(!d)throw"Invalid scope "+
d;e.method=d[b];if(!c(e.method))throw"Invalid callback "+b+" for scope "+d;}else if(!c(b))throw"Invalid callback "+b;return e}function da(d,a,b,c){a=ca(a,b);n._debug("Adding listener on",d,"with scope",a.scope,"and callback",a.method);c={channel:d,scope:a.scope,callback:a.method,listener:c};a=A[d];a||(a=[],A[d]=a);a=a.push(c)-1;c.id=a;c.handle=[d,a];n._debug("Added listener",c,"for channel",d,"having id \x3d",a);return c.handle}var n=this,fa=b||"default",H=!1,v=new org.cometd.TransportRegistry,z,
D="disconnected",ea=0,E=null,B=0,F=[],G=!1,A={},s=0,J=null,t=[],u={},P,M={},Q=!1,O=!1,q={connectTimeout:0,maxConnections:2,backoffIncrement:1E3,maxBackoff:6E4,logLevel:"info",reverseIncomingExtensions:!0,maxNetworkDelay:1E4,requestHeaders:{},appendMessageTypeToURL:!0,autoBatch:!1,advice:{timeout:6E4,interval:0,reconnect:"retry"}};this._mixin=function(d,a,c){for(var b=a||{},e=2;e<arguments.length;++e){var f=arguments[e];if(!(void 0===f||null===f))for(var g in f){var h=f[g],k=b[g];h!==a&&void 0!==h&&
(b[g]=d&&"object"===typeof h&&null!==h?h instanceof Array?this._mixin(d,k instanceof Array?k:[],h):this._mixin(d,"object"===typeof k&&!(k instanceof Array)?k:{},h):h)}}return b};this._warn=function(){g("warn",arguments)};this._info=function(){"warn"!==q.logLevel&&g("info",arguments)};this._debug=function(){"debug"===q.logLevel&&g("debug",arguments)};this._isCrossDomain=function(d){return d&&d!==window.location.host};var V,N;this.send=y;this.receive=aa;V=function(d){n._debug("Received",d);for(var a=
0;a<d.length;++a)aa(d[a])};N=function(d,a,c,b){n._debug("handleFailure",d,a,c,b);for(c=0;c<a.length;++c){var e=a[c];switch(e.channel){case "/meta/handshake":T({successful:!1,failure:!0,channel:"/meta/handshake",request:e,xhr:d,advice:{reconnect:"retry",interval:s}});break;case "/meta/connect":b=d;O=!1;U({successful:!1,failure:!0,channel:"/meta/connect",request:e,xhr:b,advice:{reconnect:"retry",interval:s}});break;case "/meta/disconnect":W({successful:!1,failure:!0,channel:"/meta/disconnect",request:e,
xhr:d,advice:{reconnect:"none",interval:0}});break;case "/meta/subscribe":X({successful:!1,failure:!0,channel:"/meta/subscribe",request:e,xhr:d,advice:{reconnect:"none",interval:0}});break;case "/meta/unsubscribe":Y({successful:!1,failure:!0,channel:"/meta/unsubscribe",request:e,xhr:d,advice:{reconnect:"none",interval:0}});break;default:$({successful:!1,failure:!0,channel:e.channel,request:e,xhr:d,advice:{reconnect:"none",interval:0}})}}};this.registerTransport=function(d,a,b){if(b=v.add(d,a,b))this._debug("Registered transport",
d),c(a.registered)&&a.registered(d,this);return b};this.getTransportTypes=function(){return v.getTransportTypes()};this.unregisterTransport=function(a){var b=v.remove(a);null!==b&&(this._debug("Unregistered transport",a),c(b.unregistered)&&b.unregistered());return b};this.unregisterTransports=function(){v.clear()};this.findTransport=function(a){return v.find(a)};this.configure=function(d){n._debug("Configuring cometd object with",d);a(d)&&(d={url:d});d||(d={});q=n._mixin(!1,q,d);if(!q.url)throw"Missing required configuration parameter 'url' specifying the Bayeux server URL";
var b=/(^https?:\/\/)?(((\[[^\]]+\])|([^:\/\?#]+))(:(\d+))?)?([^\?#]*)(.*)?/.exec(q.url);d=b[8];var c=b[9];H=n._isCrossDomain(b[2]);q.appendMessageTypeToURL&&(void 0!==c&&0<c.length?(n._info("Appending message type to URI "+d+c+" is not supported, disabling 'appendMessageTypeToURL' configuration"),q.appendMessageTypeToURL=!1):(b=d.split("/"),c=b.length-1,d.match(/\/$/)&&(c-=1),0<=b[c].indexOf(".")&&(n._info("Appending message type to URI "+d+" is not supported, disabling 'appendMessageTypeToURL' configuration"),
q.appendMessageTypeToURL=!1)))};this.init=function(a,b){this.configure(a);this.handshake(b)};this.handshake=function(a){e("disconnected");Q=!1;R(a)};this.disconnect=function(a,b){if(!f()){void 0===b&&"boolean"!==typeof a&&(b=a,a=!1);var c=this._mixin(!1,{},b,{channel:"/meta/disconnect"});e("disconnecting");x(!0===a,[c],!1,"disconnect")}};this.startBatch=function(){++B};this.endBatch=function(){--B;if(0>B)throw"Calls to startBatch() and endBatch() are not paired";0===B&&(!f()&&!G)&&I()};this.batch=
function(a,b){var c=ca(a,b);this.startBatch();try{c.method.call(c.scope),this.endBatch()}catch(e){throw this._debug("Exception during execution of batch",e),this.endBatch(),e;}};this.addListener=function(d,b,c){if(2>arguments.length)throw"Illegal arguments number: required 2, got "+arguments.length;if(!a(d))throw"Illegal argument type: channel must be a string";return da(d,b,c,!0)};this.removeListener=function(a){if(!org.cometd.Utils.isArray(a))throw"Invalid argument: expected subscription, not "+
a;var b=A[a[0]];b&&(delete b[a[1]],n._debug("Removed listener",a))};this.clearListeners=function(){A={}};this.subscribe=function(d,b,e,g){if(2>arguments.length)throw"Illegal arguments number: required 2, got "+arguments.length;if(!a(d))throw"Illegal argument type: channel must be a string";if(f())throw"Illegal state: already disconnected";c(b)&&(g=e,e=b,b=void 0);var h=!ba(d),k=da(d,b,e,!1);h&&(h=this._mixin(!1,{},g,{channel:"/meta/subscribe",subscription:d}),y(h));return k};this.unsubscribe=function(a,
b){if(1>arguments.length)throw"Illegal arguments number: required 1, got "+arguments.length;if(f())throw"Illegal state: already disconnected";this.removeListener(a);var c=a[0];ba(c)||(c=this._mixin(!1,{},b,{channel:"/meta/unsubscribe",subscription:c}),y(c))};this.clearSubscriptions=function(){l()};this.publish=function(d,b,e,g){if(1>arguments.length)throw"Illegal arguments number: required 1, got "+arguments.length;if(!a(d))throw"Illegal argument type: channel must be a string";if(f())throw"Illegal state: already disconnected";
c(b)?(g=b,b=e={}):c(e)&&(g=e,e={});var h=this._mixin(!1,{},e,{channel:d,data:b,_callback:g});y(h)};this.getStatus=function(){return D};this.isDisconnected=f;this.setBackoffIncrement=function(a){q.backoffIncrement=a};this.getBackoffIncrement=function(){return q.backoffIncrement};this.getBackoffPeriod=function(){return s};this.setLogLevel=function(a){q.logLevel=a};this.registerExtension=function(b,e){if(2>arguments.length)throw"Illegal arguments number: required 2, got "+arguments.length;if(!a(b))throw"Illegal argument type: extension name must be a string";
for(var f=!1,g=0;g<t.length;++g)if(t[g].name===b){f=!0;break}if(f)return this._info("Could not register extension with name",b,"since another extension with the same name already exists"),!1;t.push({name:b,extension:e});this._debug("Registered extension",b);c(e.registered)&&e.registered(b,this);return!0};this.unregisterExtension=function(b){if(!a(b))throw"Illegal argument type: extension name must be a string";for(var e=!1,f=0;f<t.length;++f){var g=t[f];if(g.name===b){t.splice(f,1);e=!0;this._debug("Unregistered extension",
b);b=g.extension;c(b.unregistered)&&b.unregistered();break}}return e};this.getExtension=function(a){for(var b=0;b<t.length;++b){var c=t[b];if(c.name===a)return c.extension}return null};this.getName=function(){return fa};this.getClientId=function(){return E};this.getURL=function(){return q.url};this.getTransport=function(){return z};this.getConfiguration=function(){return this._mixin(!0,{},q)};this.getAdvice=function(){return this._mixin(!0,{},u)};org.cometd.WebSocket=window.WebSocket;org.cometd.WebSocket||
(org.cometd.WebSocket=window.MozWebSocket)};
Sfdc.provide("Sfdc.CometD",function(c){function d(){var b=new org.cometd.LongPollingTransport,b=org.cometd.Transport.derive(b);b.xhrSend=function(a){a.headers&&a.headers.contentType&&delete a.headers.contentType;return c.Ajax.request(a.url,{async:!0!==a.sync,method:"POST",contentType:"application/json;charset\x3dUTF-8",data:a.body,headers:a.headers,success:a.onSuccess,failure:function(b,c,d){a.onError(c.status,b)}})};return b}function e(b){b=new org.cometd.CallbackPollingTransport;b=org.cometd.Transport.derive(b);
b.jsonpSend=function(a){c.Ajax.jsonp(a.url,{jsonp:"jsonp",data:{message:a.body},success:a.onSuccess,failure:function(b,c,d){a.onError(c.status,b)},escape:encodeURIComponent})};return b}org.cometd.JSON.toJSON=c.JSON.stringify;org.cometd.JSON.fromJSON=c.JSON.parse;return function(b){var a=new org.cometd.Cometd(b),c=a.init;a.registerTransport("long-polling",new d);a.registerTransport("callback-polling",new e);a.init=function(){a.isDisconnected()&&c.apply(a,arguments)};return a}}(Sfdc));
Sfdc.provide("Sfdc.cometd",{init:function(){Sfdc.cometd=new Sfdc.CometD;return Sfdc.cometd.init.apply(Sfdc.cometd,arguments)}});

//# sourceMappingURL=/javascript/1568710079000/ui-sfdc-javascript-impl/source/SfdcExtended.js.map
